import React, { useState } from 'react';
import { Alert, Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import { Feather, Ionicons } from '@expo/vector-icons';
import { Header, PrimaryButton, RoundedCard, ScreenShell, SectionTitle } from '../components';
import { formatMoney } from '../locale';
import { COLORS, FONT, TYPE } from '../theme';
import type { RideFareBid } from '../parity/types';
import type { VehicleMode } from './vehicle';
import { captainOffers } from './mobility';

export type RideParityData={country:string;city:string;selectedRideName:string;baseFare:number;pickup:string;destination:string;selectedBidId:string|null;selectedVehicleMode:VehicleMode};
export type RideParityActions={go:(screen:any)=>void;selectBid:(id:string|null)=>void};

export function RideFareBidsScreen({data,actions}:{data:RideParityData;actions:RideParityActions}){
  const bids:RideFareBid[]=captainOffers(data.baseFare,data.country,data.selectedVehicleMode).map((captain)=>({
    id:captain.id,
    driverName:captain.captainName,
    rating:captain.rating,
    etaMinutes:captain.etaMinutes,
    fare:captain.fare,
    vehicle:`${captain.vehicleMake} ${captain.vehicleModel} · ${captain.registration}`,
  }));
  const [offer,setOffer]=useState(String(data.baseFare));
  return <ScreenShell><Header title="Driver offers" onBack={()=>actions.go('chooseRide')}/><ScrollView style={styles.flex} contentContainerStyle={styles.scroll}><Text style={styles.title}>Choose your fare</Text><Text style={styles.subtitle}>{data.pickup} → {data.destination}</Text><RoundedCard style={styles.offerCard}><Text style={styles.offerLabel}>Your suggested fare</Text><Text style={styles.offerValue}>{formatMoney(data.country,Number(offer)||data.baseFare)}</Text><View style={styles.offerControls}><Pressable onPress={()=>setOffer(String(Math.max(1000,(Number(offer)||data.baseFare)-500)))} style={styles.circle}><Feather name="minus" size={18}/></Pressable><Text style={styles.offerHint}>Adjust in UGX 500 steps</Text><Pressable onPress={()=>setOffer(String((Number(offer)||data.baseFare)+500))} style={styles.circle}><Feather name="plus" size={18}/></Pressable></View></RoundedCard><SectionTitle title="Nearby drivers"/><View style={styles.list}>{bids.map(b=>{const active=data.selectedBidId===b.id;return <Pressable key={b.id} onPress={()=>actions.selectBid(b.id)} style={[styles.bid,active&&styles.bidActive]}><View style={styles.avatar}><Text style={styles.avatarText}>{b.driverName.slice(0,1)}</Text></View><View style={styles.flex}><Text style={styles.driver}>{b.driverName} · ★ {b.rating}</Text><Text style={styles.meta}>{b.vehicle}</Text><Text style={styles.meta}>{b.etaMinutes} min away</Text></View><View style={{alignItems:'flex-end'}}><Text style={styles.fare}>{formatMoney(data.country,b.fare)}</Text><View style={[styles.radio,active&&styles.radioActive]}>{active?<View style={styles.radioDot}/>:null}</View></View></Pressable>})}</View><PrimaryButton disabled={!data.selectedBidId} label="Continue with driver" onPress={()=>actions.go('confirmBooking')}/><Pressable onPress={()=>actions.go('confirmBooking')}><Text style={styles.link}>Skip offers and use standard matching</Text></Pressable></ScrollView></ScreenShell>
}

export function RideSafetyScreen({data,actions}:{data:RideParityData;actions:RideParityActions}){return <ScreenShell><Header title="Safety toolkit" onBack={()=>actions.go('driver')}/><ScrollView style={styles.flex} contentContainerStyle={styles.scroll}><View style={styles.safetyHero}><Ionicons name="shield-checkmark-outline" size={52}/><Text style={styles.safetyTitle}>Your trip safety tools</Text><Text style={styles.safetyBody}>Use these tools during a ride or Boda trip. Trip details remain available in Activity.</Text></View><RoundedCard><SafetyRow icon="share-social-outline" title="Share trip" body="Share driver, vehicle and live trip details" onPress={()=>Alert.alert('Share trip','Trip sharing is ready to connect to the native share sheet.')}/><SafetyRow icon="call-outline" title="Call support" body="Get help with an active trip" onPress={()=>actions.go('support')}/><SafetyRow icon="alert-circle-outline" title="Report a safety issue" body="Create a priority safety report" onPress={()=>Alert.alert('Safety report','A priority safety report has been started.')}/><SafetyRow icon="medical-outline" title="Emergency guidance" body="Quick access to local emergency guidance" onPress={()=>Alert.alert('Emergency guidance','If you are in immediate danger, contact local emergency services.')}/></RoundedCard><RoundedCard style={styles.tripCard}><Text style={styles.driver}>{data.selectedRideName}</Text><Text style={styles.meta}>{data.pickup} → {data.destination}</Text></RoundedCard></ScrollView></ScreenShell>}
function SafetyRow({icon,title,body,onPress}:{icon:string;title:string;body:string;onPress:()=>void}){return <Pressable onPress={onPress} style={styles.safetyRow}><View style={styles.safetyIcon}><Ionicons name={icon as any} size={22}/></View><View style={styles.flex}><Text style={styles.driver}>{title}</Text><Text style={styles.meta}>{body}</Text></View><Feather name="chevron-right" size={21}/></Pressable>}

const styles=StyleSheet.create({flex:{flex:1},scroll:{paddingHorizontal:14,paddingTop:14,paddingBottom:34,gap:12},title:{fontFamily:FONT.bold,fontSize:28,fontWeight:'900'},subtitle:{...TYPE.body,color:COLORS.muted},offerCard:{padding:16,alignItems:'center',gap:10,shadowOpacity:0},offerLabel:{...TYPE.caption,color:COLORS.muted},offerValue:{fontFamily:FONT.bold,fontSize:29,fontWeight:'900'},offerControls:{flexDirection:'row',alignItems:'center',gap:14},circle:{width:38,height:38,borderRadius:19,borderWidth:1,borderColor:COLORS.line,alignItems:'center',justifyContent:'center'},offerHint:{...TYPE.small,color:COLORS.muted},list:{gap:10},bid:{minHeight:92,borderWidth:1,borderColor:COLORS.line,borderRadius:18,padding:13,flexDirection:'row',alignItems:'center',gap:11},bidActive:{borderColor:COLORS.red,backgroundColor:'#FFF8F7'},avatar:{width:48,height:48,borderRadius:24,backgroundColor:COLORS.yellow,alignItems:'center',justifyContent:'center'},avatarText:{fontFamily:FONT.bold,fontSize:19,fontWeight:'900'},driver:{...TYPE.cardTitle},meta:{...TYPE.small,color:COLORS.muted,marginTop:3},fare:{fontFamily:FONT.bold,fontSize:16,fontWeight:'900'},radio:{width:22,height:22,borderRadius:11,borderWidth:2,borderColor:COLORS.lineDark,alignItems:'center',justifyContent:'center',marginTop:8},radioActive:{borderColor:COLORS.red},radioDot:{width:10,height:10,borderRadius:5,backgroundColor:COLORS.red},link:{...TYPE.action,color:COLORS.red,textAlign:'center',padding:8},safetyHero:{minHeight:190,borderRadius:23,backgroundColor:COLORS.yellow,padding:20,alignItems:'center',justifyContent:'center',gap:8},safetyTitle:{fontFamily:FONT.bold,fontSize:24,fontWeight:'900'},safetyBody:{...TYPE.body,textAlign:'center',lineHeight:21},safetyRow:{minHeight:76,flexDirection:'row',alignItems:'center',gap:11,borderBottomWidth:1,borderBottomColor:COLORS.line,paddingHorizontal:13},safetyIcon:{width:42,height:42,borderRadius:13,backgroundColor:COLORS.surface,alignItems:'center',justifyContent:'center'},tripCard:{padding:15,shadowOpacity:0}});
