import React, { memo, useMemo } from 'react';
import { ActivityIndicator, FlatList, Platform, Pressable, StyleSheet, Text, View, type ListRenderItem } from 'react-native';
import { COLORS, SPACE, TYPE } from '../theme';
import { useSafeAreaInsets } from 'react-native-safe-area-context';
import type { AppEngineContext, AppEnginePageDefinition, AppEnginePageState, AppEngineSectionDefinition } from './types';
import { resolveAppEnginePage } from './runtime';

type Props={page:AppEnginePageDefinition;context:AppEngineContext;state?:AppEnginePageState;renderSection:(section:AppEngineSectionDefinition)=>React.ReactElement|null;header?:React.ReactElement|null;footer?:React.ReactElement|null;onRetry?:()=>void};

export const AppEnginePage=memo(function AppEnginePage({page,context,state='ready',renderSection,header,footer,onRetry}:Props){const insets=useSafeAreaInsets();const resolved=useMemo(()=>resolveAppEnginePage(page,context),[page,context]);const renderItem:ListRenderItem<AppEngineSectionDefinition>=({item})=><View style={styles.section}>{renderSection(item)}</View>;if(state==='loading')return <View accessibilityRole="progressbar" style={styles.center}><ActivityIndicator size="large" color={COLORS.yellowDeep}/><Text style={styles.stateText}>Loading {page.title??'page'}…</Text></View>;if(state==='error')return <View style={styles.center}><Text style={styles.stateTitle}>We couldn’t load this page</Text><Text style={styles.stateText}>Check your connection and try again.</Text>{onRetry?<Pressable accessibilityRole="button" onPress={onRetry} style={styles.retry}><Text style={styles.retryText}>Try again</Text></Pressable>:null}</View>;if(!resolved||state==='empty'||!resolved.sections.length)return <View style={styles.center}><Text style={styles.stateTitle}>Nothing to show yet</Text><Text style={styles.stateText}>Content for your city will appear here when available.</Text></View>;return <FlatList data={resolved.sections} keyExtractor={item=>item.id} renderItem={renderItem} ListHeaderComponent={header} ListFooterComponent={footer} contentContainerStyle={[styles.content,{paddingBottom:62+Math.max(insets.bottom,8)+SPACE.md}]} scrollIndicatorInsets={{bottom:62+Math.max(insets.bottom,8)}} showsVerticalScrollIndicator={false} initialNumToRender={5} maxToRenderPerBatch={4} updateCellsBatchingPeriod={40} windowSize={7} removeClippedSubviews={Platform.OS==='android'}/>});

const styles=StyleSheet.create({content:{paddingHorizontal:SPACE.lg,paddingTop:SPACE.xxs,paddingBottom:32},section:{marginTop:28},center:{flex:1,alignItems:'center',justifyContent:'center',padding:32,backgroundColor:COLORS.surface},stateTitle:{...TYPE.sectionTitle,textAlign:'center'},stateText:{...TYPE.body,color:COLORS.muted,textAlign:'center',marginTop:8},retry:{minHeight:48,borderRadius:16,backgroundColor:COLORS.yellow,alignItems:'center',justifyContent:'center',paddingHorizontal:20,marginTop:18},retryText:{...TYPE.button,color:COLORS.black}});
