import type { AppEngineContext, AppEnginePageDefinition, AppEngineSectionDefinition, AppEngineTargeting } from './types';

function matchesTargeting(targeting:AppEngineTargeting|undefined,context:AppEngineContext){if(!targeting)return true;const now=(context.now??new Date()).getTime();return(!targeting.countries||targeting.countries.includes(context.country))&&(!targeting.cities||targeting.cities.includes(context.city))&&(!targeting.audiences||targeting.audiences.includes(context.audience)||targeting.audiences.includes('all'))&&(!targeting.membershipRequired||context.member)&&(!targeting.startAt||new Date(targeting.startAt).getTime()<=now)&&(!targeting.endAt||new Date(targeting.endAt).getTime()>=now)}

export function resolveAppEnginePage(page:AppEnginePageDefinition,context:AppEngineContext):AppEnginePageDefinition|null{if(!matchesTargeting(page.targeting,context))return null;const sections=page.sections.filter(section=>section.enabled&&matchesTargeting(section.targeting,context)&&(!section.promo||section.promo.enabled&&matchesTargeting(section.promo.targeting,context))).sort((a,b)=>b.priority-a.priority);return{...page,sections}}

export function validateAppEnginePage(page:AppEnginePageDefinition){const errors:string[]=[];const warnings:string[]=[];if(!page.id)errors.push('Page id is required');if(!page.version)errors.push(`Page ${page.id} requires a version`);if(page.header.showSearch&&!page.header.search)warnings.push(`Page ${page.id} should define a contextual search configuration`);if(page.header.search&&!page.header.search.placeholder.trim())errors.push(`Page ${page.id} search requires a placeholder`);const ids=new Set<string>();for(const section of page.sections){if(ids.has(section.id))errors.push(`Duplicate section id: ${section.id}`);ids.add(section.id);if(section.type==='banner-carousel'&&!section.promo&&!section.items?.length)warnings.push(`${section.id} has no campaign content`);if(section.promo&&!section.promo.creative.alt)errors.push(`${section.id} promotion requires accessible creative alt text`);if(section.cta&&!section.cta.route.screen)errors.push(`${section.id} CTA requires a route`)}return{valid:errors.length===0,errors,warnings}}

export function sectionImpressionKey(pageId:string,section:AppEngineSectionDefinition){return`${pageId}:${section.id}:${section.analytics?.impressionEvent??'view'}`}
