import React, { useMemo, useState } from 'react';
import { FlatList, Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import { Feather, Ionicons } from '@expo/vector-icons';
import { CategoryArtwork, KareebuPageHeader, KareebuSearchField, RoundedCard, ScreenShell, SectionTitle } from '../components';
import { COLORS, RADIUS, SHADOW, SPACE, TYPE } from '../theme';
import { categoryVisual } from './categoryVisuals';
import { VERTICAL_CONFIGS, type VerticalCategory, type VerticalId } from './verticals';
import { PromoCarousel } from '../promotions/PromoCarousel';
import { VerticalPromoCarousel } from '../promotions/VerticalPromoCarousel';
import type { Screen } from '../types';
import { verticalLandingBlueprint, type VerticalSection, type VerticalSeller } from './verticalLandingBlueprint';
import { ProductCard, SellerCard } from './VerticalMerchandisingCards';
import { searchContextForVertical, verticalSearchContext } from '../search/context';
import { CategoryLandingBanner } from '../components/CategoryLandingBanner';
import { mainPromotionalBannerForCategory } from '../promotions/promotionalContentRegistry';
import { SquarePromotionCarousel } from '../promotions/SquarePromotionCarousel';

function CategoryTile({category,onPress,compact=false}:{category:VerticalCategory;onPress:()=>void;compact?:boolean}){const visual=categoryVisual(category.visualKey);const tones={yellow:COLORS.yellowSoft,cream:COLORS.yellowWash,green:COLORS.greenSoft,rose:'#FFF0EE',blue:'#EEF4FA'};return <Pressable accessibilityRole="button" accessibilityLabel={category.label} accessibilityHint="Opens this category" onPress={onPress} style={({pressed})=>[styles.category,compact&&styles.collectionCategory,pressed&&styles.pressed]}><View style={[styles.categoryArt,{backgroundColor:tones[visual.tone]}]}><CategoryArtwork visualKey={category.visualKey} size="standard"/></View><Text numberOfLines={2} style={styles.categoryLabel}>{category.label}</Text>{category.description?<Text style={styles.categoryBody}>{category.description}</Text>:null}</Pressable>}

function LandingSection({section,go,onCategory,onSeller,onProduct,primaryCategory,categoryOptions}:{section:VerticalSection;go:(screen:Screen)=>void;onCategory:(id:string,label:string)=>void;onSeller:(id:string)=>void;onProduct:(id:string)=>void;primaryCategory?:VerticalCategory;categoryOptions:VerticalCategory[]}){
  if((section.type==='seller_carousel'||section.type==='brand_carousel'||section.type==='nearby')&&!section.sellers?.length)return null;
  if((section.type==='product_carousel'||section.type==='bestseller_carousel'||section.type==='most_ordered'||section.type==='reorder'||section.type==='offer_carousel')&&!section.products?.length)return null;
  if(section.type==='hero_promo')return section.promos?.length?<View style={styles.carouselBleed}><VerticalPromoCarousel campaigns={section.promos} onPress={(campaign)=>campaign.ctaScreen==='categoryItems'&&primaryCategory?onCategory(primaryCategory.id,primaryCategory.label):go(campaign.ctaScreen)}/></View>:null;
  if(section.type==='promo_carousel'||section.type==='editorial_banner')return section.promos?.length?<View style={styles.carouselBleed}><PromoCarousel campaigns={section.promos} onPress={(campaign)=>campaign.ctaScreen==='categoryItems'&&primaryCategory?onCategory(primaryCategory.id,primaryCategory.label):go(campaign.ctaScreen)}/></View>:null;
  if(section.type==='category_grid')return <View><SectionTitle title={section.title??'Categories'}/>{section.subtitle?<Text style={styles.sectionSubtitle}>{section.subtitle}</Text>:null}<ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={styles.categoryRail}>{section.categories?.map(category=><CategoryTile compact key={category.id} category={category} onPress={()=>onCategory(category.id,category.label)}/>)}</ScrollView></View>;
  if(section.type==='category_carousel')return <View><SectionTitle title={section.title??'Collections'}/>{section.subtitle?<Text style={styles.sectionSubtitle}>{section.subtitle}</Text>:null}<ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={styles.rail}>{section.categories?.map(category=><CategoryTile compact key={category.id} category={category} onPress={()=>onCategory(category.id,category.label)}/>)}</ScrollView></View>;
  if(section.type==='square_promotion'&&section.promotionalAssets?.length)return <View><SectionTitle title={section.title??'Promotions'}/><SquarePromotionCarousel assets={section.promotionalAssets} onPress={asset=>{const target=categoryOptions.find(category=>category.id===asset.destination.categoryId);if(target)onCategory(target.id,target.label);else go(asset.destination.screen)}}/></View>;
  if(section.type==='seller_carousel'||section.type==='brand_carousel'||section.type==='nearby')return <View><SectionTitle title={section.title??'Sellers'} action={section.ctaLabel} onAction={section.route?()=>go(section.route!):undefined}/>{section.subtitle?<Text style={styles.sectionSubtitle}>{section.subtitle}</Text>:null}<ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={styles.rail}>{section.sellers?.map(seller=><SellerCard key={seller.id} seller={seller} onPress={()=>onSeller(seller.id)}/>)}</ScrollView></View>;
  if(section.type==='product_carousel'||section.type==='bestseller_carousel'||section.type==='most_ordered'||section.type==='reorder'||section.type==='offer_carousel')return <View><SectionTitle title={section.title??'Products'} action={section.ctaLabel} onAction={section.route?()=>go(section.route!):undefined}/>{section.subtitle?<Text style={styles.sectionSubtitle}>{section.subtitle}</Text>:null}<ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={styles.rail}>{section.products?.map(product=><ProductCard key={product.id} product={product} onPress={()=>onProduct(product.id)}/>)}</ScrollView></View>;
  if(section.type==='all_results')return <Pressable accessibilityRole="button" onPress={()=>section.route&&go(section.route)} style={styles.allResults}><View style={styles.nearbyIcon}><Ionicons name="grid-outline" size={27} color={COLORS.black}/></View><View style={styles.flex}><Text style={styles.nearbyTitle}>{section.title}</Text><Text style={styles.nearbyBody}>Browse the complete collection and compare available sellers.</Text></View><Feather name="arrow-right" size={22} color={COLORS.black}/></Pressable>;
  return null;
}

export function VerticalLandingScreen({verticalId,country,city,go,onBack,onCategory,onSeller,onProduct,sellers}:{verticalId:VerticalId;country:string;city:string;go:(screen:Screen)=>void;onBack:()=>void;onCategory:(id:string,label:string)=>void;onSeller:(id:string)=>void;onProduct:(id:string)=>void;sellers?:VerticalSeller[]}){
  const [query,setQuery]=useState('');
  const blueprint=useMemo(()=>verticalLandingBlueprint(verticalId,country,city,sellers),[verticalId,country,city,sellers]);
  const config=VERTICAL_CONFIGS[verticalId];
  const landingBanner=mainPromotionalBannerForCategory(verticalId);
  const sections=useMemo(()=>{
    if(!query.trim())return blueprint.sections.filter(section=>section.enabled);
    const term=query.trim().toLowerCase();
    const categories=blueprint.sections.find(section=>section.type==='category_grid')?.categories?.filter(category=>category.label.toLowerCase().includes(term))??[];
    return [{id:`${verticalId}-search`,type:'category_grid' as const,title:'Search results',categories,priority:100,enabled:true,country,city}];
  },[blueprint.sections,city,country,query,verticalId]);
  return <ScreenShell><KareebuPageHeader title={blueprint.title} country={country} city={city} locationEnabled={false} searchEnabled searchContext={searchContextForVertical(verticalId,config.searchPlaceholder,{market:country,city})} searchValue={query} onSearchChange={setQuery} onBack={onBack} rightIcon="options-outline" rightLabel={`${blueprint.title} options`}/><FlatList data={sections} keyExtractor={section=>section.id} renderItem={({item})=><LandingSection section={item} go={go} onCategory={onCategory} onSeller={onSeller} onProduct={onProduct} primaryCategory={config.categories[0]} categoryOptions={config.categories}/>} style={styles.flex} contentContainerStyle={styles.page} keyboardShouldPersistTaps="handled" showsVerticalScrollIndicator={false} initialNumToRender={4} maxToRenderPerBatch={3} windowSize={5} removeClippedSubviews ListHeaderComponent={<View style={styles.landingIntro}>{landingBanner&&config.categories[0]?<CategoryLandingBanner banner={landingBanner} onPress={()=>onCategory(config.categories[0]!.id,config.categories[0]!.label)} accessibilityLabel={`${landingBanner.accessibilityLabel} Opens ${config.categories[0]!.label}.`}/>:null}<Text style={styles.subtitle}>{blueprint.subtitle}</Text></View>} ListFooterComponent={<View style={styles.trust}><Ionicons name="shield-checkmark-outline" size={22}/><Text style={styles.trustText}>{config.trustMessage}</Text></View>}/></ScreenShell>;
}

export function VerticalCategoryScreen({title,city,onOpenShops}:{title:string;city:string;onOpenShops:()=>void}){return <ScreenShell><KareebuPageHeader title={title} city={city} locationEnabled={false} onBack={onOpenShops}/><ScrollView style={styles.flex} contentContainerStyle={styles.page}><View><Text style={styles.title}>{title}</Text><Text style={styles.subtitle}>Products and nearby sellers in {city}</Text></View><KareebuSearchField context={verticalSearchContext(title,`Search ${title.toLowerCase()}`,{city})} onPress={onOpenShops}/><SectionTitle title="Available sellers"/><Pressable onPress={onOpenShops}><RoundedCard style={styles.nearby}><View style={styles.nearbyIcon}><Ionicons name="storefront-outline" size={28}/></View><View style={styles.flex}><Text style={styles.nearbyTitle}>Browse verified marketplace listings</Text><Text style={styles.nearbyBody}>Seller, stock, delivery and returns details appear with each live listing.</Text></View><Feather name="chevron-right" size={22}/></RoundedCard></Pressable><View style={styles.trust}><Ionicons name="information-circle-outline" size={22}/><Text style={styles.trustText}>Catalogue results are supplied through the commerce integration. No stock or availability is assumed.</Text></View></ScrollView></ScreenShell>}
const styles=StyleSheet.create({flex:{flex:1},page:{paddingHorizontal:SPACE.lg,paddingTop:SPACE.md,paddingBottom:36,gap:SPACE.lg},landingIntro:{gap:SPACE.md},title:{...TYPE.screenTitle,color:COLORS.black},subtitle:{...TYPE.body,color:COLORS.muted,marginTop:4},sectionSubtitle:{...TYPE.small,color:COLORS.muted,marginTop:-SPACE.sm,marginBottom:SPACE.md},carouselBleed:{marginHorizontal:-SPACE.lg},rail:{gap:SPACE.md,paddingRight:SPACE.lg,paddingBottom:4},categoryRail:{gap:SPACE.sm,paddingRight:SPACE.lg,paddingBottom:2},grid:{flexDirection:'row',flexWrap:'wrap',gap:SPACE.md},category:{width:'31.2%',minHeight:132,borderRadius:RADIUS.lg,backgroundColor:COLORS.white,padding:SPACE.sm,alignItems:'center',...SHADOW},collectionCategory:{width:112,minHeight:112,padding:8},categoryArt:{width:64,height:64,borderRadius:18,alignItems:'center',justifyContent:'center',overflow:'hidden'},categoryLabel:{...TYPE.small,color:COLORS.black,fontWeight:'800',textAlign:'center',marginTop:6},categoryBody:{...TYPE.caption,color:COLORS.muted,textAlign:'center',marginTop:3},pressed:{opacity:.76,transform:[{scale:.98}]},nearby:{minHeight:94,padding:SPACE.lg,flexDirection:'row',alignItems:'center',gap:SPACE.md,borderWidth:0},nearbyIcon:{width:54,height:54,borderRadius:18,backgroundColor:COLORS.yellow,alignItems:'center',justifyContent:'center'},nearbyTitle:{...TYPE.cardTitle},nearbyBody:{...TYPE.small,color:COLORS.muted,marginTop:4},allResults:{minHeight:96,borderRadius:RADIUS.lg,backgroundColor:COLORS.white,padding:SPACE.lg,flexDirection:'row',alignItems:'center',gap:SPACE.md,...SHADOW},trust:{borderRadius:RADIUS.lg,backgroundColor:COLORS.yellowWash,padding:SPACE.lg,flexDirection:'row',alignItems:'flex-start',gap:SPACE.md},trustText:{...TYPE.small,color:COLORS.black,flex:1,lineHeight:18},fixtureNote:{...TYPE.caption,color:COLORS.muted,textAlign:'center'}});
