import type { ImageSourcePropType } from 'react-native';
import type { PromotionCampaign } from '../promotions/types';
import { promotionalBannerAssets } from '../promotions/promotionalBannerAssets';

export type VerticalId='pharmacy'|'butchery'|'pets'|'gifts'|'electronics'|'beauty'|'fashion'|'groceries'|'home';
export type VerticalCategory={id:string;label:string;description?:string;visualKey:string};
export type VerticalLandingConfig={id:VerticalId;title:string;subtitle:string;searchPlaceholder:string;heroImage:ImageSourcePropType;heroHeadline:string;heroBody:string;categories:VerticalCategory[];secondaryCategories?:VerticalCategory[];trustMessage:string;countryOverrides?:Record<string,Partial<Pick<VerticalLandingConfig,'subtitle'|'categories'>>>};

const categories=(domain:string,items:Array<[string,string,string?]>)=>items.map(([id,label,visual])=>({id,label,visualKey:visual??`${domain}.${id}`}));

export const VERTICAL_CONFIGS:Record<VerticalId,VerticalLandingConfig>={
  pharmacy:{id:'pharmacy',title:'Pharmacy & Wellness',subtitle:'Medicines, wellness and personal care in one place',searchPlaceholder:'Search medicines & wellness',heroImage:require('../../assets/kareebu-plus/realistic-v9/pharmacy.jpg'),heroHeadline:'Care, organised around what you need',heroBody:'Browse health needs, vitamins, personal care, skincare and family health by department.',categories:categories('pharmacy',[
    ['medicines','Medicines & Health','pharmacy.medicines'],['vitamins-supplements','Vitamins & Supplements','pharmacy.vitamins'],['personal-care','Personal Care','pharmacy.personal-care'],['skincare','Skincare','beauty.skincare'],['haircare','Haircare','beauty.hair'],['baby-child','Baby & Child','pharmacy.baby-care'],['cold-flu','Cold & Flu','pharmacy.cold-flu'],['pain-relief','Pain Relief','pharmacy.pain-relief'],['first-aid','First Aid','pharmacy.first-aid'],['allergy','Allergy','pharmacy.allergy'],['digestive','Digestive Health','pharmacy.digestive'],['sexual-wellness','Sexual Wellness'],['fitness-nutrition','Fitness & Nutrition'],['home-health','Home Health','pharmacy.home-health']
  ]),trustMessage:'Prescription fulfilment requires pharmacy review where applicable. Kareebu does not diagnose, approve or prescribe medicines.'},
  butchery:{id:'butchery',title:'Butchery & Seafood',subtitle:'Fresh cuts and seafood from specialist sellers',searchPlaceholder:'Search meat, fish & seafood',heroImage:require('../../assets/kareebu-plus/realistic-v9/groceries.jpg'),heroHeadline:'Fresh for your table',heroBody:'Browse configured specialist butchers, fresh cuts and seafood sellers.',categories:categories('butchery',[[ 'beef','Beef'],['goat','Goat'],['chicken','Chicken'],['fish','Fish'],['seafood','Seafood'],['bbq','BBQ picks']]),trustMessage:'Freshness, cut, weight, stock and delivery are confirmed by the seller before checkout.'},
  pets:{id:'pets',title:'Pet Stores',subtitle:'Everything for your pets',searchPlaceholder:'Search pet food, toys & care',heroImage:require('../../assets/kareebu-plus/realistic-v9/pet-supplies.jpg'),heroHeadline:'Everything they love',heroBody:'Pet food, treats and everyday care organised by pet.',categories:categories('pets',[[ 'dogs','Dogs'],['cats','Cats'],['birds','Birds'],['small-pets','Small pets']]),trustMessage:'Product availability and delivery timing are confirmed by each pet store.'},
  gifts:{id:'gifts',title:'Gifts & Flowers',subtitle:'Send something thoughtful',searchPlaceholder:'Search gifts, flowers & hampers',heroImage:require('../../assets/kareebu-plus/realistic-v9/flowers.jpg'),heroHeadline:'Send something special',heroBody:'Flowers, hampers and gifts for meaningful moments.',categories:categories('gifts',[[ 'birthday','Birthday'],['anniversary','Anniversary'],['congratulations','Congratulations'],['thank-you','Thank you'],['new-baby','New baby'],['just-because','Just because'],['flowers','Flowers'],['hampers','Hampers']]),trustMessage:'Scheduled and same-day options appear only when a merchant confirms them.'},
  electronics:{id:'electronics',title:'Electronics',subtitle:'Technology for everyday life',searchPlaceholder:'Search phones, tech & appliances',heroImage:require('../../assets/kareebu-plus/realistic-v9/electronics.jpg'),heroHeadline:'Upgrade your everyday',heroBody:'Move from departments into useful subcategories, brands and products.',categories:categories('electronics',[
    ['phones','Phones'],['phone-accessories','Phone Accessories'],['computers','Computing','electronics.computing'],['computer-accessories','Computer Accessories'],['audio','Audio'],['gaming','Gaming'],['tv','TVs','electronics.tvs'],['appliances','Appliances'],['kitchen-appliances','Kitchen Appliances'],['power','Power & Accessories','electronics.power'],['cameras','Cameras','electronics.cameras'],['wearables','Wearables','electronics.wearables'],['smart-home','Smart Home','electronics.smart-home']
  ]),trustMessage:'Seller, stock, warranty, returns and delivery terms are shown before purchase.'},
  beauty:{id:'beauty',title:'Beauty',subtitle:'Beauty & personal care',searchPlaceholder:'Search beauty & personal care',heroImage:require('../../assets/kareebu-plus/realistic-v9/beauty.jpg'),heroHeadline:'Build your routine',heroBody:'Makeup, skincare, hair, fragrance and personal care organised into useful destinations.',categories:categories('beauty',[[ 'makeup','Makeup'],['skincare','Skincare'],['hair','Hair'],['fragrance','Fragrance'],['personal-care','Personal Care','beauty.body'],['tools','Beauty Tools','beauty.makeup']]),trustMessage:'Product details and availability are supplied by each seller.'},
  fashion:{id:'fashion',title:'Fashion & Beauty',subtitle:'Clothing, shoes, beauty and more',searchPlaceholder:'Search fashion & beauty',heroImage:require('../../assets/kareebu-plus/realistic-v9/fashion.jpg'),heroHeadline:'Express your style',heroBody:'Explore clothing, shoes, beauty, haircare, fragrance and accessories.',categories:categories('fashion',[[ 'women','Women'],['men','Men'],['kids','Kids','fashion.children'],['shoes','Shoes'],['bags','Bags'],['jewellery-watches','Jewellery & Watches'],['accessories','Accessories'],['skincare','Skincare','beauty.skincare'],['makeup','Makeup','beauty.makeup'],['haircare','Haircare','beauty.hair'],['fragrance','Fragrance','beauty.fragrance'],['beauty-tools','Beauty Tools','beauty.makeup']]),trustMessage:'Sizing, returns and seller terms are shown on eligible products.'},
  groceries:{id:'groceries',title:'Groceries',subtitle:'Your everyday shop, delivered',searchPlaceholder:'Search groceries',heroImage:require('../../assets/kareebu-plus/realistic-v9/groceries.jpg'),heroHeadline:'Fresh food and essentials',heroBody:'Browse the supermarket by aisle and shopping mission rather than one long product list.',categories:categories('groceries',[
    ['fresh-produce','Fresh Produce','groceries.fresh'],['meat','Meat','groceries.meat-fish'],['chicken','Chicken','butchery.chicken'],['fish-seafood','Fish & Seafood','butchery.fish'],['dairy','Dairy & Eggs'],['bakery','Bakery'],['rice-pasta-pulses','Rice, Pasta & Pulses','groceries.cooking'],['breakfast','Breakfast','food.breakfast'],['coffee-tea','Coffee & Tea','food.coffee'],['beverages','Water & Beverages','groceries.drinks'],['snacks','Snacks'],['frozen','Frozen','groceries.fresh'],['household','Household'],['personal-care','Personal Care'],['baby','Baby'],['pet','Pet Supplies'],['health','Health','pharmacy.vitamins'],['flowers','Flowers','shops.giftsFlowers']
  ]),trustMessage:'Stock, substitutions, seller and delivery information are confirmed before checkout.'},
  home:{id:'home',title:'Home & Kitchen',subtitle:'Useful things for every room',searchPlaceholder:'Search home & household',heroImage:require('../../assets/kareebu-plus/realistic-v9/home.jpg'),heroHeadline:'Make home work better',heroBody:'Kitchen, storage, cleaning, décor and everyday home essentials.',categories:categories('home',[[ 'kitchen','Kitchen'],['storage','Storage'],['decor','Decor'],['bedding','Bedding','home.bedding'],['bathroom','Bathroom'],['lighting','Lighting','home.lighting'],['appliances','Appliances','electronics.appliances'],['cleaning','Cleaning'],['garden','Garden'],['diy','DIY','home.diy']]),trustMessage:'Stock, seller and delivery information is confirmed before checkout.'},
};

const VERTICAL_PROMO_ART:Record<VerticalId,ImageSourcePropType[]>={
  pharmacy:[require('../../assets/kareebu-plus/realistic-v9/pharmacy.jpg'),require('../../assets/kareebu-plus/realistic-v9/vitamins-supplements.jpg'),require('../../assets/kareebu-plus/realistic-v9/personal-care.jpg')],
  butchery:[require('../../assets/kareebu-plus/lifestyle-cutouts/grocery-beef.png'),require('../../assets/kareebu-plus/lifestyle-cutouts/grocery-fish.png'),require('../../assets/kareebu-plus/lifestyle-cutouts/grocery-seafood.png')],
  pets:[require('../../assets/kareebu-plus/realistic-v9/pet-supplies.jpg'),require('../../assets/kareebu-plus/realistic-v9/toys.png'),require('../../assets/kareebu-plus/realistic-v9/pet-supplies.jpg')],
  gifts:[require('../../assets/kareebu-plus/realistic-v9/flowers.jpg'),require('../../assets/kareebu-plus/realistic-v9/send-gift.jpg'),require('../../assets/kareebu-plus/realistic-v9/flowers.jpg')],
  electronics:[require('../../assets/kareebu-plus/realistic-v9/electronics.jpg'),require('../../assets/kareebu-plus/realistic-v9/audio.jpg'),require('../../assets/kareebu-plus/realistic-v9/computing.jpg')],
  beauty:[require('../../assets/kareebu-plus/realistic-v9/beauty.jpg'),require('../../assets/kareebu-plus/realistic-v9/skincare.jpg'),require('../../assets/kareebu-plus/realistic-v9/haircare.jpg')],
  fashion:[require('../../assets/kareebu-plus/realistic-v9/fashion.jpg'),require('../../assets/kareebu-plus/realistic-v9/shoes.jpg'),require('../../assets/kareebu-plus/realistic-v9/accessories.jpg')],
  groceries:[require('../../assets/kareebu-plus/realistic-v9/groceries.jpg'),require('../../assets/kareebu-plus/lifestyle-cutouts/grocery-fresh-food.png'),require('../../assets/kareebu-plus/lifestyle-cutouts/grocery-household-cleaning.png')],
  home:[require('../../assets/kareebu-plus/realistic-v9/home.jpg'),require('../../assets/kareebu-plus/realistic-v9/kitchen.jpg'),require('../../assets/kareebu-plus/realistic-v9/home-storage.png')],
};

export function verticalPromotions(config:VerticalLandingConfig,country?:string,city?:string):PromotionCampaign[]{
  const service=config.id==='pharmacy'?'pharmacy':config.id==='groceries'?'groceries':'shops';
  const art=VERTICAL_PROMO_ART[config.id];
  const approvedHero:Partial<Record<VerticalId,ImageSourcePropType>>={groceries:promotionalBannerAssets.groceries.primary,fashion:promotionalBannerAssets.fashion.primary,beauty:promotionalBannerAssets.beauty.primary,electronics:promotionalBannerAssets.electronics.primary,pharmacy:promotionalBannerAssets.pharmacy.wellnessApproved};
  const campaigns:PromotionCampaign[] = [
    {id:`${config.id}-hero`,cmsSlot:`${config.id.toUpperCase()}_HERO`,slot:'hero',service,country,city,campaign:`${config.id}-landing`,headline:config.heroHeadline,body:config.heroBody,image:approvedHero[config.id]??art[0],imageOnly:Boolean(approvedHero[config.id]),backgroundTreatment:'yellow',creativeType:'CATEGORY_CAMPAIGN',ctaLabel:config.categories[0]?`Shop ${config.categories[0].label}`:`Browse ${config.title}`,ctaScreen:'categoryItems',priority:100,sessionCap:2,enabled:true,referenceFixture:true,partnerStatus:'not-required'},
    {id:`${config.id}-promo-02`,cmsSlot:`${config.id.toUpperCase()}_PROMO_02`,slot:'secondary',service,country,city,campaign:`${config.id}-discovery`,headline:`Explore ${config.title}`,body:`Browse configured ${config.title.toLowerCase()} sellers and everyday essentials.`,image:art[1],backgroundTreatment:'cream',creativeType:'CATEGORY_CAMPAIGN',ctaLabel:'Browse sellers',ctaScreen:'allStores',priority:90,sessionCap:1,enabled:true,referenceFixture:true,partnerStatus:'not-required'},
    {id:`${config.id}-promo-03`,cmsSlot:`${config.id.toUpperCase()}_PROMO_03`,slot:'contextual',service,country,city,campaign:`${config.id}-discovery`,headline:`More ways to shop ${config.title.toLowerCase()}`,body:'Browse related categories and compare sellers without losing your place.',image:art[2],backgroundTreatment:'yellow',creativeType:'CATEGORY_CAMPAIGN',ctaLabel:'Browse all',ctaScreen:'categoryItems',priority:80,sessionCap:1,enabled:true,referenceFixture:true,partnerStatus:'not-required'},
  ];
  if(config.id==='groceries') campaigns.splice(1,2,{...campaigns[1]!,image:promotionalBannerAssets.groceries.secondary,imageOnly:true},{...campaigns[2]!,image:promotionalBannerAssets.groceries.tertiary,imageOnly:true});
  if(config.id==='pharmacy') campaigns.splice(1,2,{...campaigns[1]!,image:promotionalBannerAssets.pharmacy.secondary,imageOnly:true});
  if(config.id==='fashion') campaigns.splice(1,2,{...campaigns[2]!,image:promotionalBannerAssets.beauty.primary,imageOnly:true,ctaScreen:'beautyHome'});
  if(config.id==='beauty'||config.id==='electronics') campaigns.splice(1);
  return campaigns;
}
