import React, { useMemo, useState } from 'react';
import { Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import { Feather, Ionicons, MaterialCommunityIcons } from '@expo/vector-icons';
import { Header, PrimaryButton, RoundedCard, ScreenShell, SectionTitle } from '../components';
import { formatMoney } from '../locale';
import { COLORS, FONT, TYPE } from '../theme';
import type { RentalBooking } from '../parity/types';

export type RentalVehicle = { id:string; name:string; category:string; seats:number; transmission:string; daily:number; rating:number; provider:string; icon:string; deposit:number };
export const RENTAL_VEHICLES: RentalVehicle[] = [
  {id:'rav4',name:'Toyota RAV4',category:'SUV',seats:5,transmission:'Automatic',daily:180000,rating:4.9,provider:'Kampala Drive',icon:'car-suv',deposit:200000},
  {id:'premio',name:'Toyota Premio',category:'Comfort',seats:5,transmission:'Automatic',daily:140000,rating:4.8,provider:'City Cars',icon:'car',deposit:150000},
  {id:'hiace',name:'Toyota Hiace',category:'Van',seats:12,transmission:'Manual',daily:280000,rating:4.7,provider:'Group Travel UG',icon:'van-passenger',deposit:300000},
  {id:'landcruiser',name:'Land Cruiser Prado',category:'Premium SUV',seats:7,transmission:'Automatic',daily:420000,rating:4.9,provider:'Safari Fleet',icon:'car-suv',deposit:500000},
];

export type RentalData={country:string;city:string;selectedVehicleId:string;booking:RentalBooking|null};
export type RentalActions={go:(screen:any)=>void;selectVehicle:(id:string)=>void;placeBooking:(booking:RentalBooking)=>void};
function vehicleFor(id:string){return RENTAL_VEHICLES.find(v=>v.id===id)??RENTAL_VEHICLES[0]!}

export function RentalsScreen({data,actions}:{data:RentalData;actions:RentalActions}){
  const [category,setCategory]=useState('All');
  const categories=['All','SUV','Comfort','Van','Premium SUV'];
  const vehicles=RENTAL_VEHICLES.filter(v=>category==='All'||v.category===category);
  return <ScreenShell><Header title="Vehicle rental" onBack={()=>actions.go('services')}/><ScrollView style={styles.flex} contentContainerStyle={styles.scroll}><Text style={styles.title}>Drive your way</Text><Text style={styles.subtitle}>Book cars and vans from verified rental partners in {data.city}.</Text><ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={styles.chips}>{categories.map(c=><Pressable key={c} onPress={()=>setCategory(c)} style={[styles.chip,category===c&&styles.chipActive]}><Text style={[styles.chipText,category===c&&styles.chipTextActive]}>{c}</Text></Pressable>)}</ScrollView><View style={styles.list}>{vehicles.map(v=><Pressable key={v.id} onPress={()=>{actions.selectVehicle(v.id);actions.go('rentalVehicle')}} style={styles.vehicleCard}><View style={styles.vehicleVisual}><MaterialCommunityIcons name={v.icon as any} size={64} color={COLORS.black}/></View><View style={styles.vehicleBody}><View style={styles.row}><View style={styles.flex}><Text style={styles.vehicleName}>{v.name}</Text><Text style={styles.vehicleMeta}>{v.category} · {v.seats} seats · {v.transmission}</Text></View><Text style={styles.rating}>★ {v.rating}</Text></View><Text style={styles.provider}>{v.provider}</Text><View style={styles.priceRow}><Text style={styles.price}>{formatMoney(data.country,v.daily)}<Text style={styles.per}> / day</Text></Text><Feather name="chevron-right" size={22}/></View></View></Pressable>)}</View></ScrollView></ScreenShell>
}

export function RentalVehicleScreen({data,actions}:{data:RentalData;actions:RentalActions}){
  const v=vehicleFor(data.selectedVehicleId);
  return <ScreenShell><Header title="Vehicle details" onBack={()=>actions.go('rentals')}/><ScrollView style={styles.flex} contentContainerStyle={styles.scroll}><View style={styles.hero}><MaterialCommunityIcons name={v.icon as any} size={105} color={COLORS.black}/></View><View><Text style={styles.title}>{v.name}</Text><Text style={styles.subtitle}>{v.provider} · ★ {v.rating}</Text></View><View style={styles.specs}><Spec icon="people-outline" label={`${v.seats} seats`}/><Spec icon="settings-outline" label={v.transmission}/><Spec icon="shield-checkmark-outline" label="Verified"/></View><RoundedCard style={styles.info}><Text style={styles.infoTitle}>Included</Text><Text style={styles.infoText}>• Standard insurance</Text><Text style={styles.infoText}>• 24/7 roadside assistance</Text><Text style={styles.infoText}>• 150 km/day mileage allowance</Text><Text style={styles.infoText}>• Provider handover verification</Text></RoundedCard><RoundedCard style={styles.priceCard}><View><Text style={styles.infoTitle}>Daily rate</Text><Text style={styles.subtitle}>Deposit {formatMoney(data.country,v.deposit)}</Text></View><Text style={styles.bigPrice}>{formatMoney(data.country,v.daily)}</Text></RoundedCard><PrimaryButton label="Choose dates" onPress={()=>actions.go('rentalCheckout')}/></ScrollView></ScreenShell>
}
function Spec({icon,label}:{icon:string;label:string}){return <View style={styles.spec}><Ionicons name={icon as any} size={21}/><Text style={styles.specText}>{label}</Text></View>}

export function RentalCheckoutScreen({data,actions}:{data:RentalData;actions:RentalActions}){
  const v=vehicleFor(data.selectedVehicleId);const [days,setDays]=useState(2);const [pickup,setPickup]=useState('Tomorrow · 9:00 AM');const total=v.daily*days+v.deposit;const options=['Tomorrow · 9:00 AM','Tomorrow · 2:00 PM','Saturday · 9:00 AM'];
  return <ScreenShell><Header title="Rental checkout" onBack={()=>actions.go('rentalVehicle')}/><ScrollView style={styles.flex} contentContainerStyle={styles.scroll}><RoundedCard style={styles.summary}><MaterialCommunityIcons name={v.icon as any} size={48}/><View style={styles.flex}><Text style={styles.vehicleName}>{v.name}</Text><Text style={styles.vehicleMeta}>{v.provider}</Text></View></RoundedCard><SectionTitle title="Pickup"/><View style={styles.chips}>{options.map(o=><Pressable key={o} onPress={()=>setPickup(o)} style={[styles.chip,pickup===o&&styles.chipActive]}><Text style={[styles.chipText,pickup===o&&styles.chipTextActive]}>{o}</Text></Pressable>)}</View><SectionTitle title="Rental length"/><RoundedCard style={styles.days}><Pressable onPress={()=>setDays(Math.max(1,days-1))} style={styles.circle}><Feather name="minus" size={18}/></Pressable><View><Text style={styles.daysValue}>{days} day{days===1?'':'s'}</Text><Text style={styles.subtitle}>Return after {days*24} hours</Text></View><Pressable onPress={()=>setDays(Math.min(14,days+1))} style={styles.circle}><Feather name="plus" size={18}/></Pressable></RoundedCard><RoundedCard style={styles.info}><Summary label="Rental" value={formatMoney(data.country,v.daily*days)}/><Summary label="Refundable deposit" value={formatMoney(data.country,v.deposit)}/><View style={styles.divider}/><Summary label="Total due" value={formatMoney(data.country,total)} strong/></RoundedCard><PrimaryButton label={`Book vehicle · ${formatMoney(data.country,total)}`} onPress={()=>{actions.placeBooking({id:`R${Date.now().toString().slice(-6)}`,vehicleId:v.id,pickupDate:pickup,returnDate:`${days} day${days===1?'':'s'} later`,days,total,status:'confirmed'});actions.go('rentalTrip')}}/></ScrollView></ScreenShell>
}
function Summary({label,value,strong=false}:{label:string;value:string;strong?:boolean}){return <View style={styles.row}><Text style={strong?styles.summaryStrong:styles.summaryLabel}>{label}</Text><Text style={strong?styles.summaryStrong:styles.summaryValue}>{value}</Text></View>}

export function RentalTripScreen({data,actions}:{data:RentalData;actions:RentalActions}){const booking=data.booking;if(!booking)return <RentalsScreen data={data} actions={actions}/>;const v=vehicleFor(booking.vehicleId);return <ScreenShell><Header title="Your rental" onBack={()=>actions.go('orders')}/><ScrollView style={styles.flex} contentContainerStyle={styles.scroll}><View style={styles.statusIcon}><Ionicons name="checkmark" size={38}/></View><Text style={styles.title}>Booking confirmed</Text><Text style={styles.subtitle}>Booking #{booking.id} · {booking.pickupDate}</Text><RoundedCard style={styles.summary}><MaterialCommunityIcons name={v.icon as any} size={50}/><View style={styles.flex}><Text style={styles.vehicleName}>{v.name}</Text><Text style={styles.vehicleMeta}>{v.provider} · {booking.days} days</Text></View></RoundedCard><RoundedCard style={styles.info}><Summary label="Pickup" value={data.city}/><Summary label="Status" value="Ready for provider confirmation"/><Summary label="Total" value={formatMoney(data.country,booking.total)} strong/></RoundedCard><PrimaryButton label="Contact provider" onPress={()=>actions.go('messages')}/></ScrollView></ScreenShell>}

const styles=StyleSheet.create({flex:{flex:1},scroll:{paddingHorizontal:20,paddingTop:14,paddingBottom:34,gap:17},title:{fontFamily:FONT.bold,fontSize:28,fontWeight:'900'},subtitle:{...TYPE.body,color:COLORS.muted,lineHeight:21},chips:{gap:8,paddingRight:12},chip:{minHeight:38,borderWidth:1,borderColor:COLORS.line,borderRadius:19,paddingHorizontal:13,alignItems:'center',justifyContent:'center'},chipActive:{backgroundColor:COLORS.black,borderColor:COLORS.black},chipText:{...TYPE.small,fontWeight:'800'},chipTextActive:{color:COLORS.white},list:{gap:12},vehicleCard:{borderWidth:1,borderColor:COLORS.line,borderRadius:21,overflow:'hidden',backgroundColor:COLORS.white},vehicleVisual:{height:128,backgroundColor:'#F6F3EC',alignItems:'center',justifyContent:'center'},vehicleBody:{padding:14,gap:7},row:{flexDirection:'row',alignItems:'center',justifyContent:'space-between',gap:12},vehicleName:{...TYPE.sectionTitle},vehicleMeta:{...TYPE.small,color:COLORS.muted,marginTop:3},rating:{...TYPE.bodyStrong},provider:{...TYPE.small,color:COLORS.muted},priceRow:{flexDirection:'row',alignItems:'center',justifyContent:'space-between'},price:{fontFamily:FONT.bold,fontSize:18,fontWeight:'900'},per:{fontFamily:FONT.regular,fontSize:12,color:COLORS.muted,fontWeight:'400'},hero:{height:220,borderRadius:25,backgroundColor:'#F6F3EC',alignItems:'center',justifyContent:'center'},specs:{flexDirection:'row',gap:8},spec:{flex:1,minHeight:70,borderWidth:1,borderColor:COLORS.line,borderRadius:16,alignItems:'center',justifyContent:'center',gap:5},specText:{...TYPE.small,fontWeight:'700'},info:{padding:15,gap:8,shadowOpacity:0},infoTitle:{...TYPE.cardTitle},infoText:{...TYPE.body,color:COLORS.muted},priceCard:{padding:15,flexDirection:'row',alignItems:'center',justifyContent:'space-between',shadowOpacity:0},bigPrice:{fontFamily:FONT.bold,fontSize:21,fontWeight:'900'},summary:{padding:14,flexDirection:'row',alignItems:'center',gap:12,shadowOpacity:0},days:{padding:15,flexDirection:'row',alignItems:'center',justifyContent:'space-between',shadowOpacity:0},circle:{width:42,height:42,borderRadius:21,borderWidth:1,borderColor:COLORS.line,alignItems:'center',justifyContent:'center'},daysValue:{fontFamily:FONT.bold,fontSize:20,fontWeight:'900',textAlign:'center'},summaryLabel:{...TYPE.body,color:COLORS.muted},summaryValue:{...TYPE.bodyStrong},summaryStrong:{fontFamily:FONT.bold,fontSize:16,fontWeight:'900'},divider:{height:1,backgroundColor:COLORS.line,marginVertical:3},statusIcon:{width:78,height:78,borderRadius:39,backgroundColor:COLORS.yellow,alignItems:'center',justifyContent:'center',alignSelf:'center'}});
