import type { AppEnginePageDefinition, AppEngineSectionDefinition } from '../appEngine/types';
import type { DineOutMarketContent } from './types';

const section=(id:string,rendererKey:string,priority:number,title?:string,subtitle?:string):AppEngineSectionDefinition=>({id,type:'custom',rendererKey,layout:rendererKey==='DINEOUT_CATEGORIES'?'grid-4':'carousel',title,subtitle,priority,enabled:true});
const search=(content:DineOutMarketContent,placeholder:string)=>({scope:'dineout' as const,placeholder,market:content.country,city:content.city,enabled:true,suggestionsEnabled:true,recentSearchesEnabled:true});
export function dineOutHomePage(content:DineOutMarketContent):AppEnginePageDefinition{return{id:`dineout-${content.country.toLowerCase()}`,type:'service-landing',title:'DineOut',version:'1.0.0',header:{type:'service',title:'DineOut',showLocation:true,showSearch:true,search:search(content,'Search restaurants, cuisines and areas')},navigation:{showBottomNavigation:true,activeTab:'explore',backBehaviour:'history'},targeting:{countries:[content.country],cities:[content.city]},sections:[
  section('filters','DINEOUT_FILTERS',1000),section('plan-ahead','DINEOUT_PLAN_AHEAD',995),section('categories','DINEOUT_CATEGORIES',990,'Discover DineOut','Dining occasions for every plan'),section('featured','DINEOUT_FEATURED',970,'Your next favourite might be here'),section('promo','DINEOUT_PROMO',960),section('savings','DINEOUT_SAVINGS',950,'Feast more, pay less'),section('cuisines','DINEOUT_CUISINES',930,'What are you in the mood for?'),section('guides','DINEOUT_GUIDES',910,'Your guide to dining out'),section('more-savings','DINEOUT_MORE_SAVINGS',900,'More ways to save on dining'),section('brands','DINEOUT_BRANDS',880,'Popular Restaurants'),section('highlights','DINEOUT_HIGHLIGHTS',860,"Highlights you shouldn't miss"),section('areas','DINEOUT_AREA_GUIDE',840,'DineOut Area Guide','Find the best spots around the city'),section('all','DINEOUT_ALL_RESTAURANTS',800,'Explore all dining spots')],metadata:{service:'dineout',market:content.country,city:content.city}}}

export function dineOutCollectionPage(content:DineOutMarketContent,id:string,title:string,kind:string):AppEnginePageDefinition{const area=kind==='area';return{id:`dineout-${kind}-${id}-${content.country.toLowerCase()}`,type:'category-landing',title,version:'1.1.0',header:{type:'detail',title,showLocation:false,showSearch:true,search:search(content,area?`Search restaurants in ${title}`:`Search ${title} restaurants`)},navigation:{showBottomNavigation:false,backBehaviour:'history'},sections:[section('hero',area?'DINEOUT_AREA_HERO':'DINEOUT_CATEGORY_HERO',1000),section('filters','DINEOUT_FILTERS',980),section('featured',area?'DINEOUT_AREA_FEATURED':'DINEOUT_CATEGORY_FEATURED',940,'Featured restaurants'),section('intro','DINEOUT_COLLECTION_INTRO',925),section('promo','DINEOUT_CATEGORY_PROMO',900),...(area?[section('cuisines','DINEOUT_AREA_CUISINES',860,'Cuisines in this area')]:[section('brands','DINEOUT_CATEGORY_BRANDS',860,'Popular Restaurants')]),section('all',area?'DINEOUT_AREA_ALL':'DINEOUT_CATEGORY_ALL',800,`All ${title} restaurants`)],targeting:{countries:[content.country],cities:[content.city]},metadata:{service:'dineout',collection:id,collectionKind:kind}}}
