import React, { useState } from 'react';
import { Image, Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import { Feather, Ionicons } from '@expo/vector-icons';
import { useSafeAreaInsets } from 'react-native-safe-area-context';
import { KareebuPageHeader, PrimaryButton, ScreenShell, SectionTitle } from '../components';
import { COLORS, RADIUS, SPACE, TYPE } from '../theme';
import type { Screen } from '../types';
import { dineOutContent } from './content';
import { dineOutSession } from './session';

type Props={country:string;city:string;go:(screen:Screen)=>void};
export function DineOutReservationScreen({country,city,go}:Props){
  const content=dineOutContent(country,city); const restaurant=content.restaurants.find(item=>item.id===dineOutSession.read().restaurantId)??content.restaurants[0]!;
  const [date,setDate]=useState('Tonight'); const [time,setTime]=useState('7:30 PM'); const [guests,setGuests]=useState(2); const [reviewing,setReviewing]=useState(false); const insets=useSafeAreaInsets();
  const submit=()=>{dineOutSession.setReservationIntent({date,time,guests,status:'enquiry-sent'});go('dineOutConfirmation')};
  return <ScreenShell><KareebuPageHeader title={reviewing?'Review enquiry':'Plan your visit'} country={country} city={city} locationEnabled={false} searchEnabled={false} onBack={()=>reviewing?setReviewing(false):go('dineOutRestaurant')} variant="transaction"/><ScrollView contentContainerStyle={[styles.scroll,{paddingBottom:Math.max(insets.bottom,20)+32}]}><Image source={restaurant.hero.image} accessibilityLabel={restaurant.hero.alt} style={styles.hero}/><Text style={styles.name}>{restaurant.name}</Text><Text style={styles.meta}>{restaurant.area} · Reservation enquiry</Text>{reviewing?<><SectionTitle title="Your visit"/><Summary icon="calendar-outline" title={date} body={`${time} · ${guests} guest${guests===1?'':'s'}`}/><View style={styles.boundary}><Ionicons name="information-circle-outline" size={22}/><Text style={styles.boundaryText}>Sending this enquiry does not reserve a table. The restaurant or its reservation provider must confirm availability.</Text></View><PrimaryButton label="Send reservation enquiry" onPress={submit}/></>:<><SectionTitle title="Choose a date"/><ChoiceRail values={['Tonight','Tomorrow','This weekend']} selected={date} onSelect={setDate}/><SectionTitle title="Choose a time"/><ChoiceRail values={['6:30 PM','7:30 PM','8:30 PM']} selected={time} onSelect={setTime}/><SectionTitle title="Party size"/><View style={styles.stepper}><Pressable accessibilityRole="button" accessibilityLabel="Remove guest" onPress={()=>setGuests(value=>Math.max(1,value-1))} style={styles.step}><Feather name="minus" size={20}/></Pressable><Text accessibilityLabel={`${guests} guests`} style={styles.guests}>{guests} guests</Text><Pressable accessibilityRole="button" accessibilityLabel="Add guest" onPress={()=>setGuests(value=>Math.min(12,value+1))} style={styles.step}><Feather name="plus" size={20}/></Pressable></View><View style={styles.boundary}><Ionicons name="information-circle-outline" size={22}/><Text style={styles.boundaryText}>Table availability is not live. Kareebu will ask the restaurant to confirm your selected time.</Text></View><PrimaryButton label="Review enquiry" onPress={()=>setReviewing(true)}/></>}</ScrollView></ScreenShell>;
}
export function DineOutConfirmationScreen({country,city,go}:Props){const content=dineOutContent(country,city);const restaurant=content.restaurants.find(item=>item.id===dineOutSession.read().restaurantId)??content.restaurants[0]!;const intent=dineOutSession.read().reservationIntent;return <ScreenShell><KareebuPageHeader title="Enquiry sent" country={country} city={city} locationEnabled={false} searchEnabled={false} onBack={()=>go('dineOutRestaurant')} variant="transaction"/><View style={styles.confirm}><View style={styles.confirmIcon}><Ionicons name="time-outline" size={34}/></View><Text accessibilityRole="header" style={styles.confirmTitle}>Waiting for restaurant confirmation</Text><Text style={styles.confirmBody}>Your request to {restaurant.name} for {intent?.date.toLowerCase()??'your selected date'} at {intent?.time??'your selected time'} has been recorded for {intent?.guests??2} guests. No table is confirmed yet.</Text><Summary icon="restaurant-outline" title={restaurant.name} body={`${restaurant.area}, ${restaurant.city}`}/><PrimaryButton label="Back to restaurant" onPress={()=>go('dineOutRestaurant')}/><Pressable accessibilityRole="button" onPress={()=>go('dineOut')}><Text style={styles.link}>Explore more dining spots</Text></Pressable></View></ScreenShell>}
function ChoiceRail({values,selected,onSelect}:{values:string[];selected:string;onSelect:(value:string)=>void}){return <ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={styles.choices}>{values.map(value=><Pressable accessibilityRole="button" accessibilityState={{selected:value===selected}} key={value} onPress={()=>onSelect(value)} style={[styles.choice,value===selected&&styles.choiceActive]}><Text style={styles.choiceText}>{value}</Text></Pressable>)}</ScrollView>}
function Summary({icon,title,body}:{icon:keyof typeof Ionicons.glyphMap;title:string;body:string}){return <View style={styles.summary}><Ionicons name={icon} size={23}/><View><Text style={styles.summaryTitle}>{title}</Text><Text style={styles.meta}>{body}</Text></View></View>}
const styles=StyleSheet.create({scroll:{padding:SPACE.lg,gap:12},hero:{height:190,width:'100%',borderRadius:24},name:{...TYPE.screenTitle},meta:{...TYPE.small,color:COLORS.muted,marginTop:3},choices:{gap:9,paddingRight:20},choice:{height:42,borderRadius:21,borderWidth:1,borderColor:COLORS.line,paddingHorizontal:15,alignItems:'center',justifyContent:'center'},choiceActive:{backgroundColor:COLORS.yellow,borderColor:COLORS.yellowDeep},choiceText:{...TYPE.small,fontWeight:'800'},stepper:{height:56,borderRadius:RADIUS.lg,backgroundColor:COLORS.surfaceStrong,flexDirection:'row',alignItems:'center',justifyContent:'space-between',paddingHorizontal:10},step:{width:42,height:42,borderRadius:14,backgroundColor:COLORS.white,alignItems:'center',justifyContent:'center'},guests:{...TYPE.bodyStrong},boundary:{flexDirection:'row',gap:10,padding:14,borderRadius:RADIUS.lg,backgroundColor:COLORS.yellowWash},boundaryText:{...TYPE.small,flex:1,lineHeight:19},summary:{flexDirection:'row',alignItems:'center',gap:12,padding:15,borderRadius:RADIUS.lg,backgroundColor:COLORS.surfaceStrong},summaryTitle:{...TYPE.cardTitle},confirm:{flex:1,padding:SPACE.xl,alignItems:'center',justifyContent:'center',gap:16},confirmIcon:{width:72,height:72,borderRadius:24,backgroundColor:COLORS.yellow,alignItems:'center',justifyContent:'center'},confirmTitle:{...TYPE.screenTitle,textAlign:'center'},confirmBody:{...TYPE.body,color:COLORS.muted,textAlign:'center',lineHeight:22},link:{...TYPE.action,textAlign:'center',padding:12}});
