import type { PromotionCampaign, PromotionContext, PromotionSlot } from './types';
import { PROMOTION_CREATIVE } from './creativeRegistry';
import { promotionalBannerAssets } from './promotionalBannerAssets';

export const DEMO_PROMOTION_CATALOG: PromotionCampaign[] = [
  {id:'home-everything',slot:'hero',service:'home',campaign:'everything-nearby',headline:'Everything you need, closer.',body:'Rides, meals, essentials and everyday help around your city.',badge:'Kareebu+',image:PROMOTION_CREATIVE.shops.asset,backgroundTreatment:'yellow',ctaLabel:'Explore Kareebu+',ctaScreen:'exploreHub',priority:100,enabled:true},
  {id:'home-food-local',slot:'hero',service:'home',campaign:'local-favourites',headline:'Local food discovery.',body:'Browse configured restaurant menus and food collections for your city.',badge:'FOOD',image:PROMOTION_CREATIVE.foodWeekend.asset,backgroundTreatment:'photo',ctaLabel:'Explore food',ctaScreen:'food',priority:90,enabled:true},
  {id:'home-move-city',slot:'hero',service:'home',campaign:'move-your-way',headline:'Move across town your way.',body:'Choose a car or boda, with clear pickup and safety tools.',badge:'RIDES & BODA',image:PROMOTION_CREATIVE.boda.asset,backgroundTreatment:'cream',ctaLabel:'Plan a trip',ctaScreen:'mobilityHome',priority:80,enabled:true},
  {id:'home-rewards',slot:'secondary',service:'home',campaign:'rewards-value',headline:'Make every order count',body:'See rewards, savings and Kareebu+ benefits in one place.',image:require('../../assets/kareebu-plus/quick-actions/wallet.png'),backgroundTreatment:'cream',ctaLabel:'View rewards',ctaScreen:'rewards',priority:80,enabled:true},
  {id:'home-plus',slot:'membership',service:'home',campaign:'plus-benefits',headline:'More value with Kareebu+',body:'Discover delivery and ride benefits available to members.',badge:'MEMBERSHIP',image:require('../../assets/kareebu-plus/kareebu-plus-mark.png'),backgroundTreatment:'charcoal',ctaLabel:'Explore benefits',ctaScreen:'plusManage',priority:70,enabled:true},
  {id:'rides-airport',slot:'hero',cmsSlot:'RIDES_AIRPORT',service:'rides',campaign:'airport-rides',headline:'Airport plans, sorted.',body:'Set your destination now or schedule pickup for later.',badge:'RIDES',image:require('../../assets/kareebu-plus/rides-home/kareebu-car.png'),backgroundTreatment:'yellow',ctaLabel:'Plan airport ride',ctaScreen:'whereTo',priority:100,enabled:true},
  {id:'rides-uganda-city',slot:'hero',cmsSlot:'RIDES_HERO',service:'rides',country:'Uganda',city:'Kampala',campaign:'kampala-by-car',headline:'Ride across Kampala',body:'Choose a car for everyday journeys, airport plans or a scheduled pickup.',badge:'KAMPALA',image:require('../../assets/kareebu-plus/rides-home/kareebu-car.png'),backgroundTreatment:'photo',ctaLabel:'Find a car',ctaScreen:'whereTo',priority:140,enabled:true,creative:{assetType:'bundled',width:1200,height:545,aspectRatio:2.2,market:'Uganda',service:'rides',source:'kareebu-owned',rightsStatus:'cleared'}},
  {id:'rides-kenya-city',slot:'hero',cmsSlot:'RIDES_HERO',service:'rides',country:'Kenya',city:'Nairobi',campaign:'nairobi-by-car',headline:'Your Nairobi ride, planned',body:'Cars for city journeys, scheduled pickups and airport travel.',badge:'NAIROBI',image:require('../../assets/kareebu-plus/rides-home/kareebu-car.png'),backgroundTreatment:'photo',ctaLabel:'Find a car',ctaScreen:'whereTo',priority:140,enabled:true,creative:{assetType:'bundled',width:1200,height:545,aspectRatio:2.2,market:'Kenya',service:'rides',source:'kareebu-owned',rightsStatus:'cleared'}},
  {id:'rides-tanzania-city',slot:'hero',cmsSlot:'RIDES_HERO',service:'rides',country:'Tanzania',city:'Dar es Salaam',campaign:'dar-by-car',headline:'Move across Dar with ease',body:'Choose a car for city journeys, airport plans or later pickups.',badge:'DAR ES SALAAM',image:require('../../assets/kareebu-plus/rides-home/kareebu-car.png'),backgroundTreatment:'photo',ctaLabel:'Find a car',ctaScreen:'whereTo',priority:140,enabled:true,creative:{assetType:'bundled',width:1200,height:545,aspectRatio:2.2,market:'Tanzania',service:'rides',source:'kareebu-owned',rightsStatus:'cleared'}},
  {id:'rides-night',slot:'contextual',cmsSlot:'RIDES_PROMO_02',service:'rides',campaign:'city-rides',headline:'Kareebu city rides',body:'Continue to Ride booking.',image:promotionalBannerAssets.ride.secondary,imageOnly:true,backgroundTreatment:'photo',ctaLabel:'Book a ride',ctaScreen:'whereTo',priority:70,enabled:true},
  {id:'boda-fast',slot:'hero',cmsSlot:'BODA_PROMO_02',service:'boda',campaign:'through-traffic',headline:'Boda rides around the city',body:'Continue to Boda booking.',image:promotionalBannerAssets.boda.secondary,imageOnly:true,backgroundTreatment:'photo',ctaLabel:'Choose destination',ctaScreen:'whereTo',priority:100,enabled:true},
  {id:'boda-uganda-traffic',slot:'hero',cmsSlot:'BODA_HERO',service:'boda',country:'Uganda',city:'Kampala',campaign:'kampala-traffic',headline:'Beat Kampala traffic',body:'A distinct motorcycle journey with clear pickup details and Boda safety tools.',badge:'BODA KAMPALA',image:PROMOTION_CREATIVE.boda.asset,backgroundTreatment:'yellow',ctaLabel:'Choose Boda',ctaScreen:'whereTo',priority:140,enabled:true,creative:{assetType:'bundled',width:1200,height:545,aspectRatio:2.2,market:'Uganda',service:'boda',source:'kareebu-owned',rightsStatus:'cleared'}},
  {id:'boda-kenya-traffic',slot:'hero',cmsSlot:'BODA_HERO',service:'boda',country:'Kenya',city:'Nairobi',campaign:'nairobi-traffic',headline:'Your quick ride across Nairobi',body:'Motorcycle pickup, value-focused estimates and Boda-specific safety details.',badge:'BODA NAIROBI',image:PROMOTION_CREATIVE.boda.asset,backgroundTreatment:'yellow',ctaLabel:'Choose Boda',ctaScreen:'whereTo',priority:140,enabled:true,creative:{assetType:'bundled',width:1200,height:545,aspectRatio:2.2,market:'Kenya',service:'boda',source:'kareebu-owned',rightsStatus:'cleared'}},
  {id:'boda-tanzania-traffic',slot:'hero',cmsSlot:'BODA_HERO',service:'boda',country:'Tanzania',city:'Dar es Salaam',campaign:'dar-traffic',headline:'Boda around Dar',body:'A motorcycle-first journey with separate estimates, riders and safety context.',badge:'BODA DAR',image:PROMOTION_CREATIVE.boda.asset,backgroundTreatment:'yellow',ctaLabel:'Choose Boda',ctaScreen:'whereTo',priority:140,enabled:true,creative:{assetType:'bundled',width:1200,height:545,aspectRatio:2.2,market:'Tanzania',service:'boda',source:'kareebu-owned',rightsStatus:'cleared'}},
  {id:'food-lunch',slot:'hero',cmsSlot:'FOOD_HERO',service:'food',campaign:'lunch-discovery',headline:'What are you craving?',body:'Explore food and restaurant discovery.',image:promotionalBannerAssets.food.primary,imageOnly:true,backgroundTreatment:'photo',ctaLabel:'Find food',ctaScreen:'foodSearch',priority:100,enabled:true},
  {id:'food-local',slot:'secondary',cmsSlot:'FOOD_PROMO_02',service:'food',campaign:'local-favourites',headline:'Explore food offers',body:'Explore restaurants and dishes around your city.',image:promotionalBannerAssets.food.secondary,imageOnly:true,backgroundTreatment:'photo',ctaLabel:'Explore food',ctaScreen:'food',priority:90,enabled:true},
  {id:'food-discovery',slot:'contextual',cmsSlot:'FOOD_PROMO_03',service:'food',campaign:'restaurant-discovery',headline:'Food delivered with Kareebu',body:'Browse cuisines and restaurants.',image:promotionalBannerAssets.food.tertiary,imageOnly:true,backgroundTreatment:'photo',ctaLabel:'Browse restaurants',ctaScreen:'foodSearch',priority:80,enabled:true},
  {id:'food-nearby',slot:'secondary',cmsSlot:'FOOD_PROMO_04',service:'food',campaign:'restaurant-discovery',headline:'Explore more restaurants',body:'Browse configured restaurant menus and confirm fulfilment details before checkout.',image:require('../../assets/karibu/food/cafe-javas.png'),backgroundTreatment:'photo',ctaLabel:'Browse restaurants',ctaScreen:'foodSearch',priority:70,enabled:false},
  {id:'food-plus',slot:'membership',cmsSlot:'FOOD_PLUS',service:'food',campaign:'plus-delivery',headline:'Kareebu+ food benefits',body:'See configured member delivery benefits before checkout.',image:require('../../assets/kareebu-plus/kareebu-plus-mark.png'),backgroundTreatment:'charcoal',ctaLabel:'See benefits',ctaScreen:'plusManage',priority:70,enabled:true},
  {id:'grocery-weekly',slot:'hero',service:'groceries',campaign:'weekly-shop',headline:'The weekly shop, simplified',body:'Browse groceries and household essentials.',image:promotionalBannerAssets.groceries.primary,imageOnly:true,backgroundTreatment:'photo',ctaLabel:'Shop essentials',ctaScreen:'groceryList',priority:100,enabled:true},
  {id:'pharmacy-wellness',slot:'hero',service:'pharmacy',campaign:'wellness-essentials',headline:'Wellness, when you need it',body:'Medicines, health essentials and trusted pharmacies in one place.',image:promotionalBannerAssets.pharmacy.wellnessApproved,imageOnly:true,backgroundTreatment:'photo',ctaLabel:'Shop medicines & wellness',ctaScreen:'pharmacyHome',priority:100,enabled:true},
  {id:'shops-trending',slot:'hero',service:'shops',campaign:'trending-nearby',headline:'Fresh finds from local shops',body:'Explore marketplace discovery.',image:promotionalBannerAssets.marketplace.primary,imageOnly:true,backgroundTreatment:'photo',ctaLabel:'Browse shops',ctaScreen:'allStores',priority:100,enabled:true},
  {id:'home-global-launch',slot:'secondary',placement:'HOME_PROMO',service:'home',campaign:'global-launch',headline:'The world is now on Kareebu',body:'Explore international sources with a landed estimate in your local currency.',badge:'GLOBAL',image:require('../../assets/kareebu-plus/global/products/headphones.png'),backgroundTreatment:'yellow',ctaLabel:'Explore Global',ctaScreen:'globalHome',priority:75,frequencyCap:2,enabled:true},
  {id:'shops-global-fallback',slot:'contextual',placement:'SHOP_CATEGORY_PROMO',service:'shops',campaign:'global-local-fallback',headline:'Can’t find it locally?',body:'Continue the same search across supported international sources.',badge:'GLOBAL',image:require('../../assets/kareebu-plus/global/products/trainers.png'),backgroundTreatment:'cream',ctaLabel:'Search Global',ctaScreen:'globalHome',priority:75,frequencyCap:2,enabled:true},
  {id:'global-world-delivered',slot:'hero',placement:'GLOBAL_HERO',service:'global',campaign:'world-delivered',headline:'The world, delivered.',body:'Shop international sources and review one local-currency delivered estimate.',badge:'KAREEBU GLOBAL',image:PROMOTION_CREATIVE.globalHero.asset,backgroundTreatment:'yellow',ctaLabel:'Explore products',ctaScreen:'globalHome',priority:100,frequencyCap:3,enabled:true},
  {id:'global-fashion',slot:'secondary',placement:'GLOBAL_CATEGORY_PROMO',service:'global',campaign:'global-fashion',headline:'Global fashion. One local estimate.',body:'Source price, delivery, duties and Kareebu logistics shown before payment.',image:require('../../assets/kareebu-plus/global/products/trainers.png'),backgroundTreatment:'photo',ctaLabel:'Shop fashion',ctaScreen:'globalCollection',priority:85,frequencyCap:2,enabled:true},
  {id:'dine-tonight',slot:'hero',placement:'DINEOUT_HERO',service:'dineout',campaign:'kampala-flavours',headline:"Kampala's flavours",body:'Discover restaurants and dining across Kampala.',image:promotionalBannerAssets.website.dineout,imageOnly:true,backgroundTreatment:'photo',ctaLabel:'Explore DineOut',ctaScreen:'dineOut',priority:100,enabled:true},
  {id:'send-sameday',slot:'hero',service:'send',campaign:'same-day',headline:'Delivery across town',body:'Start a Kareebu delivery.',image:promotionalBannerAssets.send.primary,imageOnly:true,backgroundTreatment:'photo',ctaLabel:'Start a delivery',ctaScreen:'parcel',priority:100,enabled:true},
  {id:'services-help',slot:'hero',service:'services',campaign:'home-help',headline:'Trusted help at home',body:'Browse home and care services.',image:promotionalBannerAssets.homeCare.primary,imageOnly:true,backgroundTreatment:'photo',ctaLabel:'Choose a service',ctaScreen:'serviceMarketplace',priority:100,enabled:true},
  {id:'pay-wallet',slot:'hero',service:'pay',campaign:'payment-control',headline:'Pay securely across Kareebu',body:'Choose a supported payment method, pay bills and keep your receipts in one protected place.',image:require('../../assets/kareebu-plus/quick-actions/wallet.png'),backgroundTreatment:'yellow',ctaLabel:'Manage payments',ctaScreen:'paymentMethods',priority:100,enabled:true},

  {id:'home-global-feature',slot:'secondary',placement:'HOME_GLOBAL',service:'home',campaign:'global-discovery',headline:'Shop the world with Kareebu Global',body:'International products with a clear landed estimate in your local currency.',badge:'GLOBAL',image:PROMOTION_CREATIVE.globalHero.asset,backgroundTreatment:'yellow',creativeType:'MARKETPLACE_CAMPAIGN',ctaLabel:'Explore Global',ctaScreen:'globalHome',priority:92,sessionCap:1,cooldownHours:4,enabled:true,referenceFixture:true,partnerStatus:'not-required'},
  {id:'home-shops-feature',slot:'contextual',placement:'HOME_SHOPS',service:'home',campaign:'shops-discovery',headline:'Shops worth exploring today',body:'Browse configured grocery, pharmacy, electronics and beauty sellers.',badge:'SHOPS',image:PROMOTION_CREATIVE.shops.asset,backgroundTreatment:'cream',creativeType:'SERVICE_CAMPAIGN',ctaLabel:'Explore shops',ctaScreen:'shops',priority:88,sessionCap:1,enabled:true,referenceFixture:true,partnerStatus:'not-required'},
  {id:'home-food-weekend',slot:'contextual',placement:'HOME_FOOD',service:'home',campaign:'weekend-food',headline:'What are you eating today?',body:'Explore configured restaurants, menus and food collections.',badge:'FOOD',image:PROMOTION_CREATIVE.foodWeekend.asset,backgroundTreatment:'photo',creativeType:'PHOTOGRAPHIC_HERO',ctaLabel:'Find food',ctaScreen:'food',priority:86,sessionCap:1,enabled:true,referenceFixture:true,partnerStatus:'not-required'},

  {id:'grocery-fresh',slot:'secondary',placement:'GROCERY_FRESH',service:'groceries',campaign:'fresh-food',headline:'Fresh food for the week ahead',body:'Browse produce, meat, dairy and bakery from configured grocery sellers.',badge:'FRESH',image:PROMOTION_CREATIVE.groceryFresh.asset,backgroundTreatment:'green',creativeType:'CATEGORY_CAMPAIGN',ctaLabel:'Browse fresh food',ctaScreen:'verticalCategory',priority:92,sessionCap:2,enabled:true,referenceFixture:true,partnerStatus:'not-required'},
  {id:'grocery-household',slot:'contextual',placement:'GROCERY_HOUSEHOLD',service:'groceries',campaign:'home-essentials',headline:'Keep the household topped up',body:'Cleaning, cooking and everyday home essentials in one shop.',image:PROMOTION_CREATIVE.groceryHousehold.asset,backgroundTreatment:'cream',creativeType:'CATEGORY_CAMPAIGN',ctaLabel:'Shop household',ctaScreen:'verticalCategory',priority:82,sessionCap:1,enabled:true,referenceFixture:true,partnerStatus:'not-required'},
  {id:'grocery-personal',slot:'contextual',placement:'GROCERY_PERSONAL_CARE',service:'groceries',campaign:'personal-care',headline:'Everyday personal care',body:'Personal-care and family essentials from configured grocery sellers.',image:PROMOTION_CREATIVE.personalCare.asset,backgroundTreatment:'rose',creativeType:'CATEGORY_CAMPAIGN',ctaLabel:'Browse personal care',ctaScreen:'verticalCategory',priority:78,sessionCap:1,enabled:true,referenceFixture:true,partnerStatus:'not-required'},

  {id:'pharmacy-vitamins',slot:'secondary',placement:'PHARMACY_VITAMINS',service:'pharmacy',campaign:'vitamins-wellness',headline:'Everyday wellness, clearly organised',body:'Browse vitamins and supplements by need. Product suitability remains a customer/pharmacy decision.',badge:'WELLNESS',image:PROMOTION_CREATIVE.vitamins.asset,backgroundTreatment:'cream',creativeType:'CATEGORY_CAMPAIGN',ctaLabel:'Browse vitamins',ctaScreen:'verticalCategory',priority:90,sessionCap:2,enabled:true,referenceFixture:true,partnerStatus:'not-required'},
  {id:'pharmacy-first-aid',slot:'contextual',placement:'PHARMACY_FIRST_AID',service:'pharmacy',campaign:'first-aid',headline:'Home first-aid essentials',body:'Browse everyday first-aid supplies from pharmacies in your market.',image:PROMOTION_CREATIVE.pharmacy.asset,backgroundTreatment:'yellow',creativeType:'CATEGORY_CAMPAIGN',ctaLabel:'Browse first aid',ctaScreen:'verticalCategory',priority:80,sessionCap:1,enabled:true,referenceFixture:true,partnerStatus:'not-required'},

  {id:'shops-tech',slot:'secondary',placement:'SHOP_INLINE',service:'shops',campaign:'tech-everyday',headline:'Tech for everyday life',body:'Phones, accessories, computers and home electronics from specialist sellers.',badge:'ELECTRONICS',image:PROMOTION_CREATIVE.electronics.asset,backgroundTreatment:'blue',creativeType:'CATEGORY_CAMPAIGN',ctaLabel:'Explore electronics',ctaScreen:'electronicsHome',priority:93,sessionCap:2,enabled:true,referenceFixture:true,partnerStatus:'not-required'},
  {id:'shops-beauty',slot:'contextual',placement:'SHOP_INLINE',service:'shops',campaign:'beauty-care',headline:'Beauty & self care',body:'Skincare, grooming and personal-care products from beauty and pharmacy sellers.',badge:'BEAUTY',image:PROMOTION_CREATIVE.beauty.asset,backgroundTreatment:'rose',creativeType:'PRODUCT_CAMPAIGN',ctaLabel:'Explore beauty',ctaScreen:'beautyHome',priority:89,sessionCap:2,enabled:true,referenceFixture:true,partnerStatus:'not-required'},
  {id:'shops-home',slot:'contextual',placement:'SHOP_INLINE',service:'shops',campaign:'home-refresh',headline:'Refresh your home',body:'Storage, cleaning, kitchen and household picks from nearby sellers.',image:PROMOTION_CREATIVE.home.asset,backgroundTreatment:'cream',creativeType:'PRODUCT_CAMPAIGN',ctaLabel:'Explore home',ctaScreen:'homeShoppingHome',priority:84,sessionCap:1,enabled:true,referenceFixture:true,partnerStatus:'not-required'},

  {id:'rides-event',slot:'contextual',placement:'RIDES_EVENT',service:'rides',campaign:'ride-to-events',headline:'Going somewhere worth showing up for?',body:'Choose a destination and Kareebu will prefill the ride journey for you.',badge:'RIDE THERE',image:PROMOTION_CREATIVE.rides.asset,backgroundTreatment:'cream',creativeType:'EVENT_CAMPAIGN',ctaLabel:'Choose destination',ctaScreen:'whereTo',priority:88,sessionCap:1,enabled:true,referenceFixture:true,partnerStatus:'not-required'},
  {id:'rides-schedule',slot:'contextual',placement:'RIDES_INLINE',service:'rides',campaign:'schedule-ahead',headline:'Plan the ride before the rush',body:'Schedule a pickup when your market and ride product support it.',image:PROMOTION_CREATIVE.rideSchedule.asset,backgroundTreatment:'yellow',creativeType:'SERVICE_CAMPAIGN',ctaLabel:'Schedule ride',ctaScreen:'rideSchedule',priority:85,sessionCap:1,enabled:true,referenceFixture:true,partnerStatus:'not-required'},
  {id:'boda-commute',slot:'contextual',placement:'BODA_INLINE',service:'boda',campaign:'city-commute',headline:'A simpler move through city traffic',body:'Motorcycle-only booking with Boda-specific rider, safety and pickup details.',image:PROMOTION_CREATIVE.boda.asset,backgroundTreatment:'yellow',creativeType:'SERVICE_CAMPAIGN',ctaLabel:'Book a Boda',ctaScreen:'whereTo',priority:88,sessionCap:1,enabled:true,referenceFixture:true,partnerStatus:'not-required'},

  {id:'dine-brunch',slot:'secondary',placement:'DINEOUT_BRUNCH',service:'dineout',campaign:'brunch-guide',headline:'Make a morning of it',body:'Explore brunch spots, relaxed cafés and weekend dining collections.',badge:'BRUNCH',image:PROMOTION_CREATIVE.dineoutBrunch.asset,backgroundTreatment:'photo',creativeType:'PHOTOGRAPHIC_HERO',ctaLabel:'Explore brunch',ctaScreen:'dineOutCollection',priority:92,sessionCap:1,enabled:true,referenceFixture:true,partnerStatus:'not-required'},
  {id:'dine-weekend',slot:'contextual',placement:'DINEOUT_WEEKEND',service:'dineout',campaign:'weekend-dining',headline:'Make the weekend a DineOut weekend',body:'Discover restaurant guides and places worth planning around.',image:promotionalBannerAssets.dineout.weekendApproved,imageOnly:true,backgroundTreatment:'photo',creativeType:'EDITORIAL_CAMPAIGN',ctaLabel:'Explore DineOut',ctaScreen:'dineOut',priority:88,sessionCap:1,enabled:true,referenceFixture:true,partnerStatus:'not-required'},

  {id:'goout-weekend',slot:'hero',placement:'GOOUT_HERO',service:'goout',campaign:'weekend-out',headline:'Make more of the weekend',body:'Explore activities, experiences, wellness and places to go in your city.',badge:'GO OUT',image:PROMOTION_CREATIVE.goout.asset,backgroundTreatment:'yellow',creativeType:'SERVICE_CAMPAIGN',ctaLabel:'Explore things to do',ctaScreen:'exploreHub',priority:100,sessionCap:2,enabled:true,referenceFixture:true,partnerStatus:'not-required'},
  {id:'goout-wellness',slot:'secondary',placement:'GOOUT_WELLNESS',service:'goout',campaign:'wellness-out',headline:'Take some time for yourself',body:'Browse spa, wellness and relaxation experiences in your city.',image:PROMOTION_CREATIVE.wellness.asset,backgroundTreatment:'cream',creativeType:'CATEGORY_CAMPAIGN',ctaLabel:'Explore wellness',ctaScreen:'exploreHub',priority:90,sessionCap:1,enabled:true,referenceFixture:true,partnerStatus:'not-required'},
  {id:'goout-family',slot:'contextual',placement:'GOOUT_FAMILY',service:'goout',campaign:'family-day-out',headline:'Plan a family day out',body:'Activities and places for shared time together.',image:PROMOTION_CREATIVE.activities.asset,backgroundTreatment:'yellow',creativeType:'CATEGORY_CAMPAIGN',ctaLabel:'Find activities',ctaScreen:'exploreHub',priority:84,sessionCap:1,enabled:true,referenceFixture:true,partnerStatus:'not-required'},

  {id:'global-tech',slot:'secondary',placement:'GLOBAL_TECH',service:'global',campaign:'global-tech',headline:'Tech from around the world',body:'Phones, computers, audio and accessories with a local-currency landed estimate.',badge:'GLOBAL TECH',image:PROMOTION_CREATIVE.electronics.asset,backgroundTreatment:'blue',creativeType:'MARKETPLACE_CAMPAIGN',ctaLabel:'Explore tech',ctaScreen:'globalCollection',priority:94,sessionCap:2,enabled:true,referenceFixture:true,partnerStatus:'unknown'},
  {id:'global-beauty',slot:'contextual',placement:'GLOBAL_BEAUTY',service:'global',campaign:'global-beauty',headline:'Beauty from around the world',body:'Skincare, beauty and personal-care picks from supported international sources.',image:PROMOTION_CREATIVE.beauty.asset,backgroundTreatment:'rose',creativeType:'PRODUCT_CAMPAIGN',ctaLabel:'Explore beauty',ctaScreen:'globalCollection',priority:90,sessionCap:1,enabled:true,referenceFixture:true,partnerStatus:'unknown'},
  {id:'global-home',slot:'contextual',placement:'GLOBAL_HOME',service:'global',campaign:'global-home',headline:'Upgrade your home globally',body:'Storage, kitchen and useful home finds with one estimated delivered total.',image:PROMOTION_CREATIVE.home.asset,backgroundTreatment:'cream',creativeType:'PRODUCT_CAMPAIGN',ctaLabel:'Explore home',ctaScreen:'globalCollection',priority:86,sessionCap:1,enabled:true,referenceFixture:true,partnerStatus:'unknown'},
  {id:'global-school',slot:'contextual',placement:'GLOBAL_SCHOOL',service:'global',campaign:'global-school',headline:'Office & school essentials',body:'Study, stationery and workspace picks from international sources.',image:PROMOTION_CREATIVE.globalSchool.asset,backgroundTreatment:'green',creativeType:'CATEGORY_CAMPAIGN',ctaLabel:'Explore school & office',ctaScreen:'globalCollection',priority:84,sessionCap:1,enabled:true,referenceFixture:true,partnerStatus:'unknown'},

  {id:'category-shops-discovery',slot:'contextual',placement:'CATEGORY_INLINE',service:'shops',campaign:'category-discovery',headline:'More to discover in this category',body:'Compare sellers, products and related collections without losing your place.',image:PROMOTION_CREATIVE.shops.asset,backgroundTreatment:'cream',creativeType:'CATEGORY_CAMPAIGN',ctaLabel:'Explore more',ctaScreen:'shops',priority:72,sessionCap:1,enabled:true,referenceFixture:true,partnerStatus:'not-required'},
  {id:'category-grocery-discovery',slot:'contextual',placement:'CATEGORY_INLINE',service:'groceries',campaign:'grocery-category-discovery',headline:'Build the rest of your basket',body:'Explore related grocery categories and household essentials.',image:require('../../assets/kareebu-plus/lifestyle-cutouts/service-groceries.png'),backgroundTreatment:'green',creativeType:'CATEGORY_CAMPAIGN',ctaLabel:'Explore groceries',ctaScreen:'groceries',priority:72,sessionCap:1,enabled:true,referenceFixture:true,partnerStatus:'not-required'},
  {id:'category-pharmacy-discovery',slot:'contextual',placement:'CATEGORY_INLINE',service:'pharmacy',campaign:'pharmacy-category-discovery',headline:'Explore related wellness essentials',body:'Browse personal-care and wellness categories in one place.',image:PROMOTION_CREATIVE.pharmacy.asset,backgroundTreatment:'cream',creativeType:'CATEGORY_CAMPAIGN',ctaLabel:'Explore pharmacy',ctaScreen:'pharmacyHome',priority:72,sessionCap:1,enabled:true,referenceFixture:true,partnerStatus:'not-required'},
  {id:'category-food-discovery',slot:'contextual',placement:'CATEGORY_INLINE',service:'food',campaign:'food-category-discovery',headline:'More favourites in this collection',body:'Keep browsing nearby restaurants and dishes related to this category.',image:PROMOTION_CREATIVE.foodWeekend.asset,backgroundTreatment:'photo',creativeType:'CATEGORY_CAMPAIGN',ctaLabel:'Explore food',ctaScreen:'food',priority:72,sessionCap:1,enabled:true,referenceFixture:true,partnerStatus:'not-required'},
  {id:'activity-related',slot:'contextual',placement:'ACTIVITY_PROMO',service:'activity',campaign:'activity-related',headline:'Discover something related',body:'Completed transactions can surface a subtle next action without interrupting tracking.',image:PROMOTION_CREATIVE.shops.asset,backgroundTreatment:'cream',creativeType:'EDITORIAL_CAMPAIGN',ctaLabel:'Explore Kareebu',ctaScreen:'exploreHub',priority:50,sessionCap:1,cooldownHours:24,enabled:true,referenceFixture:true,partnerStatus:'not-required'},
  {id:'store-pharmacy-wellness',slot:'hero',placement:'STORE_HERO',service:'shops',merchantType:'pharmacy',campaign:'merchant-wellness',headline:'Wellness, care and everyday health',body:'Browse the strongest categories from this pharmacy’s own catalogue.',badge:'STORE COLLECTION',image:PROMOTION_CREATIVE.pharmacy.asset,backgroundTreatment:'cream',creativeType:'MERCHANT_CAMPAIGN',ctaLabel:'Explore this store',ctaScreen:'shop',priority:110,sessionCap:1,enabled:true,referenceFixture:true,partnerStatus:'not-required'},
  {id:'store-beauty-featured',slot:'hero',placement:'STORE_HERO',service:'shops',merchantType:'beauty',campaign:'merchant-beauty',headline:'Build your beauty routine',body:'Skincare, hair and personal-care picks from this seller’s assortment.',badge:'BEAUTY',image:PROMOTION_CREATIVE.beauty.asset,backgroundTreatment:'rose',creativeType:'MERCHANT_CAMPAIGN',ctaLabel:'Explore beauty',ctaScreen:'shop',priority:108,sessionCap:1,enabled:true,referenceFixture:true,partnerStatus:'not-required'},
  {id:'store-pet-featured',slot:'hero',placement:'STORE_HERO',service:'shops',merchantType:'pet-store',campaign:'merchant-pets',headline:'Everyday care for pets',body:'Food, treats, grooming and home pet essentials from this store.',badge:'PET CARE',image:PROMOTION_CREATIVE.shops.asset,backgroundTreatment:'cream',creativeType:'MERCHANT_CAMPAIGN',ctaLabel:'Explore pet care',ctaScreen:'shop',priority:106,sessionCap:1,enabled:true,referenceFixture:true,partnerStatus:'not-required'},
  {id:'store-home-featured',slot:'hero',placement:'STORE_HERO',service:'shops',merchantType:'home-kitchen',campaign:'merchant-home',headline:'Refresh your home',body:'Kitchen, storage, cleaning and home essentials from this seller.',badge:'HOME',image:PROMOTION_CREATIVE.home.asset,backgroundTreatment:'cream',creativeType:'MERCHANT_CAMPAIGN',ctaLabel:'Explore home',ctaScreen:'shop',priority:104,sessionCap:1,enabled:true,referenceFixture:true,partnerStatus:'not-required'},
  {id:'supermarket-fresh-hero',slot:'hero',placement:'SUPERMARKET_HERO',service:'shops',merchantType:'supermarket',campaign:'fresh-storefront',headline:'Fresh finds for your basket',body:'Start with produce, pantry and everyday essentials from this supermarket.',badge:'SUPERMARKET',image:PROMOTION_CREATIVE.groceryFresh.asset,backgroundTreatment:'yellow',creativeType:'MERCHANT_CAMPAIGN',ctaLabel:'Shop fresh',ctaScreen:'shop',priority:130,sessionCap:1,enabled:true,referenceFixture:true,partnerStatus:'not-required'},
  {id:'supermarket-fresh-inline',slot:'contextual',placement:'SUPERMARKET_FRESH',service:'shops',merchantType:'supermarket',categoryId:'fresh',campaign:'fresh-food-collection',headline:'Fresh food, front and centre',body:'Produce and fresh essentials grouped from this store’s current assortment.',image:PROMOTION_CREATIVE.groceryFresh.asset,backgroundTreatment:'cream',creativeType:'CATEGORY_CAMPAIGN',ctaLabel:'Explore fresh food',ctaScreen:'shop',priority:120,sessionCap:1,enabled:true,referenceFixture:true,partnerStatus:'not-required'},
  {id:'supermarket-household-inline',slot:'contextual',placement:'SUPERMARKET_HOUSEHOLD',service:'shops',merchantType:'supermarket',categoryId:'household',campaign:'household-collection',headline:'Home essentials, sorted',body:'Cleaning, laundry and household products grouped into one useful collection.',image:PROMOTION_CREATIVE.groceryHousehold.asset,backgroundTreatment:'cream',creativeType:'CATEGORY_CAMPAIGN',ctaLabel:'Shop household',ctaScreen:'shop',priority:116,sessionCap:1,enabled:true,referenceFixture:true,partnerStatus:'not-required'},
  {id:'electronics-storefront-hero',slot:'hero',placement:'ELECTRONICS_HERO',service:'shops',merchantType:'electronics',campaign:'electronics-storefront',headline:'Tech for everyday life',body:'Mobiles, accessories, audio, computing and gaming from this seller’s catalogue.',badge:'TECH',image:PROMOTION_CREATIVE.electronics.asset,backgroundTreatment:'charcoal',creativeType:'MERCHANT_CAMPAIGN',ctaLabel:'Explore technology',ctaScreen:'shop',priority:130,sessionCap:1,enabled:true,referenceFixture:true,partnerStatus:'not-required'},
  {id:'electronics-gaming-hub',slot:'contextual',placement:'ELECTRONICS_GAMING',service:'shops',merchantType:'electronics',categoryId:'gaming',campaign:'gaming-hub',headline:'Gaming Hub',body:'Consoles, controllers, audio and accessories grouped for easier discovery.',badge:'GAMING',image:PROMOTION_CREATIVE.electronics.asset,foregroundImage:require('../../assets/kareebu-plus/global/products/headphones.png'),backgroundTreatment:'charcoal',creativeType:'CATEGORY_CAMPAIGN',ctaLabel:'Explore gaming',ctaScreen:'shop',priority:120,sessionCap:1,enabled:true,referenceFixture:true,partnerStatus:'not-required'},

  {id:'landing-pharmacy-hero',slot:'hero',placement:'LANDING_HERO',service:'pharmacy',campaign:'deep-pharmacy-discovery',headline:'Care, organised around what you need',body:'Move from health needs into useful subcategories, pharmacies and products without losing context.',image:PROMOTION_CREATIVE.pharmacy.asset,backgroundTreatment:'cream',creativeType:'CATEGORY_CAMPAIGN',ctaLabel:'Explore pharmacy',ctaScreen:'pharmacyHome',priority:95,sessionCap:1,enabled:true,referenceFixture:true,partnerStatus:'not-required'},
  {id:'landing-pharmacy-inline',slot:'contextual',placement:'LANDING_INLINE_1',service:'pharmacy',campaign:'pharmacy-wellness-path',headline:'Keep exploring wellness',body:'Vitamins, personal care, skincare and family health remain close as you browse.',image:PROMOTION_CREATIVE.vitamins.asset,backgroundTreatment:'yellow',creativeType:'CATEGORY_CAMPAIGN',ctaLabel:'Explore wellness',ctaScreen:'pharmacyHome',priority:82,sessionCap:1,enabled:true,referenceFixture:true,partnerStatus:'not-required'},
  {id:'landing-grocery-hero',slot:'hero',placement:'LANDING_HERO',service:'groceries',campaign:'grocery-department-discovery',headline:'Build your basket by aisle',body:'Fresh food, drinks, pantry, household and everyday care organised into useful shopping destinations.',image:PROMOTION_CREATIVE.groceryFresh.asset,backgroundTreatment:'cream',creativeType:'CATEGORY_CAMPAIGN',ctaLabel:'Explore groceries',ctaScreen:'groceries',priority:94,sessionCap:1,enabled:true,referenceFixture:true,partnerStatus:'not-required'},
  {id:'landing-grocery-inline',slot:'contextual',placement:'LANDING_INLINE_1',service:'groceries',campaign:'grocery-related-aisles',headline:'More useful aisles for your basket',body:'Move between related grocery departments without returning to the start.',image:PROMOTION_CREATIVE.groceryHousehold.asset,backgroundTreatment:'green',creativeType:'CATEGORY_CAMPAIGN',ctaLabel:'Keep shopping',ctaScreen:'groceries',priority:80,sessionCap:1,enabled:true,referenceFixture:true,partnerStatus:'not-required'},
  {id:'landing-shops-hero',slot:'hero',placement:'LANDING_HERO',service:'shops',campaign:'retail-category-discovery',headline:'Browse before you compare',body:'Explore subcategories, brands, sellers and useful collections before comparing products.',image:PROMOTION_CREATIVE.shops.asset,backgroundTreatment:'yellow',creativeType:'CATEGORY_CAMPAIGN',ctaLabel:'Explore shops',ctaScreen:'shops',priority:93,sessionCap:1,enabled:true,referenceFixture:true,partnerStatus:'not-required'},
  {id:'landing-shops-inline',slot:'contextual',placement:'LANDING_INLINE_1',service:'shops',campaign:'retail-related-discovery',headline:'More ways to browse this category',body:'Related collections, sellers and products stay contextual to where you are.',image:PROMOTION_CREATIVE.electronics.asset,backgroundTreatment:'cream',creativeType:'EDITORIAL_CAMPAIGN',ctaLabel:'Keep exploring',ctaScreen:'shops',priority:78,sessionCap:1,enabled:true,referenceFixture:true,partnerStatus:'not-required'},
  {id:'landing-goout-hero',slot:'hero',placement:'LANDING_HERO',service:'goout',campaign:'goout-category-discovery',headline:'Find the right experience for the day',body:'Browse activities by type, occasion and experience before choosing a venue.',image:PROMOTION_CREATIVE.goout.asset,backgroundTreatment:'photo',creativeType:'EVENT_CAMPAIGN',ctaLabel:'Explore experiences',ctaScreen:'exploreHub',priority:96,sessionCap:1,enabled:true,referenceFixture:true,partnerStatus:'not-required'},
  {id:'landing-dineout-hero',slot:'hero',placement:'LANDING_HERO',service:'dineout',campaign:'dineout-category-discovery',headline:'Find somewhere worth going out for',body:'Browse by occasion and cuisine, then compare real restaurant and venue options.',image:PROMOTION_CREATIVE.dineoutWeekend.asset,backgroundTreatment:'photo',creativeType:'EDITORIAL_CAMPAIGN',ctaLabel:'Explore dining',ctaScreen:'dineOut',priority:96,sessionCap:1,enabled:true,referenceFixture:true,partnerStatus:'not-required'},
  {id:'landing-global-hero',slot:'hero',placement:'LANDING_HERO',service:'global',campaign:'global-department-discovery',headline:'Browse the world’s marketplaces by department',body:'Browse by marketplace, department, brand and product while keeping the delivered-price estimate in view.',image:PROMOTION_CREATIVE.globalHero.asset,backgroundTreatment:'yellow',creativeType:'MARKETPLACE_CAMPAIGN',ctaLabel:'Explore Global',ctaScreen:'globalHome',priority:98,sessionCap:1,enabled:true,referenceFixture:true,partnerStatus:'unknown'},
  {id:'landing-global-inline',slot:'contextual',placement:'LANDING_INLINE_1',service:'global',campaign:'global-related-discovery',headline:'More from this global department',body:'Explore related categories, brands and product families from supported international sources.',image:PROMOTION_CREATIVE.globalSchool.asset,backgroundTreatment:'green',creativeType:'CATEGORY_CAMPAIGN',ctaLabel:'Keep exploring',ctaScreen:'globalCollection',priority:83,sessionCap:1,enabled:true,referenceFixture:true,partnerStatus:'unknown'},
];

export function promotionsFor(context: PromotionContext, slot?: PromotionSlot, source: PromotionCampaign[] = DEMO_PROMOTION_CATALOG) {
  const now = (context.now ?? new Date()).getTime();
  return source.filter((item) => item.enabled
    && item.service === context.service
    && (!slot || item.slot === slot)
    && (!item.country || item.country === context.country)
    && (!item.city || item.city === context.city)
    && (!item.membershipRequired || context.member)
    && (!item.categoryId || !context.categoryId || item.categoryId === context.categoryId)
    && (!item.subcategoryId || !context.subcategoryId || item.subcategoryId === context.subcategoryId)
    && (!item.sellerId || !context.sellerId || item.sellerId === context.sellerId)
    && (!item.marketplaceId || !context.marketplaceId || item.marketplaceId === context.marketplaceId)
    && (!item.merchantType || !context.merchantType || item.merchantType === context.merchantType)
    && (!item.startAt || new Date(item.startAt).getTime() <= now)
    && (!item.endAt || new Date(item.endAt).getTime() >= now))
    .sort((a,b) => b.priority-a.priority);
}
