import React, { memo, useEffect, useMemo, useRef, useState } from 'react';
import { FlatList, Image, Pressable, StyleSheet, Text, View } from 'react-native';
import { Feather, Ionicons } from '@expo/vector-icons';
import { useSafeAreaInsets } from 'react-native-safe-area-context';
import { KareebuSearchField } from '../components/KareebuSearchField';
import { SellerLogo } from '../commerce/SellerLogo';
import { categoryVisual } from '../visuals/categoryVisuals';
import { commerceProductVisual } from '../commerce/productVisuals';
import { COLORS, RADIUS, SHADOW, SPACE, TYPE } from '../theme';
import { PromotionSurface } from '../promotions/PromotionSurface';
import type { PromotionCampaign, PromotionService } from '../promotions/types';
import { CategoryFilterRail, CategoryLandingHero, DealCategoryGrid } from './components';
import type { CategoryDeal, CategoryLandingConfig, CategoryProduct, CategorySeller } from './types';
import { categoryLandingState, saveCategoryLandingState } from './state';

type Props={config:CategoryLandingConfig;sellers:CategorySeller[];products:CategoryProduct[];state?:'loading'|'ready'|'error';onBack:()=>void;onOpenSeller:(id:string)=>void;onOpenProduct:(id:string)=>void;onOpenPromotion?:(campaign:PromotionCampaign)=>void;onRetry?:()=>void};

const ProductTile=memo(function ProductTile({item,onPress}:{item:CategoryProduct;onPress:()=>void}){const visual=categoryVisual(item.visualKey??'');const productVisual=commerceProductVisual({id:item.id,name:item.title,brand:item.brand,detail:item.pack,imageKey:item.visualKey});const image=item.image??productVisual.image;return <Pressable accessibilityRole="button" accessibilityLabel={`${item.title}. ${item.isLivePrice&&item.referencePrice?`${item.currency} ${item.referencePrice}`:'Price confirmed by seller'}.`} onPress={onPress} style={({pressed})=>[styles.product,pressed&&styles.pressed]}><View style={[styles.productArt,{backgroundColor:productVisual.background}]}>{image?<Image source={image} accessibilityLabel={visual.alt??item.title} resizeMode="cover" style={styles.productImage}/>:<View style={{width:104,height:104,borderRadius:16,backgroundColor:'#F4F1EB'}}/>}</View>{item.brand?<Text numberOfLines={1} style={styles.brand}>{item.brand}</Text>:null}<Text numberOfLines={2} style={styles.productTitle}>{item.title}</Text><Text numberOfLines={1} style={styles.productMeta}>{item.pack??'Details at seller'}</Text><View style={styles.productFooter}><Text style={styles.price}>{item.isLivePrice&&item.referencePrice?`${item.currency} ${item.referencePrice.toLocaleString()}`:'Price at seller'}</Text><View style={styles.add}><Feather name="plus" size={18}/></View></View></Pressable>});

export function CategoryLandingPage({config,sellers,products,state='ready',onBack,onOpenSeller,onOpenProduct,onOpenPromotion,onRetry}:Props){const insets=useSafeAreaInsets();const restored=categoryLandingState(config.id);const restoredOffset=restored.scrollOffset??0;const listRef=useRef<FlatList<CategoryProduct>>(null);const restoredRef=useRef(false);const [query,setQuery]=useState(restored.query);const [filter,setFilter]=useState<string|null>(restored.filter);const offsetRef=useRef(restoredOffset);useEffect(()=>{saveCategoryLandingState(config.id,{query,filter,scrollOffset:offsetRef.current});},[config.id,filter,query]);const visible=useMemo(()=>{const term=query.trim().toLowerCase();return products.filter(item=>!term||`${item.title} ${item.brand??''} ${item.pack??''}`.toLowerCase().includes(term));},[products,query]);const deals=useMemo<CategoryDeal[]>(()=>[{id:'configured',title:'Configured picks',body:'Browse the current catalogue selection',visualKey:config.hero.visualKey,eligibilityKnown:true},{id:'plus',title:'Kareebu+ Deals',body:'Shown when eligible',visualKey:'pharmacy.vitamins',eligibilityKnown:false},{id:'local',title:'Configured Offers',body:`Campaigns available for ${config.city}`,visualKey:'shops.specialty',eligibilityKnown:false},{id:'delivery',title:'Delivery Benefits',body:'See eligibility before checkout',visualKey:'groceries.fresh',eligibilityKnown:false}],[config.city,config.hero.visualKey]);
  if(state==='error')return <View style={styles.state}><Text style={styles.stateTitle}>We couldn’t load {config.title}</Text><Text style={styles.stateBody}>Check your connection and try again.</Text>{onRetry?<Pressable onPress={onRetry} style={styles.retry}><Text style={styles.retryText}>Try again</Text></Pressable>:null}</View>;
  const header=<View><CategoryLandingHero hero={config.hero} market={config.market} onBack={onBack}/><View style={styles.search}><KareebuSearchField context={config.search} value={query} onChangeText={setQuery} elevated={false}/></View><CategoryFilterRail filters={config.filters} selected={filter} onSelect={id=>setFilter(current=>current===id?null:id)}/>{config.kind==='offers'?<View style={styles.section}><Text style={styles.sectionTitle}>Unmissable Deals</Text><Text style={styles.sectionBody}>Eligible offers and terms appear before you order.</Text><DealCategoryGrid deals={deals} onPress={()=>undefined}/></View>:null}<View style={styles.section}><PromotionSurface service={(config.service==='groceries'?'groceries':config.service==='pharmacy'?'pharmacy':config.service==='food'?'food':'shops') as PromotionService} placement="CATEGORY_INLINE" country={config.market} city={config.city} categoryId={config.category} layout="compact" onPress={campaign=>onOpenPromotion?.(campaign)}/></View>{sellers.length?<View style={styles.section}><Text style={styles.sectionTitle}>{config.kind==='new-additions'?'Newly Dropped':config.sections.find(item=>item.type==='featured_seller')?.title??'Recommended Sellers'}</Text><FlatList horizontal data={sellers} keyExtractor={item=>item.id} showsHorizontalScrollIndicator={false} contentContainerStyle={styles.sellerRail} renderItem={({item})=><Pressable accessibilityRole="button" accessibilityLabel={`Open ${item.name}`} onPress={()=>onOpenSeller(item.id)} style={styles.seller}><View style={styles.logo}>{item.logo?<Image source={item.logo} resizeMode="contain" style={styles.logoImage}/>:<SellerLogo name={item.name}/>}</View><Text numberOfLines={2} style={styles.sellerName}>{item.name}</Text><Text numberOfLines={1} style={styles.productMeta}>{item.liveAvailability?item.eta:'View seller'}</Text></Pressable>}/></View>:null}<View style={styles.allHeader}><Text style={styles.sectionTitle}>{config.sections.find(item=>item.type==='all_products')?.title??`All ${config.title}`}</Text><Text style={styles.sectionBody}>{visible.length} item{visible.length===1?'':'s'} · availability shown by each seller</Text></View></View>;
  return <FlatList ref={listRef} data={state==='loading'?[]:visible} numColumns={2} keyExtractor={item=>item.id} renderItem={({item})=><ProductTile item={item} onPress={()=>onOpenProduct(item.id)}/>} columnWrapperStyle={styles.columns} ListHeaderComponent={header} contentContainerStyle={{paddingBottom:Math.max(insets.bottom,20)+32}} initialNumToRender={8} maxToRenderPerBatch={6} windowSize={7} removeClippedSubviews scrollEventThrottle={32} onScroll={event=>{offsetRef.current=event.nativeEvent.contentOffset.y}} onContentSizeChange={()=>{if(restoredRef.current||restoredOffset<=0)return;restoredRef.current=true;requestAnimationFrame(()=>listRef.current?.scrollToOffset({offset:restoredOffset,animated:false}))}} onMomentumScrollEnd={()=>saveCategoryLandingState(config.id,{query,filter,scrollOffset:offsetRef.current})} ListEmptyComponent={<View style={styles.empty}><Ionicons name={state==='loading'?'hourglass-outline':'search-outline'} size={36}/><Text style={styles.stateTitle}>{state==='loading'?'Loading category…':'No products found'}</Text><Text style={styles.stateBody}>{state==='loading'?'Kareebu is loading sellers and products.':'Try clearing search or choosing another category.'}</Text></View>}/>;
}

const styles=StyleSheet.create({search:{marginHorizontal:SPACE.lg,marginTop:SPACE.lg},section:{paddingHorizontal:SPACE.lg,paddingBottom:SPACE.xl},sectionTitle:{...TYPE.sectionTitle},sectionBody:{...TYPE.small,color:COLORS.muted,marginTop:4,marginBottom:SPACE.md},sellerRail:{gap:SPACE.md,paddingVertical:SPACE.md,paddingRight:SPACE.lg},seller:{width:142,minHeight:150,borderRadius:RADIUS.lg,backgroundColor:COLORS.white,padding:SPACE.sm,...SHADOW},logo:{height:82,borderRadius:RADIUS.md,backgroundColor:COLORS.yellowWash,alignItems:'center',justifyContent:'center',overflow:'hidden'},logoImage:{width:70,height:62},sellerName:{...TYPE.cardTitle,marginTop:SPACE.sm},allHeader:{paddingHorizontal:SPACE.lg,paddingBottom:SPACE.md},columns:{paddingHorizontal:SPACE.lg,gap:SPACE.md},product:{flex:1,maxWidth:'48.5%',minHeight:250,borderRadius:RADIUS.lg,backgroundColor:COLORS.white,padding:SPACE.sm,marginBottom:SPACE.md,...SHADOW},productArt:{height:126,borderRadius:RADIUS.md,backgroundColor:COLORS.yellowWash,alignItems:'center',justifyContent:'center'},productImage:{width:112,height:112},brand:{...TYPE.caption,color:COLORS.muted,fontWeight:'800',textTransform:'uppercase',marginTop:SPACE.sm},productTitle:{...TYPE.cardTitle,marginTop:4},productMeta:{...TYPE.caption,color:COLORS.muted,marginTop:3},productFooter:{marginTop:'auto',paddingTop:SPACE.sm,flexDirection:'row',alignItems:'center',justifyContent:'space-between'},price:{...TYPE.caption,fontWeight:'800',color:COLORS.muted},add:{width:36,height:36,borderRadius:12,backgroundColor:COLORS.yellow,alignItems:'center',justifyContent:'center'},state:{flex:1,alignItems:'center',justifyContent:'center',padding:SPACE.xl},stateTitle:{...TYPE.sectionTitle,textAlign:'center'},stateBody:{...TYPE.body,color:COLORS.muted,textAlign:'center',marginTop:6},retry:{minHeight:48,borderRadius:RADIUS.md,backgroundColor:COLORS.yellow,paddingHorizontal:SPACE.xl,alignItems:'center',justifyContent:'center',marginTop:SPACE.lg},retryText:{...TYPE.button},empty:{margin:SPACE.xl,padding:SPACE.xl,alignItems:'center',backgroundColor:COLORS.yellowWash,borderRadius:RADIUS.lg},pressed:{opacity:.78,transform:[{scale:.98}]}});
