import React, { memo } from 'react';
import { FlatList, Pressable, StyleSheet, Text, View } from 'react-native';
import { Feather } from '@expo/vector-icons';
import { useSafeAreaInsets } from 'react-native-safe-area-context';
import { CategoryArtwork } from '../components/CategoryArtwork';
import { COLORS, RADIUS, SHADOW, SPACE, TYPE } from '../theme';
import type { CategoryDeal, CategoryFilterConfig, CategoryHeroConfig } from './types';
import { useRegisterBackControl } from '../navigation/AppNavigation';

export const CategoryLandingHero=memo(function CategoryLandingHero({hero,market,onBack}:{hero:CategoryHeroConfig;market:string;onBack:()=>void}){const insets=useSafeAreaInsets();useRegisterBackControl(true);return <View style={styles.hero}><Pressable accessibilityRole="button" accessibilityLabel="Go back" onPress={onBack} style={[styles.back,{top:Math.max(insets.top,12)+8}]}><Feather name="arrow-left" size={22} color={COLORS.black}/></Pressable><View style={styles.heroCopy}><View style={styles.heroText}><Text accessibilityRole="header" style={styles.heroTitle}>{hero.title}</Text><Text style={styles.heroSubtitle}>{hero.subtitle}</Text></View><View style={styles.heroArt}><CategoryArtwork visualKey={hero.visualKey} market={market} size="hero"/></View></View></View>});

export const CategoryFilterRail=memo(function CategoryFilterRail({filters,selected,onSelect}:{filters:CategoryFilterConfig[];selected:string|null;onSelect:(id:string)=>void}){return <FlatList horizontal data={filters} keyExtractor={item=>item.id} showsHorizontalScrollIndicator={false} contentContainerStyle={styles.filterRail} renderItem={({item})=>{const active=selected===item.id;return <Pressable accessibilityRole="button" accessibilityState={{selected:active}} accessibilityLabel={item.label} onPress={()=>onSelect(item.id)} style={[styles.filter,active&&styles.filterActive]}><Text style={[styles.filterText,active&&styles.filterTextActive]}>{item.label}</Text></Pressable>}}/>});

export const DealCategoryGrid=memo(function DealCategoryGrid({deals,onPress}:{deals:CategoryDeal[];onPress:(deal:CategoryDeal)=>void}){return <View style={styles.dealGrid}>{deals.map(deal=><Pressable key={deal.id} accessibilityRole="button" accessibilityLabel={`${deal.title}. ${deal.eligibilityKnown?deal.body:'Eligibility checked before showing a benefit.'}`} onPress={()=>onPress(deal)} style={styles.deal}><View style={styles.dealArt}><CategoryArtwork visualKey={deal.visualKey} size="standard"/></View><Text numberOfLines={2} style={styles.dealTitle}>{deal.title}</Text><Text numberOfLines={2} style={styles.dealBody}>{deal.body}</Text></Pressable>)}</View>});

const styles=StyleSheet.create({hero:{height:276,backgroundColor:COLORS.yellowWash,overflow:'hidden'},back:{position:'absolute',left:SPACE.lg,width:48,height:48,borderRadius:15,backgroundColor:COLORS.white,alignItems:'center',justifyContent:'center',zIndex:2,...SHADOW},heroCopy:{position:'absolute',left:SPACE.lg,right:SPACE.lg,bottom:SPACE.xl,flexDirection:'row',alignItems:'flex-end',gap:SPACE.md},heroText:{flex:1},heroTitle:{fontSize:30,lineHeight:35,fontWeight:'900',color:COLORS.black},heroSubtitle:{...TYPE.body,color:COLORS.black,marginTop:6,maxWidth:220},heroArt:{width:124,height:124,borderRadius:34,backgroundColor:'rgba(255,255,255,.78)',alignItems:'center',justifyContent:'center',overflow:'hidden'},filterRail:{paddingHorizontal:SPACE.lg,paddingVertical:SPACE.lg,gap:SPACE.sm},filter:{minHeight:40,borderRadius:15,borderWidth:1,borderColor:COLORS.line,backgroundColor:COLORS.white,paddingHorizontal:SPACE.md,alignItems:'center',justifyContent:'center'},filterActive:{backgroundColor:COLORS.yellow,borderColor:COLORS.yellow},filterText:{...TYPE.small,fontWeight:'700'},filterTextActive:{fontWeight:'900'},dealGrid:{flexDirection:'row',flexWrap:'wrap',gap:SPACE.md},deal:{width:'47.8%',minHeight:170,borderRadius:RADIUS.lg,backgroundColor:COLORS.yellowWash,padding:SPACE.md},dealArt:{height:82,alignItems:'center',justifyContent:'center'},dealTitle:{...TYPE.cardTitle,marginTop:4},dealBody:{...TYPE.caption,color:COLORS.muted,marginTop:3}});
