import { foodCategorySearchContext, searchContextForVertical } from '../search/context';
import type { CategoryLandingConfig, CategoryLandingKind, CategoryService } from './types';
import type { AppEnginePageDefinition, AppEngineSectionType } from '../appEngine/types';

const FOOD=['Offers','New Additions','Burgers','Pizza','Healthy','Chicken','African','Indian','Breakfast'] as const;
const VERTICALS:Record<Exclude<CategoryService,'food'|'shops'>,readonly string[]>={
  pharmacy:['Cold & Flu','Pain Relief','Allergy','Digestive','First Aid','Vitamins','Baby Care','Personal Care'],
  groceries:['Fresh Produce','Meat & Fish','Dairy & Eggs','Drinks','Snacks','Cooking'],
  electronics:['Phones','Accessories','Audio','Computers','Gaming','TV','Appliances','Power & Charging'],
  pets:['Dogs','Cats','Birds','Small Pets','Food','Treats','Toys','Grooming'],
  gifts:['Birthday','Anniversary','Congratulations','Thank You','New Baby','Just Because'],
  beauty:['Skincare','Hair','Makeup','Fragrance','Body','Grooming'],
  fashion:['Women','Men','Kids','Shoes','Accessories','Sportswear','Bags'],
  butchery:['Beef','Goat','Chicken','Fish','Seafood','BBQ Picks'],
};

const slug=(value:string)=>value.toLowerCase().replace(/&/g,'and').replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'');
const VISUAL_OVERRIDES:Record<string,string>={
  'food/offers':'food.food','food/new-additions':'food.breakfast','food/burgers':'food.burgers','food/pizza':'food.pizza','food/healthy':'food.healthy','food/chicken':'food.chicken','food/african':'food.african','food/indian':'food.indian','food/breakfast':'food.breakfast',
  'pharmacy/cold-and-flu':'pharmacy.cold-flu','pharmacy/pain-relief':'pharmacy.pain-relief','pharmacy/allergy':'pharmacy.allergy','pharmacy/digestive':'pharmacy.digestive','pharmacy/first-aid':'pharmacy.first-aid','pharmacy/vitamins':'pharmacy.vitamins','pharmacy/baby-care':'pharmacy.baby-care','pharmacy/personal-care':'pharmacy.personal-care',
  'groceries/fresh-produce':'groceries.fresh','groceries/meat-and-fish':'groceries.meat-fish','groceries/dairy-and-eggs':'groceries.dairy','groceries/drinks':'groceries.drinks','groceries/snacks':'groceries.snacks','groceries/cooking':'groceries.cooking',
  'electronics/phones':'electronics.phones','pets/dogs':'pets.dogs','gifts/birthday':'gifts.birthday','beauty/skincare':'beauty.skincare','fashion/women':'fashion.women','butchery/fish':'butchery.fish',
};
const visualKey=(service:CategoryService,category:string)=>VISUAL_OVERRIDES[`${service}/${slug(category)}`]??`${service}.${slug(category)}`;
const foodEditorial:Record<string,[string,string]>={
  Burgers:['Burgers Done Right','Trending Burger Spots'],Pizza:['From Our Oven to Your Door','Top Artisan Pizzas'],Healthy:['Fresh Picks','Healthy Favourites'],Chicken:['Chicken Favourites','Grilled & Good'],African:['Taste of Home','Popular African Kitchens'],Indian:['Indian Favourites','Curries & Grills'],Breakfast:['Start Well','Breakfast Favourites'],Offers:['Unmissable Deals','More Deals'],'New Additions':['Newly Dropped','All New Restaurants'],
};

function kindFor(category:string):CategoryLandingKind{return category==='Offers'?'offers':category==='New Additions'?'new-additions':'standard'}
function searchFor(service:CategoryService,category:string,country:string,city:string){if(service==='food')return foodCategorySearchContext(category==='New Additions'?'new':category==='Offers'?'offer':category,{market:country,city});const placeholders:Partial<Record<CategoryService,string>>={pharmacy:'Search medicines & wellness',groceries:'Search groceries',electronics:'Search phones, tech and appliances',pets:'Search pet food, toys and care',gifts:'Search gifts, flowers and hampers',beauty:'Search beauty & personal care',fashion:'Search fashion',butchery:'Search meat, fish & seafood'};return searchContextForVertical(service,placeholders[service]??`Search ${category.toLowerCase()}`,{market:country,city,category});}

export function categoryLandingConfig(service:CategoryService,category:string,country:string,city:string):CategoryLandingConfig{
  const kind=kindFor(category);const editorial=foodEditorial[category]??[`Featured ${category}`,`Popular ${category}`];const key=visualKey(service,category);
  const sections=kind==='offers'?[{id:'deals',type:'deal_grid' as const,title:'Configured Deals',subtitle:'Eligibility and live benefits come from configured campaigns',enabled:true,priority:100},{id:'featured',type:'featured_seller' as const,title:'Featured Offers',enabled:true,priority:90},{id:'more',type:'trending_sellers' as const,title:'More Deals',enabled:true,priority:70},{id:'all',type:'all_sellers' as const,title:service==='food'?'All Restaurants':'All Sellers',enabled:true,priority:10}]:kind==='new-additions'?[{id:'new',type:'new_sellers' as const,title:'Configured Additions',subtitle:`Reference listings configured for ${city}`,enabled:true,priority:100},{id:'all',type:'all_sellers' as const,title:service==='food'?'All Restaurants':'All Sellers',enabled:true,priority:10}]:[{id:'featured',type:'featured_seller' as const,title:editorial[0],enabled:true,priority:100},{id:'brands',type:'brand_carousel' as const,title:service==='food'?'Restaurants':'Brands to browse',enabled:true,priority:90},{id:'editorial',type:service==='food'?'editorial_carousel' as const:'product_carousel' as const,title:editorial[1],enabled:true,priority:70},{id:'best',type:'best_sellers' as const,title:`More ${category.toLowerCase()}`,enabled:true,priority:60},{id:'all',type:service==='food'?'all_sellers' as const:'all_products' as const,title:service==='food'?'All Restaurants':`All ${category}`,enabled:true,priority:10}];
  return {id:`${service}-${slug(category)}-${country.toLowerCase()}`,pageType:'categoryLanding',service,category,kind,title:category,subtitle:kind==='offers'?`Configured food and delivery offers in ${city}`:kind==='new-additions'?`New places worth discovering in ${city}`:`Discover ${category.toLowerCase()} around ${city}`,market:country,city,hero:{slot:`${service}_${slug(category).replace(/-/g,'_')}_HERO`.toUpperCase(),title:category,subtitle:kind==='offers'?'Offers selected for your market and eligibility':kind==='new-additions'?`New in ${city}`:`${category} selected for ${city}`,visualKey:key,backgroundTreatment:'cream',enabled:true},search:searchFor(service,category,country,city),filters:service==='food'?[{id:'rating',label:'4.7+ Rated',kind:'rating'},{id:'top',label:'Top Choices',kind:'sort'},{id:'offers',label:'Offers',kind:'offers'},{id:'fast',label:'Fast Delivery',kind:'delivery'},{id:'plus',label:'Kareebu+',kind:'membership'}]:[{id:'popular',label:'Popular',kind:'sort'},{id:'offers',label:'Offers',kind:'offers'},{id:'nearby',label:'Nearby',kind:'delivery'},{id:'plus',label:'Kareebu+',kind:'membership'}],sections,version:'1.0.0'};
}

export const CATEGORY_LANDING_REGISTRY={food:FOOD, ...VERTICALS};
export function supportedCategory(service:CategoryService,category:string){const rows=(CATEGORY_LANDING_REGISTRY as Partial<Record<CategoryService,readonly string[]>>)[service];return Boolean(rows?.some(item=>item.toLowerCase()===category.toLowerCase()));}

const APP_ENGINE_SECTION:Record<CategoryLandingConfig['sections'][number]['type'],AppEngineSectionType>={featured_seller:'merchant-carousel',featured_product:'product-carousel',deal_grid:'deal-grid',seller_carousel:'merchant-carousel',brand_carousel:'brand-carousel',product_carousel:'product-carousel',trending_sellers:'trending-sellers',editorial_carousel:'editorial-carousel',new_sellers:'new-sellers',nearby:'merchant-carousel',best_sellers:'bestsellers',most_ordered:'recommendation-rail',promo:'banner-carousel',all_sellers:'all-sellers',all_products:'all-products'};
export function categoryLandingPageDefinition(config:CategoryLandingConfig):AppEnginePageDefinition{return{id:config.id,type:'category-landing',title:config.title,version:config.version,header:{type:'detail',title:config.title,showSearch:true,search:{...config.search,enabled:true,suggestionsEnabled:true,recentSearchesEnabled:true}},navigation:{showBottomNavigation:true,backBehaviour:'history'},targeting:{countries:[config.market],cities:[config.city]},sections:[{id:'category-hero',type:'category-hero',title:config.hero.title,subtitle:config.hero.subtitle,slot:config.hero.slot,layout:'full-width',enabled:config.hero.enabled,priority:1000,data:{hero:config.hero}}, {id:'category-filters',type:'filter-rail',layout:'carousel',enabled:Boolean(config.filters.length),priority:900,data:{filters:config.filters}},...config.sections.map(section=>({id:section.id,type:APP_ENGINE_SECTION[section.type],title:section.title,subtitle:section.subtitle,slot:section.slot,layout:section.type==='all_products'?'grid-2' as const:section.type==='all_sellers'?'stack' as const:section.type==='deal_grid'?'grid-2' as const:'carousel' as const,enabled:section.enabled,priority:section.priority,data:{itemIds:section.itemIds}}))]};}
