import type { GlobalCategoryId } from './types';

export type GlobalTaxonomyNode={id:string;label:string;category:GlobalCategoryId;parentId?:string;children?:string[];searchTerms?:string[]};

const tree:GlobalTaxonomyNode[]=[
  {id:'electronics',label:'Electronics',category:'electronics',children:['electronics.phones','electronics.phone-accessories','electronics.computers','electronics.audio','electronics.gaming','electronics.tv','electronics.cameras','electronics.smart-home','electronics.wearables']},
  {id:'electronics.phones',label:'Phones',category:'electronics',parentId:'electronics',children:['electronics.phones.smartphones','electronics.phones.feature','electronics.phones.refurbished']},
  {id:'electronics.phones.smartphones',label:'Smartphones',category:'electronics',parentId:'electronics.phones',searchTerms:['smartphone','phone']},
  {id:'electronics.phones.feature',label:'Feature phones',category:'electronics',parentId:'electronics.phones'},
  {id:'electronics.phones.refurbished',label:'Refurbished phones',category:'electronics',parentId:'electronics.phones'},
  {id:'electronics.phone-accessories',label:'Phone accessories',category:'electronics',parentId:'electronics',children:['electronics.phone-accessories.cases','electronics.phone-accessories.screen-protectors','electronics.phone-accessories.chargers','electronics.phone-accessories.cables','electronics.phone-accessories.power-banks','electronics.phone-accessories.mounts']},
  {id:'electronics.phone-accessories.cases',label:'Cases',category:'electronics',parentId:'electronics.phone-accessories'},
  {id:'electronics.phone-accessories.screen-protectors',label:'Screen protectors',category:'electronics',parentId:'electronics.phone-accessories'},
  {id:'electronics.phone-accessories.chargers',label:'Chargers',category:'electronics',parentId:'electronics.phone-accessories'},
  {id:'electronics.phone-accessories.cables',label:'Cables',category:'electronics',parentId:'electronics.phone-accessories'},
  {id:'electronics.phone-accessories.power-banks',label:'Power banks',category:'electronics',parentId:'electronics.phone-accessories'},
  {id:'electronics.phone-accessories.mounts',label:'Mounts',category:'electronics',parentId:'electronics.phone-accessories'},
  {id:'electronics.computers',label:'Computers',category:'electronics',parentId:'electronics',children:['electronics.computers.laptops','electronics.computers.desktops','electronics.computers.monitors','electronics.computers.keyboards','electronics.computers.mice','electronics.computers.storage','electronics.computers.components']},
  {id:'electronics.computers.laptops',label:'Laptops',category:'electronics',parentId:'electronics.computers'},
  {id:'electronics.computers.desktops',label:'Desktops',category:'electronics',parentId:'electronics.computers'},
  {id:'electronics.computers.monitors',label:'Monitors',category:'electronics',parentId:'electronics.computers'},
  {id:'electronics.computers.keyboards',label:'Keyboards',category:'electronics',parentId:'electronics.computers'},
  {id:'electronics.computers.mice',label:'Mice',category:'electronics',parentId:'electronics.computers'},
  {id:'electronics.computers.storage',label:'Storage',category:'electronics',parentId:'electronics.computers'},
  {id:'electronics.computers.components',label:'Components',category:'electronics',parentId:'electronics.computers'},
  {id:'electronics.audio',label:'Audio',category:'electronics',parentId:'electronics',children:['electronics.audio.earbuds','electronics.audio.headphones','electronics.audio.speakers','electronics.audio.soundbars']},
  {id:'electronics.audio.earbuds',label:'Earbuds',category:'electronics',parentId:'electronics.audio'},
  {id:'electronics.audio.headphones',label:'Headphones',category:'electronics',parentId:'electronics.audio'},
  {id:'electronics.audio.speakers',label:'Speakers',category:'electronics',parentId:'electronics.audio'},
  {id:'electronics.audio.soundbars',label:'Soundbars',category:'electronics',parentId:'electronics.audio'},
  {id:'electronics.gaming',label:'Gaming',category:'electronics',parentId:'electronics',children:['electronics.gaming.consoles','electronics.gaming.controllers','electronics.gaming.games','electronics.gaming.headsets','electronics.gaming.accessories']},
  {id:'electronics.gaming.consoles',label:'Consoles',category:'electronics',parentId:'electronics.gaming'},
  {id:'electronics.gaming.controllers',label:'Controllers',category:'electronics',parentId:'electronics.gaming'},
  {id:'electronics.gaming.games',label:'Games',category:'electronics',parentId:'electronics.gaming'},
  {id:'electronics.gaming.headsets',label:'Gaming headsets',category:'electronics',parentId:'electronics.gaming'},
  {id:'electronics.gaming.accessories',label:'Gaming accessories',category:'electronics',parentId:'electronics.gaming'},
  {id:'electronics.tv',label:'TV & entertainment',category:'electronics',parentId:'electronics'},
  {id:'electronics.cameras',label:'Cameras',category:'electronics',parentId:'electronics'},
  {id:'electronics.smart-home',label:'Smart home',category:'electronics',parentId:'electronics'},
  {id:'electronics.wearables',label:'Wearables',category:'electronics',parentId:'electronics'},

  {id:'fashion',label:'Fashion',category:'fashion',children:['fashion.women','fashion.men','fashion.kids','fashion.shoes','fashion.accessories']},
  {id:'fashion.women',label:'Women',category:'fashion',parentId:'fashion',children:['fashion.women.dresses','fashion.women.tops','fashion.women.jeans','fashion.women.trousers','fashion.women.skirts','fashion.women.jackets','fashion.women.activewear','fashion.women.underwear','fashion.women.swimwear']},
  {id:'fashion.women.dresses',label:'Dresses',category:'fashion',parentId:'fashion.women',children:['fashion.women.dresses.mini','fashion.women.dresses.midi','fashion.women.dresses.maxi','fashion.women.dresses.occasion']},
  {id:'fashion.women.dresses.mini',label:'Mini dresses',category:'fashion',parentId:'fashion.women.dresses'},
  {id:'fashion.women.dresses.midi',label:'Midi dresses',category:'fashion',parentId:'fashion.women.dresses'},
  {id:'fashion.women.dresses.maxi',label:'Maxi dresses',category:'fashion',parentId:'fashion.women.dresses'},
  {id:'fashion.women.dresses.occasion',label:'Occasion dresses',category:'fashion',parentId:'fashion.women.dresses'},
  {id:'fashion.women.tops',label:'Tops',category:'fashion',parentId:'fashion.women'},
  {id:'fashion.women.jeans',label:'Jeans',category:'fashion',parentId:'fashion.women'},
  {id:'fashion.women.trousers',label:'Trousers',category:'fashion',parentId:'fashion.women'},
  {id:'fashion.women.skirts',label:'Skirts',category:'fashion',parentId:'fashion.women'},
  {id:'fashion.women.jackets',label:'Jackets',category:'fashion',parentId:'fashion.women'},
  {id:'fashion.women.activewear',label:'Activewear',category:'fashion',parentId:'fashion.women'},
  {id:'fashion.women.underwear',label:'Underwear',category:'fashion',parentId:'fashion.women'},
  {id:'fashion.women.swimwear',label:'Swimwear',category:'fashion',parentId:'fashion.women'},
  {id:'fashion.men',label:'Men',category:'fashion',parentId:'fashion',children:['fashion.men.tshirts','fashion.men.shirts','fashion.men.jeans','fashion.men.trousers','fashion.men.jackets','fashion.men.suits','fashion.men.activewear']},
  {id:'fashion.men.tshirts',label:'T-shirts',category:'fashion',parentId:'fashion.men'},
  {id:'fashion.men.shirts',label:'Shirts',category:'fashion',parentId:'fashion.men'},
  {id:'fashion.men.jeans',label:'Jeans',category:'fashion',parentId:'fashion.men'},
  {id:'fashion.men.trousers',label:'Trousers',category:'fashion',parentId:'fashion.men'},
  {id:'fashion.men.jackets',label:'Jackets',category:'fashion',parentId:'fashion.men'},
  {id:'fashion.men.suits',label:'Suits',category:'fashion',parentId:'fashion.men'},
  {id:'fashion.men.activewear',label:'Activewear',category:'fashion',parentId:'fashion.men'},
  {id:'fashion.kids',label:'Kids',category:'fashion',parentId:'fashion'},
  {id:'fashion.shoes',label:'Shoes',category:'fashion',parentId:'fashion',children:['fashion.shoes.trainers','fashion.shoes.running','fashion.shoes.formal','fashion.shoes.boots','fashion.shoes.sandals']},
  {id:'fashion.shoes.trainers',label:'Trainers',category:'fashion',parentId:'fashion.shoes'},
  {id:'fashion.shoes.running',label:'Running shoes',category:'fashion',parentId:'fashion.shoes'},
  {id:'fashion.shoes.formal',label:'Formal shoes',category:'fashion',parentId:'fashion.shoes'},
  {id:'fashion.shoes.boots',label:'Boots',category:'fashion',parentId:'fashion.shoes'},
  {id:'fashion.shoes.sandals',label:'Sandals',category:'fashion',parentId:'fashion.shoes'},
  {id:'fashion.accessories',label:'Accessories',category:'accessories',parentId:'fashion'},

  {id:'beauty',label:'Beauty',category:'beauty',children:['beauty.skincare','beauty.makeup','beauty.hair','beauty.fragrance','beauty.personal-care']},
  {id:'beauty.skincare',label:'Skincare',category:'beauty',parentId:'beauty',children:['beauty.skincare.cleansers','beauty.skincare.moisturisers','beauty.skincare.serums','beauty.skincare.sunscreen','beauty.skincare.masks']},
  {id:'beauty.skincare.cleansers',label:'Cleansers',category:'beauty',parentId:'beauty.skincare'},
  {id:'beauty.skincare.moisturisers',label:'Moisturisers',category:'beauty',parentId:'beauty.skincare'},
  {id:'beauty.skincare.serums',label:'Serums',category:'beauty',parentId:'beauty.skincare'},
  {id:'beauty.skincare.sunscreen',label:'Sunscreen',category:'beauty',parentId:'beauty.skincare'},
  {id:'beauty.skincare.masks',label:'Masks',category:'beauty',parentId:'beauty.skincare'},
  {id:'beauty.makeup',label:'Makeup',category:'beauty',parentId:'beauty'},
  {id:'beauty.hair',label:'Hair',category:'beauty',parentId:'beauty'},
  {id:'beauty.fragrance',label:'Fragrance',category:'beauty',parentId:'beauty'},
  {id:'beauty.personal-care',label:'Personal care',category:'beauty',parentId:'beauty'},

  {id:'home',label:'Home & kitchen',category:'home',children:['home.kitchen','home.furniture','home.bedding','home.bathroom','home.storage','home.decor','home.lighting','home.appliances','home.cleaning','home.garden','home.diy']},
  ...['kitchen','furniture','bedding','bathroom','storage','decor','lighting','appliances','cleaning','garden','diy'].map(id=>({id:`home.${id}`,label:id.charAt(0).toUpperCase()+id.slice(1),category:'home' as const,parentId:'home'})),
  {id:'kids',label:'Baby & kids',category:'kids',children:['kids.clothing','kids.feeding','kids.nursery','kids.travel','kids.changing','kids.bathing','kids.learning','kids.toys']},
  ...['clothing','feeding','nursery','travel','changing','bathing','learning','toys'].map(id=>({id:`kids.${id}`,label:id.charAt(0).toUpperCase()+id.slice(1),category:'kids' as const,parentId:'kids'})),
  {id:'sports',label:'Sports & fitness',category:'sports',children:['sports.running','sports.football','sports.gym','sports.cycling','sports.swimming','sports.outdoor','sports.equipment','sports.sportswear']},
  ...['running','football','gym','cycling','swimming','outdoor','equipment','sportswear'].map(id=>({id:`sports.${id}`,label:id.charAt(0).toUpperCase()+id.slice(1),category:'sports' as const,parentId:'sports'})),
  {id:'automotive',label:'Automotive',category:'automotive'},
  {id:'books',label:'Books & media',category:'books'},
  {id:'pets',label:'Pet supplies',category:'pets',children:['pets.dogs','pets.cats','pets.birds','pets.small-pets','pets.food','pets.treats','pets.toys','pets.beds','pets.grooming','pets.health']},
  ...['dogs','cats','birds','small-pets','food','treats','toys','beds','grooming','health'].map(id=>({id:`pets.${id}`,label:id.split('-').map(x=>x.charAt(0).toUpperCase()+x.slice(1)).join(' '),category:'pets' as const,parentId:'pets'})),
  {id:'accessories',label:'Accessories',category:'accessories'},
];

export const GLOBAL_TAXONOMY=tree;
export const GLOBAL_TAXONOMY_BY_ID=new Map(tree.map(node=>[node.id,node]));
export const globalTaxonomyNode=(id:string)=>GLOBAL_TAXONOMY_BY_ID.get(id);
export const globalTaxonomyChildren=(id:string)=>GLOBAL_TAXONOMY.filter(node=>node.parentId===id);
export const GLOBAL_TOP_LEVEL_CATEGORIES=tree.filter(node=>!node.parentId).map(node=>node.category);
