import type { ImageSourcePropType } from 'react-native';
import type { RiskAction } from '../trust/types';
import type { PaymentState } from '../payments/types';

export type GlobalMarketplaceId = 'amazon' | 'ebay' | 'shein' | 'temu' | 'aliexpress' | 'etsy';
export type GlobalCategoryId = 'fashion' | 'electronics' | 'beauty' | 'home' | 'kids' | 'sports' | 'automotive' | 'books' | 'pets' | 'accessories';
export type GlobalQuoteState = 'estimated' | 'refreshing' | 'locked_until' | 'requires_classification' | 'requires_review' | 'expired' | 'price_changed' | 'tariff_changed' | 'unavailable' | 'restricted';
export type GlobalRestrictionState = 'eligible' | 'restricted' | 'prohibited' | 'hazardous' | 'oversized' | 'country-restricted' | 'requires_documentation' | 'requires_regulatory_clearance' | 'manual_review';
export type ImporterModel='CUSTOMER_IMPORTER'|'KAREEBU_IMPORTER'|'THIRD_PARTY_IMPORTER'|'CONSOLIDATOR_MODEL';

export type GlobalProduct = {
  id: string;
  marketplace: GlobalMarketplaceId;
  seller?: string;
  retailer?: string;
  sourceRegion: string;
  sourceReference: string;
  sourceCurrency: 'USD' | 'GBP' | 'EUR';
  sourcePrice: number;
  title: string;
  subtitle?:string;
  brand: string;
  category: GlobalCategoryId;
  subcategory?:string;
  taxonomyPath?:string[];
  image: ImageSourcePropType;
  images: ImageSourcePropType[];
  variant: string;
  variants: string[];
  colours?:string[];
  sizes?:string[];
  description: string;
  specifications: Array<{ label: string; value: string }>;
  compatibilityNote?: string;
  weightKg: number;
  dimensionsCm?:{length:number;width:number;height:number};
  rating?: number;
  reviewCount?: number;
  deliveryDays: [number, number];
  restriction: GlobalRestrictionState;
  stock: 'in_stock' | 'low_stock' | 'unavailable' | 'check_at_quote';
  lastVerifiedAt: string;
  priceExpiresAt?:string;
  availabilityExpiresAt?:string;
  live: boolean;
  dataSource?:'fixture'|'marketplace-api'|'merchant-feed'|'provider';
  referenceFixture?:boolean;
  priceStatus?:'reference'|'live'|'stale';
  partnerStatus: 'partner' | 'independent-source' | 'unknown';
  returnEligibility: 'eligible' | 'conditional' | 'not-eligible';
  cancellationNote: string;
  returnNote: string;
  warrantyNote?: string;
  hsCodeCandidate?:string;
  classificationConfidence?:number;
};

export type GlobalQuoteBreakdown = {
  product: number;
  internationalDelivery: number;
  estimatedDutyTax: number;
  kareebuLogistics: number;
  localDelivery: number;
  discount: number;
  total: number;
  customsValue?:number;
  importDuty?:number;
  importVat?:number;
  importDeclarationFee?:number;
  infrastructureLevy?:number;
  excise?:number;
  environmentalLevy?:number;
  brokerage?:number;
  paymentProcessing?:number;
  recoverableTaxCashflow?:number;
  whtCashflow?:number;
  serviceFee?:number;
  freightMargin?:number;
  fxMargin?:number;
  contributionMargin?:number;
  contributionMarginPercent?:number;
};

export type GlobalQuote = {
  id: string;
  productId: string;
  market: string;
  currency: 'UGX' | 'KES' | 'TZS';
  state: GlobalQuoteState;
  breakdown: GlobalQuoteBreakdown;
  lockedUntil?: string;
  checkedAt: string;
  estimateNotice: string;
  source: 'provider' | 'reference-fixture';
  importerModel?:ImporterModel;
  hsCodeCandidate?:string;
  classificationConfidence?:number;
  requiresManualReview?:boolean;
  assumptions?:string[];
  tariffEffectiveFrom?:string;
  tariffSource?:string;
};

export type GlobalCartLine = { id: string; productId: string; quantity: number; variant: string; quote: GlobalQuote };
export type GlobalOrderStatus = 'verification_hold' | 'order_confirmed' | 'retailer_processing' | 'retailer_dispatched' | 'hub_received' | 'international_preparation' | 'international_transit' | 'customs' | 'destination_arrival' | 'local_delivery' | 'delivered' | 'cancelled' | 'refund_pending' | 'refunded';
export type GlobalOrder = {
  id: string;
  marketplace: GlobalMarketplaceId;
  lines: GlobalCartLine[];
  total: number;
  currency: GlobalQuote['currency'];
  status: GlobalOrderStatus;
  createdAt: string;
  deliveryAddress: string;
  paymentMethod: string;
  source: 'local-session' | 'live';
  paymentAttemptId?:string;
  paymentState?:PaymentState;
  riskAction?:RiskAction;
  verificationState?:'not_required'|'required'|'pending'|'passed'|'manual_review';
};
