import React, { useMemo, useState } from 'react';
import { Alert, Image, Pressable, ScrollView, StyleSheet, Text, TextInput, View } from 'react-native';
import { Feather, Ionicons, MaterialCommunityIcons } from '@expo/vector-icons';
import { Header, PrimaryButton, RoundedCard, ScreenShell, SectionTitle } from '../components';
import { COLORS, FONT, SHADOW, TYPE } from '../theme';
import { formatMoney } from '../locale';
import { MarketplaceCategoryGrid, MarketplaceCategoryHeader, MarketplaceMembershipStrip, MarketplacePromoBanner, MarketplacePromoGrid, MarketplaceRecommendedRail, marketplaceSemanticForCategory } from '../marketplace/MarketplaceCategoryChrome';
import type { Screen } from '../types';

export type V41FrontendData = {
  country: string;
  city: string;
  fullName: string;
  email: string;
  walletBalance: number;
  rewardPoints: number;
};

export type V41FrontendActions = { go: (screen: Screen) => void };

const uiAssets = {
  emptyCart: require('../../assets/v41/empty_cart.png'),
  noInternet: require('../../assets/v41/no_internet.png'),
  update: require('../../assets/v41/update.png'),
  order: require('../../assets/v41/order_place_holder.png'),
  support: require('../../assets/v41/support_redesign.png'),
  refer: require('../../assets/v41/refer_earn.png'),
  groceryList: require('../../assets/v41/grocery_list.png'),
  prescription: require('../../assets/v41/predcription_icon.png'),
  qr: require('../../assets/v41/qrscanner.png'),
  flash: require('../../assets/v41/flash_sale_deshboard.png'),
  crown: require('../../assets/v41/pro_plan_crown.png'),
  coupon: require('../../assets/v41/coupon.png'),
  loyalty: require('../../assets/v41/loyalty_icon.png'),
  wallet: require('../../assets/v41/wallet.png'),
  noAddress: require('../../assets/v41/no_address.png'),
  noCoupon: require('../../assets/v41/no_coupon.png'),
  noData: require('../../assets/v41/no_data_found.png'),
  language: require('../../assets/v41/language.png'),
  profileBg: require('../../assets/v41/profile_bg.png'),
  tracking: require('../../assets/v41/tracking.png'),
  refund: require('../../assets/v41/refund.png'),
};

const categories = [
  { id: 'restaurants', name: 'Restaurants', icon: 'restaurant-outline' as const, color: '#FFE4DE' },
  { id: 'grocery', name: 'Groceries', icon: 'basket-outline' as const, color: '#FFF2C8' },
  { id: 'pharmacy', name: 'Pharmacy', icon: 'medical-outline' as const, color: '#DFF5E8' },
  { id: 'electronics', name: 'Electronics', icon: 'phone-portrait-outline' as const, color: '#E7EBFF' },
  { id: 'fashion', name: 'Fashion', icon: 'shirt-outline' as const, color: '#F5E4FF' },
  { id: 'home', name: 'Home & living', icon: 'home-outline' as const, color: '#E8F3FF' },
  { id: 'beauty', name: 'Beauty', icon: 'sparkles-outline' as const, color: '#FFE7F0' },
  { id: 'services', name: 'Services', icon: 'construct-outline' as const, color: '#ECECEC' },
];

const CATEGORY_DESTINATIONS: Record<(typeof categories)[number]['id'], Screen> = {
  restaurants: 'food',
  grocery: 'groceries',
  pharmacy: 'pharmacyHome',
  electronics: 'electronicsHome',
  fashion: 'fashionHome',
  home: 'homeShoppingHome',
  beauty: 'beautyHome',
  services: 'serviceMarketplace',
};

const demoProducts = [
  { id: 'fresh-basket', name: 'Fresh family basket', meta: 'Groceries · 12 essentials', price: 48500, icon: 'basket-outline' as const },
  { id: 'wellness-pack', name: 'Daily wellness pack', meta: 'Pharmacy · Vitamins', price: 32000, icon: 'medical-outline' as const },
  { id: 'power-bank', name: '20,000mAh power bank', meta: 'Electronics · Fast charge', price: 89000, icon: 'battery-charging-outline' as const },
  { id: 'family-pizza', name: 'Family pizza selection', meta: 'Food · Serves 4', price: 42000, icon: 'pizza-outline' as const },
];

// V4.1 reference listings deliberately carry no synthetic rating, ETA, delivery fee or offer.
// Live commercial metadata must come from the market/store integration before it is rendered.
const stores = [
  { id: 'capital', name: 'Capital Shoppers', type: 'Groceries', icon: 'cart-outline' as const },
  { id: 'goodlife', name: 'Goodlife Pharmacy', type: 'Pharmacy', icon: 'medical-outline' as const },
  { id: 'jumia', name: 'Jumia Marketplace', type: 'Shopping', icon: 'bag-handle-outline' as const },
  { id: 'javas', name: 'Cafe Javas', type: 'Restaurant', icon: 'restaurant-outline' as const },
];

const referenceMerchantMeta = (store: typeof stores[number]) => `${store.type} · Reference listing`;

function V41SearchBar({ placeholder, onPress }: { placeholder: string; onPress?: () => void }) {
  return <Pressable onPress={onPress} style={styles.search}><Feather name="search" size={19} color={COLORS.muted}/><Text style={styles.searchText}>{placeholder}</Text><Ionicons name="options-outline" size={20} color={COLORS.black}/></Pressable>;
}

function V41Chip({ label, active, onPress }: { label: string; active?: boolean; onPress?: () => void }) {
  return <Pressable onPress={onPress} style={[styles.chip, active && styles.chipActive]}><Text style={[styles.chipText, active && styles.chipTextActive]}>{label}</Text></Pressable>;
}

function ProductCard({ product, country, onPress }: { product: typeof demoProducts[number]; country: string; onPress: () => void }) {
  return <Pressable onPress={onPress} style={styles.productCard}><View style={styles.productVisual}><Ionicons name={product.icon} size={35} color={COLORS.black}/></View><Text numberOfLines={2} style={styles.productName}>{product.name}</Text><Text style={styles.productMeta}>{product.meta}</Text><View style={styles.productBottom}><Text style={styles.productPrice}>{formatMoney(country, product.price)}</Text><View style={styles.addButton}><Feather name="plus" size={18} color={COLORS.white}/></View></View></Pressable>;
}

function StoreCard({ store, onPress }: { store: typeof stores[number]; onPress: () => void }) {
  return <Pressable onPress={onPress} style={styles.storeCard}><View style={styles.storeLogo}><Ionicons name={store.icon} size={30} color={COLORS.black}/></View><View style={styles.flex}><Text style={styles.storeName}>{store.name}</Text><Text style={styles.storeMeta}>{referenceMerchantMeta(store)}</Text><Text style={styles.storeMeta}>Open to check current availability</Text></View><Feather name="chevron-right" size={21} color={COLORS.muted}/></Pressable>;
}

export function CategoriesScreen({ data, actions }: { data: V41FrontendData; actions: V41FrontendActions }) {
  return <ScreenShell><ScrollView style={styles.flex} contentContainerStyle={{paddingBottom:34}} showsVerticalScrollIndicator={false}>
    <MarketplaceCategoryHeader location={`${data.city}, ${data.country}`} searchPlaceholder="Type to search..." onSearchPress={()=>actions.go('search')} onBack={()=>actions.go('home')} onMenu={()=>actions.go('allStores')} onLocation={()=>actions.go('locationPicker')}/>
    <View style={{paddingHorizontal:14}}>
      <MarketplacePromoBanner category="Shops" onPress={()=>actions.go('offers')}/>
      <MarketplaceRecommendedRail merchants={stores.map((store)=>({id:store.id,name:store.name,meta:referenceMerchantMeta(store),semantic:marketplaceSemanticForCategory(store.type)}))} onPress={(id)=>actions.go(id==='javas'?'food':'shops')}/>
      <MarketplaceCategoryGrid tiles={categories.map((item)=>({id:item.id,label:item.name,semantic:marketplaceSemanticForCategory(item.name)}))} onPress={(id)=>actions.go(CATEGORY_DESTINATIONS[id])}/>
      <MarketplacePromoGrid category="Shops" onPress={()=>actions.go('campaigns')}/>
      <MarketplaceMembershipStrip onPress={()=>actions.go('plusManage')}/>
    </View>
  </ScrollView></ScreenShell>;
}

export function CategoryItemsScreen({ data, actions }: { data: V41FrontendData; actions: V41FrontendActions }) {
  const [filter,setFilter]=useState('Popular');
  return <ScreenShell><ScrollView style={styles.flex} contentContainerStyle={{paddingBottom:34}} showsVerticalScrollIndicator={false}>
    <MarketplaceCategoryHeader location={`${data.city}, ${data.country}`} searchPlaceholder="Search this category..." onSearchPress={()=>actions.go('search')} onBack={()=>actions.go('categories')} onMenu={()=>actions.go('categories')} onLocation={()=>actions.go('locationPicker')}/>
    <View style={{paddingHorizontal:14}}>
      <MarketplacePromoBanner category="Groceries" onPress={()=>setFilter('Offers')}/>
      <MarketplaceRecommendedRail title="Recommended Shops" merchants={stores.map((store)=>({id:store.id,name:store.name,meta:referenceMerchantMeta(store),semantic:marketplaceSemanticForCategory(store.type)}))} onPress={()=>actions.go('shops')}/>
      <MarketplaceCategoryGrid tiles={categories.map((item)=>({id:item.id,label:item.name,semantic:marketplaceSemanticForCategory(item.name)}))} selectedId="grocery" onPress={()=>actions.go('categoryItems')}/>
      <MarketplacePromoGrid category="Groceries" onPress={()=>setFilter('Offers')}/>
      <ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={styles.chipRow}>{['Popular','Explore','New'].map(x=><V41Chip key={x} label={x} active={filter===x} onPress={()=>setFilter(x)}/>)}</ScrollView>
      <SectionTitle title="Popular products"/>
      <View style={styles.productGrid}>{demoProducts.map(p=><ProductCard key={p.id} product={p} country={data.country} onPress={()=>actions.go('shops')}/>)}</View>
      <MarketplaceMembershipStrip onPress={()=>actions.go('plusManage')}/>
    </View>
  </ScrollView></ScreenShell>;
}

export function BrandsScreen({ data, actions }: { data: V41FrontendData; actions: V41FrontendActions }) {
  const brands=[['Capital Shoppers','Groceries'],['Goodlife','Pharmacy'],['Jumia','Marketplace'],['Cafe Javas','Food'],['Pizza Inn','Food'],['Kareebu Local','Shops']];
  return <ScreenShell><ScrollView style={styles.flex} contentContainerStyle={{paddingBottom:34}} showsVerticalScrollIndicator={false}>
    <MarketplaceCategoryHeader location={`${data.city}, ${data.country}`} searchPlaceholder="Search brands..." onSearchPress={()=>actions.go('search')} onBack={()=>actions.go('home')} onMenu={()=>actions.go('categories')} onLocation={()=>actions.go('locationPicker')}/>
    <View style={{paddingHorizontal:14}}>
      <MarketplacePromoBanner category="Brands" onPress={()=>actions.go('offers')}/>
      <MarketplaceRecommendedRail title="Recommended brands" merchants={brands.map(([name,type],index)=>({id:String(index),name,semantic:marketplaceSemanticForCategory(type),meta:'Popular on Kareebu+'}))} onPress={()=>actions.go('brandItems')}/>
      <MarketplaceCategoryGrid tiles={categories.map((item)=>({id:item.id,label:item.name,semantic:marketplaceSemanticForCategory(item.name)}))} onPress={()=>actions.go('categoryItems')}/>
      <MarketplacePromoGrid category="Shops" onPress={()=>actions.go('campaigns')}/>
      <MarketplaceMembershipStrip onPress={()=>actions.go('plusManage')}/>
    </View>
  </ScrollView></ScreenShell>;
}

export function BrandItemsScreen({ data, actions }: { data: V41FrontendData; actions: V41FrontendActions }) {
  return <ScreenShell><ScrollView style={styles.flex} contentContainerStyle={{paddingBottom:34}} showsVerticalScrollIndicator={false}>
    <MarketplaceCategoryHeader location={`${data.city}, ${data.country}`} searchPlaceholder="Search Goodlife Pharmacy..." onSearchPress={()=>actions.go('search')} onBack={()=>actions.go('brands')} onMenu={()=>actions.go('categories')} onLocation={()=>actions.go('locationPicker')}/>
    <View style={{paddingHorizontal:14}}>
      <MarketplacePromoBanner category="Pharmacy" onPress={()=>actions.go('offers')}/>
      <MarketplaceRecommendedRail title="Recommended in health" merchants={stores.map((store)=>({id:store.id,name:store.name,meta:referenceMerchantMeta(store),semantic:marketplaceSemanticForCategory(store.type)}))} onPress={()=>actions.go('shops')}/>
      <MarketplaceCategoryGrid tiles={categories.map((item)=>({id:item.id,label:item.name,semantic:marketplaceSemanticForCategory(item.name)}))} selectedId="pharmacy" onPress={()=>actions.go('categoryItems')}/>
      <MarketplacePromoGrid category="Pharmacy" onPress={()=>actions.go('campaigns')}/>
      <SectionTitle title="Featured products"/>
      <View style={styles.productGrid}>{demoProducts.filter(p=>p.id==='wellness-pack').concat(demoProducts.slice(0,3)).map((p,i)=><ProductCard key={`${p.id}-${i}`} product={p} country={data.country} onPress={()=>actions.go('shops')}/>)}</View>
      <MarketplaceMembershipStrip onPress={()=>actions.go('plusManage')}/>
    </View>
  </ScrollView></ScreenShell>;
}

export function CampaignsScreen({ data, actions }: { data: V41FrontendData; actions: V41FrontendActions }) {
  const campaigns=[
    {title:'Weekend discovery',body:'Browse groceries and household reference listings around your market.',tone:COLORS.yellow,icon:'basket-outline'},
    {title:'Health & wellness',body:'Explore pharmacy and wellness categories without assuming a live promotion.',tone:'#DFF5E8',icon:'medical-outline'},
    {title:'Food discovery',body:`Browse restaurant reference listings around ${data.city} and confirm live details before ordering.`,tone:'#FFE2DC',icon:'restaurant-outline'},
  ];
  return <ScreenShell><Header title="Campaigns" onBack={()=>actions.go('home')}/><ScrollView style={styles.flex} contentContainerStyle={styles.scroll}>{campaigns.map((c)=><Pressable key={c.title} onPress={()=>actions.go('campaignDetails')} style={[styles.campaignCard,{backgroundColor:c.tone}]}><View style={styles.campaignIcon}><Ionicons name={c.icon as any} size={32}/></View><View style={styles.flex}><Text style={styles.campaignTitle}>{c.title}</Text><Text style={styles.campaignBody}>{c.body}</Text><Text style={styles.campaignLink}>Explore →</Text></View></Pressable>)}</ScrollView></ScreenShell>;
}

export function CampaignDetailsScreen({ data, actions }: { data: V41FrontendData; actions: V41FrontendActions }) {
  return <ScreenShell><Header title="Weekend discovery" onBack={()=>actions.go('campaigns')}/><ScrollView style={styles.flex} contentContainerStyle={styles.scroll}><View style={[styles.bigCampaign,{backgroundColor:COLORS.yellow}]}><Text style={styles.heroEyebrow}>DISCOVERY</Text><Text style={styles.bigCampaignTitle}>Explore weekend picks</Text><Text style={styles.heroBody}>Reference groceries, restaurants and local stores around {data.city}. Live commercial terms appear only when supplied by configured campaign data.</Text><Ionicons name="compass-outline" size={62}/></View><SectionTitle title="Discovery picks"/><View style={styles.productGrid}>{demoProducts.map(p=><ProductCard key={p.id} product={p} country={data.country} onPress={()=>actions.go('shops')}/>)}</View></ScrollView></ScreenShell>;
}

export function FlashSaleScreen({ data, actions }: { data: V41FrontendData; actions: V41FrontendActions }) {
  const [tab,setTab]=useState('Featured');
  return <ScreenShell><Header title="Discover now" onBack={()=>actions.go('home')}/><ScrollView style={styles.flex} contentContainerStyle={styles.scroll}><View style={styles.flashHero}><Image source={uiAssets.flash} style={styles.flashImage} resizeMode="contain"/><View style={styles.flex}><Text style={styles.flashTitle}>Discover now</Text><Text style={styles.flashBody}>Browse current catalogue ideas. Live pricing is confirmed in the seller flow.</Text></View></View><View style={styles.segment}>{['Featured','More'].map(x=><Pressable key={x} onPress={()=>setTab(x)} style={[styles.segmentButton,tab===x&&styles.segmentActive]}><Text style={[styles.segmentText,tab===x&&styles.segmentTextActive]}>{x}</Text></Pressable>)}</View><View style={styles.productGrid}>{demoProducts.map(p=><ProductCard key={p.id} product={p} country={data.country} onPress={()=>actions.go('shops')}/>)}</View></ScrollView></ScreenShell>;
}

export function OffersScreen({ data, actions }: { data: V41FrontendData; actions: V41FrontendActions }) {
  return <ScreenShell><Header title="Offers" onBack={()=>actions.go('home')}/><ScrollView style={styles.flex} contentContainerStyle={[styles.scroll,styles.fullCenter]}><Image source={uiAssets.noCoupon} style={styles.systemAsset} resizeMode="contain"/><Text style={styles.bigTitle}>No configured offers right now</Text><Text style={[styles.heroBody,{textAlign:'center'}]}>Kareebu will only show a discount, voucher or free-delivery benefit here when it comes from configured campaign data for {data.city}.</Text><PrimaryButton label="Explore stores" onPress={()=>actions.go('shops')}/></ScrollView></ScreenShell>;
}

export function AllStoresScreen({ data, actions }: { data: V41FrontendData; actions: V41FrontendActions }) {
  const [filter,setFilter]=useState('All');
  const visible=stores.filter(s=>filter==='All'||s.type.toLowerCase().includes(filter.toLowerCase())||(filter==='Food'&&s.type==='Restaurant'));
  return <ScreenShell><ScrollView style={styles.flex} contentContainerStyle={{paddingBottom:34}} showsVerticalScrollIndicator={false}>
    <MarketplaceCategoryHeader location={`${data.city}, ${data.country}`} searchPlaceholder="Search stores and restaurants..." onSearchPress={()=>actions.go('search')} onBack={()=>actions.go('home')} onMenu={()=>actions.go('categories')} onLocation={()=>actions.go('locationPicker')}/>
    <View style={{paddingHorizontal:14}}>
      <MarketplacePromoBanner category={filter==='All'?'Shops':filter} onPress={()=>actions.go('offers')}/>
      <MarketplaceRecommendedRail title="Recommended Shops" merchants={stores.map((store)=>({id:store.id,name:store.name,meta:referenceMerchantMeta(store),semantic:marketplaceSemanticForCategory(store.type)}))} onPress={(id)=>{const store=stores.find(s=>s.id===id);actions.go(store?.type==='Restaurant'?'food':'shops')}}/>
      <MarketplaceCategoryGrid tiles={categories.map((item)=>({id:item.id,label:item.name,semantic:marketplaceSemanticForCategory(item.name)}))} onPress={()=>actions.go('categoryItems')}/>
      <MarketplacePromoGrid category={filter==='All'?'Shops':filter} onPress={()=>actions.go('campaigns')}/>
      <ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={styles.chipRow}>{['All','Food','Grocery','Pharmacy','Shopping'].map(x=><V41Chip key={x} label={x} active={filter===x} onPress={()=>setFilter(x)}/>)}</ScrollView>
      <View style={styles.storeList}>{visible.map(s=><StoreCard key={s.id} store={s} onPress={()=>actions.go(s.type==='Restaurant'?'food':'shops')}/>)}</View>
      <MarketplaceMembershipStrip onPress={()=>actions.go('plusManage')}/>
    </View>
  </ScrollView></ScreenShell>;
}

export function ItemViewAllScreen({ data, actions }: { data: V41FrontendData; actions: V41FrontendActions }) {
  const [sort,setSort]=useState('Recommended');
  return <ScreenShell><ScrollView style={styles.flex} contentContainerStyle={{paddingBottom:34}} showsVerticalScrollIndicator={false}>
    <MarketplaceCategoryHeader location={`${data.city}, ${data.country}`} searchPlaceholder="Search products..." onSearchPress={()=>actions.go('search')} onBack={()=>actions.go('home')} onMenu={()=>actions.go('categories')} onLocation={()=>actions.go('locationPicker')}/>
    <View style={{paddingHorizontal:14}}>
      <MarketplacePromoBanner category="Shops" onPress={()=>actions.go('offers')}/>
      <MarketplaceRecommendedRail merchants={stores.map((store)=>({id:store.id,name:store.name,meta:referenceMerchantMeta(store),semantic:marketplaceSemanticForCategory(store.type)}))} onPress={()=>actions.go('shops')}/>
      <MarketplaceCategoryGrid tiles={categories.map((item)=>({id:item.id,label:item.name,semantic:marketplaceSemanticForCategory(item.name)}))} onPress={()=>actions.go('categoryItems')}/>
      <MarketplacePromoGrid category="Shops" onPress={()=>actions.go('campaigns')}/>
      <View style={styles.rowBetween}><Text style={styles.resultCount}>48 items</Text><Pressable onPress={()=>setSort(sort==='Recommended'?'Price: low to high':'Recommended')} style={styles.sortButton}><Ionicons name="swap-vertical-outline" size={17}/><Text style={styles.sortText}>{sort}</Text></Pressable></View>
      <View style={styles.productGrid}>{[...demoProducts,...demoProducts].map((p,i)=><ProductCard key={`${p.id}-${i}`} product={p} country={data.country} onPress={()=>actions.go('shops')}/>)}</View>
      <MarketplaceMembershipStrip onPress={()=>actions.go('plusManage')}/>
    </View>
  </ScrollView></ScreenShell>;
}

export function SearchFiltersScreen({ actions }: { data: V41FrontendData; actions: V41FrontendActions }) {
  const [sort,setSort]=useState('Recommended'); const [rating,setRating]=useState('Any'); const [delivery,setDelivery]=useState('Any');
  return <ScreenShell><Header title="Filters" onBack={()=>actions.go('search')}/><ScrollView style={styles.flex} contentContainerStyle={styles.scroll}><FilterSection title="Sort by" values={['Recommended','Price: low to high']} value={sort} setValue={setSort}/><FilterSection title="Listing type" values={['Any','Stores','Products','Categories']} value={rating} setValue={setRating}/><FilterSection title="Availability" values={['Any','Check in seller flow']} value={delivery} setValue={setDelivery}/><PrimaryButton label="Show results" onPress={()=>actions.go('search')}/></ScrollView></ScreenShell>;
}
function FilterSection({title,values,value,setValue}:{title:string;values:string[];value:string;setValue:(x:string)=>void}){return <View><SectionTitle title={title}/><RoundedCard style={styles.filterCard}>{values.map(x=><Pressable key={x} onPress={()=>setValue(x)} style={styles.filterRow}><View style={[styles.radio,value===x&&styles.radioActive]}>{value===x?<View style={styles.radioDot}/>:null}</View><Text style={styles.filterText}>{x}</Text></Pressable>)}</RoundedCard></View>}

export function AddressesScreen({ data, actions }: { data: V41FrontendData; actions: V41FrontendActions }) {
  const addresses=[{label:'Home',value:`Kololo, ${data.city}`,icon:'home-outline'},{label:'Work',value:`Nakasero, ${data.city}`,icon:'briefcase-outline'}];
  return <ScreenShell><Header title="My addresses" onBack={()=>actions.go('account')} right={<Pressable onPress={()=>actions.go('addAddress')}><Feather name="plus" size={24}/></Pressable>}/><ScrollView style={styles.flex} contentContainerStyle={styles.scroll}>{addresses.map(a=><RoundedCard key={a.label} style={styles.addressCard}><View style={styles.addressIcon}><Ionicons name={a.icon as any} size={22}/></View><View style={styles.flex}><Text style={styles.addressTitle}>{a.label}</Text><Text style={styles.addressBody}>{a.value}</Text></View><Feather name="edit-2" size={18} color={COLORS.muted}/></RoundedCard>)}<Pressable onPress={()=>actions.go('addAddress')} style={styles.addAddress}><Feather name="plus-circle" size={23} color={COLORS.red}/><Text style={styles.addAddressText}>Add a new address</Text></Pressable></ScrollView></ScreenShell>;
}

export function AddAddressScreen({ data, actions }: { data: V41FrontendData; actions: V41FrontendActions }) {
  const [label,setLabel]=useState('Home'); const [address,setAddress]=useState(''); const [details,setDetails]=useState('');
  return <ScreenShell><Header title="Add address" onBack={()=>actions.go('addresses')}/><ScrollView style={styles.flex} contentContainerStyle={styles.scroll}><View style={styles.mapMock}><Ionicons name="map-outline" size={46} color={COLORS.muted}/><View style={styles.mapPin}><Ionicons name="location" size={24} color={COLORS.red}/></View><Text style={styles.mapText}>{data.city}, {data.country}</Text></View><TextInput value={address} onChangeText={setAddress} placeholder="Search or enter address" placeholderTextColor={COLORS.muted} style={styles.input}/><View style={styles.chipWrap}>{['Home','Work','Other'].map(x=><V41Chip key={x} label={x} active={label===x} onPress={()=>setLabel(x)}/>)}</View><TextInput value={details} onChangeText={setDetails} placeholder="Apartment, floor, landmark or delivery note" placeholderTextColor={COLORS.muted} style={[styles.input,styles.multiline]} multiline/><PrimaryButton disabled={!address.trim()} label="Save address" onPress={()=>{Alert.alert('Address saved',`${label}: ${address}`);actions.go('addresses')}}/></ScrollView></ScreenShell>;
}

export function LanguageScreen({ actions }: { data: V41FrontendData; actions: V41FrontendActions }) {
  const [language,setLanguage]=useState('English'); const langs=['English','Swahili','Luganda','French'];
  return <ScreenShell><Header title="Language" onBack={()=>actions.go('settings')}/><ScrollView style={styles.flex} contentContainerStyle={styles.scroll}><View style={styles.languageHero}><Image source={uiAssets.language} style={styles.languageImage} resizeMode="contain"/><Text style={styles.heroTitle}>Choose your language</Text><Text style={styles.heroBody}>You can change this at any time.</Text></View><RoundedCard>{langs.map(x=><Pressable key={x} onPress={()=>setLanguage(x)} style={styles.languageRow}><Text style={styles.languageName}>{x}</Text><View style={[styles.radio,language===x&&styles.radioActive]}>{language===x?<View style={styles.radioDot}/>:null}</View></Pressable>)}</RoundedCard><PrimaryButton label="Apply language" onPress={()=>{Alert.alert('Language updated',language);actions.go('settings')}}/></ScrollView></ScreenShell>;
}

export function InterestsScreen({ actions }: { data: V41FrontendData; actions: V41FrontendActions }) {
  const all=['Food deals','Groceries','Health & wellness','Electronics','Fashion','Beauty','Local services','Ride offers','Family','Fitness']; const [selected,setSelected]=useState<string[]>(['Food deals','Groceries']);
  const toggle=(x:string)=>setSelected(v=>v.includes(x)?v.filter(i=>i!==x):[...v,x]);
  return <ScreenShell><Header title="Your interests" onBack={()=>actions.go('settings')}/><ScrollView style={styles.flex} contentContainerStyle={styles.scroll}><Text style={styles.bigTitle}>Make Kareebu+ feel more like you</Text><Text style={styles.heroBody}>Pick what you want to see more often on Home and Discover.</Text><View style={styles.interestGrid}>{all.map(x=><Pressable key={x} onPress={()=>toggle(x)} style={[styles.interestCard,selected.includes(x)&&styles.interestActive]}><Ionicons name={selected.includes(x)?'checkmark-circle':'add-circle-outline'} size={23} color={selected.includes(x)?COLORS.white:COLORS.black}/><Text style={[styles.interestText,selected.includes(x)&&styles.interestTextActive]}>{x}</Text></Pressable>)}</View><PrimaryButton label={`Save ${selected.length} interests`} onPress={()=>actions.go('settings')}/></ScrollView></ScreenShell>;
}

export function GuestTrackOrderScreen({ actions }: { data: V41FrontendData; actions: V41FrontendActions }) {
  const [orderId,setOrderId]=useState(''); const [phone,setPhone]=useState('');
  return <ScreenShell><Header title="Track an order" onBack={()=>actions.go('orders')}/><ScrollView style={styles.flex} contentContainerStyle={styles.scroll}><View style={styles.centerHero}><Image source={uiAssets.tracking} style={styles.heroAsset} resizeMode="contain"/><Text style={styles.heroTitle}>Track without signing in</Text><Text style={styles.heroBody}>Enter the order number and phone number used when placing the order.</Text></View><TextInput value={orderId} onChangeText={setOrderId} placeholder="Order ID" placeholderTextColor={COLORS.muted} style={styles.input}/><TextInput value={phone} onChangeText={setPhone} placeholder="Phone number" placeholderTextColor={COLORS.muted} keyboardType="phone-pad" style={styles.input}/><PrimaryButton disabled={!orderId||!phone} label="Track order" onPress={()=>actions.go('orderDetails')}/></ScrollView></ScreenShell>;
}

export function OrderDetailsScreen({ data, actions }: { data: V41FrontendData; actions: V41FrontendActions }) {
  const steps=[['Order placed','10:42 AM',true],['Confirmed','10:44 AM',true],['Preparing','10:51 AM',true],['Courier assigned','11:02 AM',false],['Delivered','—',false]];
  return <ScreenShell><Header title="Order #KRB-10482" onBack={()=>actions.go('orders')} right={<Pressable onPress={()=>actions.go('support')}><Ionicons name="help-circle-outline" size={24}/></Pressable>}/><ScrollView style={styles.flex} contentContainerStyle={styles.scroll}><RoundedCard style={styles.orderStatusCard}><View style={styles.orderStatusTop}><View><Text style={styles.heroEyebrow}>ESTIMATED DELIVERY</Text><Text style={styles.orderEta}>11:25–11:40 AM</Text></View><Image source={uiAssets.order} style={styles.orderAsset} resizeMode="contain"/></View><Text style={styles.orderStatus}>Preparing your order</Text></RoundedCard><SectionTitle title="Status"/><View style={styles.timeline}>{steps.map(([name,time,done],i)=><View key={String(name)} style={styles.timelineRow}><View style={styles.timelineRail}><View style={[styles.timelineDot,done&&styles.timelineDone]}>{done?<Feather name="check" size={12} color={COLORS.white}/>:null}</View>{i<steps.length-1?<View style={[styles.timelineLine,done&&styles.timelineLineDone]}/>:null}</View><View style={styles.timelineCopy}><Text style={styles.timelineTitle}>{name}</Text><Text style={styles.timelineMeta}>{time}</Text></View></View>)}</View><SectionTitle title="Order summary"/><RoundedCard style={styles.summaryCard}><SummaryRow label="2 × Chicken sandwich" value={formatMoney(data.country,26000)}/><SummaryRow label="1 × Fresh juice" value={formatMoney(data.country,8000)}/><SummaryRow label="Delivery" value={formatMoney(data.country,2500)}/><View style={styles.divider}/><SummaryRow label="Total" value={formatMoney(data.country,36500)} strong/></RoundedCard><PrimaryButton label="Track courier" onPress={()=>actions.go('orderTracking')}/><Pressable onPress={()=>actions.go('refunds')}><Text style={styles.centerAction}>Cancel or get help with this order</Text></Pressable></ScrollView></ScreenShell>;
}

export function MonthlyOrdersScreen({ data, actions }: { data: V41FrontendData; actions: V41FrontendActions }) {
  const [active,setActive]=useState(true);
  return <ScreenShell><Header title="Monthly orders" onBack={()=>actions.go('orders')}/><ScrollView style={styles.flex} contentContainerStyle={styles.scroll}><View style={styles.monthlyHero}><Ionicons name="calendar-outline" size={40}/><View style={styles.flex}><Text style={styles.heroTitle}>Repeat your essentials</Text><Text style={styles.heroBody}>Automatically prepare recurring grocery and household baskets.</Text></View></View><RoundedCard style={styles.monthlyCard}><View style={styles.rowBetween}><View><Text style={styles.orderStatus}>Family essentials</Text><Text style={styles.storeMeta}>Every 1st Saturday · 9:00 AM</Text></View><Pressable onPress={()=>setActive(!active)} style={[styles.toggle,active&&styles.toggleOn]}><View style={[styles.toggleDot,active&&styles.toggleDotOn]}/></Pressable></View><View style={styles.divider}/><SummaryRow label="Estimated basket" value={formatMoney(data.country,87500)}/><Text style={styles.monthlyNote}>8 items · Capital Shoppers</Text><Pressable onPress={()=>actions.go('shops')}><Text style={styles.actionText}>Edit items</Text></Pressable></RoundedCard><PrimaryButton label="Create another recurring order" onPress={()=>actions.go('shops')}/></ScrollView></ScreenShell>;
}

export function MyItemsScreen({ data, actions }: { data: V41FrontendData; actions: V41FrontendActions }) {
  return <ScreenShell><Header title="My items" onBack={()=>actions.go('orders')}/><ScrollView style={styles.flex} contentContainerStyle={styles.scroll}><Text style={styles.heroBody}>Items you order frequently are saved here for faster reordering.</Text><View style={styles.productGrid}>{demoProducts.map(p=><ProductCard key={p.id} product={p} country={data.country} onPress={()=>actions.go('shops')}/>)}</View></ScrollView></ScreenShell>;
}

export function PaymentMethodsScreen({ data, actions }: { data: V41FrontendData; actions: V41FrontendActions }) {
  const [selected,setSelected]=useState('mtn'); const methods=[['mtn','MTN Mobile Money','phone-portrait-outline'],['airtel','Airtel Money','phone-portrait-outline'],['card','Visa •••• 4242','card-outline'],['cash','Cash','cash-outline']];
  return <ScreenShell><Header title="Payment methods" onBack={()=>actions.go('wallet')}/><ScrollView style={styles.flex} contentContainerStyle={styles.scroll}><RoundedCard>{methods.map(([id,name,icon])=><Pressable key={id} onPress={()=>setSelected(id)} style={styles.paymentRow}><View style={styles.paymentIcon}><Ionicons name={icon as any} size={23}/></View><Text style={styles.paymentName}>{name}</Text><View style={[styles.radio,selected===id&&styles.radioActive]}>{selected===id?<View style={styles.radioDot}/>:null}</View></Pressable>)}</RoundedCard><Pressable onPress={()=>Alert.alert('Add payment method','Card and mobile-money linking will use the production payment provider.')} style={styles.addAddress}><Feather name="plus-circle" size={23} color={COLORS.red}/><Text style={styles.addAddressText}>Add payment method</Text></Pressable><RoundedCard><Pressable onPress={()=>actions.go('offlinePayment')} style={styles.paymentRow}><View style={styles.paymentIcon}><Ionicons name="document-text-outline" size={23}/></View><Text style={styles.paymentName}>Offline / bank payment</Text><Feather name="chevron-right" size={20}/></Pressable><Pressable onPress={()=>actions.go('paymentProcessing')} style={styles.paymentRow}><View style={styles.paymentIcon}><Ionicons name="shield-checkmark-outline" size={23}/></View><Text style={styles.paymentName}>Secure payment page</Text><Feather name="chevron-right" size={20}/></Pressable></RoundedCard><PrimaryButton label="Use selected method" onPress={()=>actions.go('wallet')}/></ScrollView></ScreenShell>;
}

export function PaymentFailedScreen({ actions }: { data: V41FrontendData; actions: V41FrontendActions }) {
  return <ScreenShell><ScrollView style={styles.flex} contentContainerStyle={[styles.scroll,styles.fullCenter]}><View style={styles.failedIcon}><Ionicons name="close" size={42} color={COLORS.white}/></View><Text style={styles.bigTitle}>Payment unsuccessful</Text><Text style={[styles.heroBody,{textAlign:'center'}]}>We couldn’t complete the payment. No completed charge has been recorded for this attempt.</Text><PrimaryButton label="Try another payment method" onPress={()=>actions.go('paymentMethods')}/><Pressable onPress={()=>actions.go('orders')}><Text style={styles.centerAction}>Back to orders</Text></Pressable></ScrollView></ScreenShell>;
}

export function SubscriptionPlansScreen({ data, actions }: { data: V41FrontendData; actions: V41FrontendActions }) {
  const [plan,setPlan]=useState('monthly');
  return <ScreenShell><Header title="Kareebu Black" onBack={()=>actions.go('membership')}/><ScrollView style={styles.flex} contentContainerStyle={styles.scroll}><View style={styles.proHero}><Image source={uiAssets.crown} style={styles.proCrown} resizeMode="contain"/><Text style={styles.proBrand}>Kareebu Black</Text><Text style={styles.proHeadline}>More value from the services you use every week.</Text></View><View style={styles.segment}>{['monthly','annual'].map(x=><Pressable key={x} onPress={()=>setPlan(x)} style={[styles.segmentButton,plan===x&&styles.segmentActive]}><Text style={[styles.segmentText,plan===x&&styles.segmentTextActive]}>{x==='monthly'?'Monthly':'Annual'}</Text></Pressable>)}</View><RoundedCard style={styles.planCard}><Text style={styles.planTitle}>{plan==='monthly'?'Monthly':'Annual'} membership</Text><Text style={styles.planPrice}>{plan==='monthly'?formatMoney(data.country,12000):formatMoney(data.country,120000)}</Text><Text style={styles.planMeta}>{plan==='monthly'?'per month':'per year · save 2 months'}</Text><View style={styles.benefits}><Benefit text="Reduced delivery fees on eligible orders"/><Benefit text="Priority matching on selected rides"/><Benefit text="Member-only coupons and cashback"/><Benefit text="Extra Kareebu Rewards earning"/></View></RoundedCard><PrimaryButton label="Continue to payment" onPress={()=>actions.go('subscriptionResult')}/><Text style={styles.termsText}>Subscription renews until cancelled. Benefits vary by market and eligible service.</Text></ScrollView></ScreenShell>;
}

export function SubscriptionResultScreen({ actions }: { data: V41FrontendData; actions: V41FrontendActions }) {
  return <ScreenShell><ScrollView style={styles.flex} contentContainerStyle={[styles.scroll,styles.fullCenter]}><View style={styles.successCircle}><Feather name="check" size={38} color={COLORS.black}/></View><Text style={styles.bigTitle}>Welcome to Kareebu Black</Text><Text style={[styles.heroBody,{textAlign:'center'}]}>Your membership benefits are ready to use across eligible Kareebu+ services.</Text><PrimaryButton label="Explore benefits" onPress={()=>actions.go('membership')}/><Pressable onPress={()=>actions.go('home')}><Text style={styles.centerAction}>Back to Home</Text></Pressable></ScrollView></ScreenShell>;
}

export function GroceryListScreen({ data, actions }: { data: V41FrontendData; actions: V41FrontendActions }) {
  const [items,setItems]=useState(['Milk','Bread','Eggs']); const [input,setInput]=useState('');
  const add=()=>{if(input.trim()){setItems([...items,input.trim()]);setInput('')}};
  return <ScreenShell><Header title="Grocery list" onBack={()=>actions.go('shops')}/><ScrollView style={styles.flex} contentContainerStyle={styles.scroll}><View style={styles.listHero}><Image source={uiAssets.groceryList} style={styles.listImage} resizeMode="contain"/><View style={styles.flex}><Text style={styles.heroTitle}>Build your basket faster</Text><Text style={styles.heroBody}>Add what you need and then shop the list across grocery stores.</Text></View></View><View style={styles.inlineInput}><TextInput value={input} onChangeText={setInput} placeholder="Add an item" placeholderTextColor={COLORS.muted} style={styles.inlineTextInput} onSubmitEditing={add}/><Pressable onPress={add} style={styles.addButtonLarge}><Feather name="plus" size={20} color={COLORS.white}/></Pressable></View><RoundedCard>{items.map((x,i)=><View key={`${x}-${i}`} style={styles.listRow}><View style={styles.checkCircle}/><Text style={styles.listText}>{x}</Text><Pressable onPress={()=>setItems(v=>v.filter((_,idx)=>idx!==i))}><Feather name="x" size={18} color={COLORS.muted}/></Pressable></View>)}</RoundedCard><PrimaryButton label={`Shop ${items.length} items`} onPress={()=>actions.go('shops')}/></ScrollView></ScreenShell>;
}

export function MedicineListScreen({ actions }: { data: V41FrontendData; actions: V41FrontendActions }) {
  const [note,setNote]=useState(''); const [attached,setAttached]=useState(false);
  return <ScreenShell><Header title="Medicine list" onBack={()=>actions.go('shops')}/><ScrollView style={styles.flex} contentContainerStyle={styles.scroll}><View style={styles.listHero}><Image source={uiAssets.prescription} style={styles.listImage} resizeMode="contain"/><View style={styles.flex}><Text style={styles.heroTitle}>Upload a prescription or medicine list</Text><Text style={styles.heroBody}>A pharmacy can review your request before checkout.</Text></View></View><Pressable onPress={()=>setAttached(true)} style={[styles.uploadBox,attached&&styles.uploadDone]}><Ionicons name={attached?'checkmark-circle':'cloud-upload-outline'} size={34} color={attached?COLORS.green:COLORS.black}/><Text style={styles.uploadTitle}>{attached?'Prescription attached':'Attach prescription'}</Text><Text style={styles.storeMeta}>JPG, PNG or PDF in the production flow</Text></Pressable><TextInput value={note} onChangeText={setNote} placeholder="Medicine names, dosage or pharmacist note" placeholderTextColor={COLORS.muted} style={[styles.input,styles.multiline]} multiline/><PrimaryButton disabled={!attached&&!note.trim()} label="Find a pharmacy" onPress={()=>actions.go('shops')}/></ScrollView></ScreenShell>;
}

export function RentalFavouritesScreen({ actions }: { data: V41FrontendData; actions: V41FrontendActions }) {
  const vehicles=[['Toyota RAV4','SUV · Automatic','UGX 140,000/day'],['Toyota Hiace','Van · 10 seats','UGX 220,000/day']];
  return <ScreenShell><Header title="Saved vehicles" onBack={()=>actions.go('rentals')}/><ScrollView style={styles.flex} contentContainerStyle={styles.scroll}>{vehicles.map(([name,meta,price])=><Pressable key={name} onPress={()=>actions.go('rentalVehicle')} style={styles.vehicleCard}><View style={styles.vehicleVisual}><Ionicons name="car-sport-outline" size={38}/></View><View style={styles.flex}><Text style={styles.storeName}>{name}</Text><Text style={styles.storeMeta}>{meta}</Text><Text style={styles.vehiclePrice}>{price}</Text></View><Ionicons name="heart" size={23} color={COLORS.red}/></Pressable>)}</ScrollView></ScreenShell>;
}

export function ProviderProfileScreen({ data, actions }: { data: V41FrontendData; actions: V41FrontendActions }) {
  return <ScreenShell><Header title="Provider" onBack={()=>actions.go('serviceProviders')}/><ScrollView style={styles.flex} contentContainerStyle={styles.scroll}><View style={styles.providerHero}><View style={styles.providerAvatar}><Text style={styles.providerInitial}>B</Text></View><Text style={styles.bigTitle}>BrightHome Services</Text><Text style={styles.storeMeta}>Verified provider · ★ 4.9 · 312 jobs</Text><View style={styles.providerStats}><Stat value="98%" label="On-time"/><Stat value="4.9" label="Rating"/><Stat value="4 yrs" label="Experience"/></View></View><SectionTitle title="About"/><Text style={styles.bodyCopy}>Professional home cleaning, deep cleaning and move-in services across {data.city}. Equipment and cleaning products can be included.</Text><SectionTitle title="Services"/><RoundedCard><ServiceLine title="Standard home cleaning" price={formatMoney(data.country,45000)}/><ServiceLine title="Deep cleaning" price={formatMoney(data.country,85000)}/><ServiceLine title="Move-in cleaning" price={formatMoney(data.country,120000)}/></RoundedCard><SectionTitle title="Recent reviews"/><RoundedCard style={styles.reviewCard}><Text style={styles.storeName}>★★★★★</Text><Text style={styles.bodyCopy}>“Arrived on time, very thorough and easy to communicate with.”</Text><Text style={styles.storeMeta}>Sarah · 2 weeks ago</Text></RoundedCard><PrimaryButton label="Book this provider" onPress={()=>actions.go('serviceCheckout')}/></ScrollView></ScreenShell>;
}

export function RideOffersScreen({ data, actions }: { data: V41FrontendData; actions: V41FrontendActions }) {
  return <ScreenShell><Header title="Ride offers" onBack={()=>actions.go('whereTo')}/><ScrollView style={styles.flex} contentContainerStyle={[styles.scroll,styles.fullCenter]}><View style={styles.rideOfferHero}><Ionicons name="ticket-outline" size={52}/><Text style={styles.heroTitle}>No configured ride offers</Text><Text style={[styles.heroBody,{textAlign:'center'}]}>Any ride discount shown here must come from an active campaign configured for {data.city}. Your normal fare estimate remains available in the booking flow.</Text></View><PrimaryButton label="Plan a ride" onPress={()=>actions.go('whereTo')}/></ScrollView></ScreenShell>;
}

export function LegalScreen({ actions }: { data: V41FrontendData; actions: V41FrontendActions }) {
  const [section,setSection]=useState('Terms');
  return <ScreenShell><Header title="Legal" onBack={()=>actions.go('settings')}/><ScrollView style={styles.flex} contentContainerStyle={styles.scroll}><View style={styles.segment}>{['Terms','Privacy','Refunds'].map(x=><Pressable key={x} onPress={()=>setSection(x)} style={[styles.segmentButton,section===x&&styles.segmentActive]}><Text style={[styles.segmentText,section===x&&styles.segmentTextActive]}>{x}</Text></Pressable>)}</View><Text style={styles.legalTitle}>{section}</Text><Text style={styles.legalText}>{section==='Terms'?'These screens provide the in-app legal-content surface used by the donor application. Production terms should be loaded from Kareebu’s approved legal documents and market-specific policies.':section==='Privacy'?'Kareebu should explain how account, location, order, trip and payment data are used, retained and protected. Production text belongs to the approved Kareebu privacy policy.':'Refund eligibility depends on service type, fulfilment state, payment method and local policy. The production app should display the applicable refund rules before submission.'}</Text><Text style={styles.legalText}>The interface supports long-form content, section navigation, readable typography and a clear route back to Settings.</Text></ScrollView></ScreenShell>;
}

export function UpdateScreen({ actions }: { data: V41FrontendData; actions: V41FrontendActions }) {
  return <ScreenShell><ScrollView style={styles.flex} contentContainerStyle={[styles.scroll,styles.fullCenter]}><Image source={uiAssets.update} style={styles.systemAsset} resizeMode="contain"/><Text style={styles.bigTitle}>A new Kareebu+ update is available</Text><Text style={[styles.heroBody,{textAlign:'center'}]}>Update to continue with the latest features, security improvements and service compatibility.</Text><PrimaryButton label="Update app" onPress={()=>Alert.alert('Update','The production Android build will open its store listing.')}/><Pressable onPress={()=>actions.go('home')}><Text style={styles.centerAction}>Remind me later</Text></Pressable></ScrollView></ScreenShell>;
}

export function NoInternetScreen({ actions }: { data: V41FrontendData; actions: V41FrontendActions }) {
  return <ScreenShell><ScrollView style={styles.flex} contentContainerStyle={[styles.scroll,styles.fullCenter]}><Image source={uiAssets.noInternet} style={styles.systemAsset} resizeMode="contain"/><Text style={styles.bigTitle}>You’re offline</Text><Text style={[styles.heroBody,{textAlign:'center'}]}>Check your connection and try again. Saved account and order information can remain available where supported.</Text><PrimaryButton label="Try again" onPress={()=>actions.go('home')}/></ScrollView></ScreenShell>;
}

export function QrScreen({ data, actions }: { data: V41FrontendData; actions: V41FrontendActions }) {
  return <ScreenShell><Header title="Kareebu QR" onBack={()=>actions.go('account')}/><ScrollView style={styles.flex} contentContainerStyle={styles.scroll}><View style={styles.qrHero}><Text style={styles.heroEyebrow}>YOUR KAREEBU ID</Text><View style={styles.qrBox}><Image source={uiAssets.qr} style={styles.qrImage} resizeMode="contain"/></View><Text style={styles.heroTitle}>{data.fullName || 'Kareebu member'}</Text><Text style={styles.heroBody}>Scan to identify your account at supported Kareebu experiences.</Text></View><RoundedCard style={styles.qrActions}><Pressable onPress={()=>Alert.alert('Share QR','The native share sheet will be used in production.')} style={styles.quickAction}><Ionicons name="share-social-outline" size={24}/><Text style={styles.quickActionText}>Share</Text></Pressable><Pressable onPress={()=>Alert.alert('Scan','Camera QR scanning will open here.')} style={styles.quickAction}><Ionicons name="scan-outline" size={24}/><Text style={styles.quickActionText}>Scan</Text></Pressable></RoundedCard></ScrollView></ScreenShell>;
}

export function PartnerRegistrationScreen({ actions }: { data: V41FrontendData; actions: V41FrontendActions }) {
  const [role,setRole]=useState('Store'); const [name,setName]=useState(''); const [phone,setPhone]=useState('');
  return <ScreenShell><Header title="Join Kareebu" onBack={()=>actions.go('account')}/><ScrollView style={styles.flex} contentContainerStyle={styles.scroll}><Text style={styles.bigTitle}>Earn with Kareebu</Text><Text style={styles.heroBody}>The donor app exposes store, rider and delivery-partner registration paths. Kareebu keeps those entry points available while the operational apps remain separate.</Text><View style={styles.roleGrid}>{['Store','Driver','Courier'].map(x=><Pressable key={x} onPress={()=>setRole(x)} style={[styles.roleCard,role===x&&styles.roleActive]}><Ionicons name={x==='Store'?'storefront-outline':x==='Driver'?'car-outline':'cube-outline'} size={28} color={role===x?COLORS.white:COLORS.black}/><Text style={[styles.roleText,role===x&&styles.roleTextActive]}>{x}</Text></Pressable>)}</View><TextInput value={name} onChangeText={setName} placeholder={`${role} name`} placeholderTextColor={COLORS.muted} style={styles.input}/><TextInput value={phone} onChangeText={setPhone} placeholder="Phone number" placeholderTextColor={COLORS.muted} style={styles.input} keyboardType="phone-pad"/><PrimaryButton disabled={!name||!phone} label={`Continue ${role.toLowerCase()} registration`} onPress={()=>Alert.alert('Registration started',`${role} onboarding will continue in the appropriate Kareebu operational flow.`)}/></ScrollView></ScreenShell>;
}


export function SignInScreen({ actions }: { data: V41FrontendData; actions: V41FrontendActions }) {
  const [identity,setIdentity]=useState(''); const [password,setPassword]=useState(''); const [show,setShow]=useState(false);
  return <ScreenShell><Header title="Sign in" onBack={()=>actions.go('welcome')}/><ScrollView keyboardShouldPersistTaps="handled" style={styles.flex} contentContainerStyle={styles.scroll}><View style={styles.authHero}><View style={styles.authMark}><Text style={styles.authMarkText}>K+</Text></View><Text style={styles.bigTitle}>Welcome back</Text><Text style={styles.heroBody}>Sign in to continue with your orders, wallet, saved addresses and rewards.</Text></View><TextInput value={identity} onChangeText={setIdentity} placeholder="Phone number or email" placeholderTextColor={COLORS.muted} autoCapitalize="none" style={styles.input}/><View style={styles.passwordWrap}><TextInput value={password} onChangeText={setPassword} placeholder="Password" placeholderTextColor={COLORS.muted} secureTextEntry={!show} style={styles.passwordInput}/><Pressable onPress={()=>setShow(!show)}><Ionicons name={show?'eye-off-outline':'eye-outline'} size={22} color={COLORS.muted}/></Pressable></View><Pressable onPress={()=>actions.go('forgotPassword')}><Text style={styles.rightAction}>Forgot password?</Text></Pressable><PrimaryButton disabled={!identity.trim()||!password} label="Sign in" onPress={()=>actions.go('home')}/><View style={styles.orRow}><View style={styles.orLine}/><Text style={styles.orText}>or</Text><View style={styles.orLine}/></View><Pressable onPress={()=>actions.go('phone')} style={styles.secondaryButton}><Ionicons name="chatbox-ellipses-outline" size={21}/><Text style={styles.secondaryButtonText}>Sign in with OTP</Text></Pressable><Pressable onPress={()=>actions.go('signUp')}><Text style={styles.centerAction}>New to Kareebu+? Create account</Text></Pressable></ScrollView></ScreenShell>;
}

export function SignUpScreen({ actions }: { data: V41FrontendData; actions: V41FrontendActions }) {
  const [name,setName]=useState(''); const [phone,setPhone]=useState(''); const [email,setEmail]=useState(''); const [password,setPassword]=useState(''); const [accepted,setAccepted]=useState(false);
  return <ScreenShell><Header title="Create account" onBack={()=>actions.go('signIn')}/><ScrollView keyboardShouldPersistTaps="handled" style={styles.flex} contentContainerStyle={styles.scroll}><Text style={styles.bigTitle}>Create your Kareebu+ account</Text><Text style={styles.heroBody}>One account for food, shopping, rides, parcels, services and payments.</Text><TextInput value={name} onChangeText={setName} placeholder="Full name" placeholderTextColor={COLORS.muted} style={styles.input}/><TextInput value={phone} onChangeText={setPhone} placeholder="Phone number" placeholderTextColor={COLORS.muted} keyboardType="phone-pad" style={styles.input}/><TextInput value={email} onChangeText={setEmail} placeholder="Email address" placeholderTextColor={COLORS.muted} keyboardType="email-address" autoCapitalize="none" style={styles.input}/><TextInput value={password} onChangeText={setPassword} placeholder="Create password" placeholderTextColor={COLORS.muted} secureTextEntry style={styles.input}/><Pressable onPress={()=>setAccepted(!accepted)} style={styles.termsRow}><View style={[styles.checkBox,accepted&&styles.checkBoxOn]}>{accepted?<Feather name="check" size={14} color={COLORS.white}/>:null}</View><Text style={styles.termsCopy}>I agree to the Kareebu terms, privacy policy and applicable service conditions.</Text></Pressable><PrimaryButton disabled={!name||!phone||!password||!accepted} label="Create account" onPress={()=>actions.go('verification')}/><Pressable onPress={()=>actions.go('signIn')}><Text style={styles.centerAction}>Already have an account? Sign in</Text></Pressable></ScrollView></ScreenShell>;
}

export function ForgotPasswordScreen({ actions }: { data: V41FrontendData; actions: V41FrontendActions }) {
  const [identity,setIdentity]=useState('');
  return <ScreenShell><Header title="Forgot password" onBack={()=>actions.go('signIn')}/><ScrollView style={styles.flex} contentContainerStyle={styles.scroll}><View style={styles.centerHero}><View style={styles.authIcon}><Ionicons name="key-outline" size={34}/></View><Text style={styles.heroTitle}>Reset your password</Text><Text style={styles.heroBody}>Enter the phone number or email attached to your Kareebu+ account.</Text></View><TextInput value={identity} onChangeText={setIdentity} placeholder="Phone number or email" placeholderTextColor={COLORS.muted} style={styles.input}/><PrimaryButton disabled={!identity.trim()} label="Send verification code" onPress={()=>actions.go('verification')}/></ScrollView></ScreenShell>;
}

export function VerificationScreen({ actions }: { data: V41FrontendData; actions: V41FrontendActions }) {
  const [code,setCode]=useState('');
  return <ScreenShell><Header title="Verification" onBack={()=>actions.go('forgotPassword')}/><ScrollView style={styles.flex} contentContainerStyle={styles.scroll}><View style={styles.centerHero}><View style={styles.authIcon}><Ionicons name="shield-checkmark-outline" size={34}/></View><Text style={styles.heroTitle}>Enter verification code</Text><Text style={styles.heroBody}>We sent a 6-digit code to your selected contact method.</Text></View><TextInput value={code} onChangeText={x=>setCode(x.replace(/\D/g,'').slice(0,6))} placeholder="000000" placeholderTextColor={COLORS.mutedLight} keyboardType="number-pad" style={styles.codeInput}/><Pressable onPress={()=>Alert.alert('Code sent','A new verification code has been requested.')}><Text style={styles.centerAction}>Resend code</Text></Pressable><PrimaryButton disabled={code.length!==6} label="Verify" onPress={()=>actions.go('resetPassword')}/></ScrollView></ScreenShell>;
}

export function ResetPasswordScreen({ actions }: { data: V41FrontendData; actions: V41FrontendActions }) {
  const [password,setPassword]=useState(''); const [confirm,setConfirm]=useState('');
  return <ScreenShell><Header title="New password" onBack={()=>actions.go('verification')}/><ScrollView style={styles.flex} contentContainerStyle={styles.scroll}><Text style={styles.bigTitle}>Create a new password</Text><Text style={styles.heroBody}>Use at least 8 characters and avoid reusing a password from another service.</Text><TextInput value={password} onChangeText={setPassword} placeholder="New password" placeholderTextColor={COLORS.muted} secureTextEntry style={styles.input}/><TextInput value={confirm} onChangeText={setConfirm} placeholder="Confirm password" placeholderTextColor={COLORS.muted} secureTextEntry style={styles.input}/><PrimaryButton disabled={password.length<8||password!==confirm} label="Save password" onPress={()=>{Alert.alert('Password changed','You can now sign in with your new password.');actions.go('signIn')}}/></ScrollView></ScreenShell>;
}

export function GlobalCartScreen({ data, actions }: { data: V41FrontendData; actions: V41FrontendActions }) {
  const [foodQty,setFoodQty]=useState(2); const [shopQty,setShopQty]=useState(1); const total=foodQty*13000+shopQty*32000;
  return <ScreenShell><Header title="Global cart" onBack={()=>actions.go('home')}/><ScrollView style={styles.flex} contentContainerStyle={styles.scroll}><Text style={styles.heroBody}>The donor app keeps carts from different stores visible together while checkout remains grouped by merchant.</Text><SectionTitle title="Cafe Javas"/><RoundedCard style={styles.globalCartGroup}><CartLine title="Chicken sandwich" meta="Regular" price={formatMoney(data.country,13000*foodQty)} qty={foodQty} setQty={setFoodQty}/><Pressable onPress={()=>actions.go('foodCheckout')} style={styles.cartCheckout}><Text style={styles.cartCheckoutText}>Checkout food order</Text><Feather name="arrow-right" size={17} color={COLORS.white}/></Pressable></RoundedCard><SectionTitle title="Goodlife Pharmacy"/><RoundedCard style={styles.globalCartGroup}><CartLine title="Daily wellness pack" meta="Standard pack" price={formatMoney(data.country,32000*shopQty)} qty={shopQty} setQty={setShopQty}/><Pressable onPress={()=>actions.go('commerceCheckout')} style={styles.cartCheckout}><Text style={styles.cartCheckoutText}>Checkout shop order</Text><Feather name="arrow-right" size={17} color={COLORS.white}/></Pressable></RoundedCard><RoundedCard style={styles.summaryCard}><SummaryRow label="Across carts" value={formatMoney(data.country,total)} strong/></RoundedCard></ScrollView></ScreenShell>;
}
function CartLine({title,meta,price,qty,setQty}:{title:string;meta:string;price:string;qty:number;setQty:(v:number)=>void}){return <View style={styles.cartLine}><View style={styles.cartLineIcon}><Ionicons name="bag-handle-outline" size={23}/></View><View style={styles.flex}><Text style={styles.storeName}>{title}</Text><Text style={styles.storeMeta}>{meta}</Text><Text style={styles.productPrice}>{price}</Text></View><View style={styles.qtyControl}><Pressable onPress={()=>setQty(Math.max(0,qty-1))}><Feather name="minus" size={16}/></Pressable><Text style={styles.qtyText}>{qty}</Text><Pressable onPress={()=>setQty(qty+1)}><Feather name="plus" size={16}/></Pressable></View></View>}

export function OfflinePaymentScreen({ data, actions }: { data: V41FrontendData; actions: V41FrontendActions }) {
  const [method,setMethod]=useState('Bank transfer'); const [reference,setReference]=useState('');
  return <ScreenShell><Header title="Offline payment" onBack={()=>actions.go('paymentMethods')}/><ScrollView style={styles.flex} contentContainerStyle={styles.scroll}><View style={styles.offlineHero}><Ionicons name="receipt-outline" size={40}/><View style={styles.flex}><Text style={styles.heroTitle}>Pay using an offline method</Text><Text style={styles.heroBody}>Submit your payment reference so the merchant can verify it.</Text></View></View><View style={styles.chipWrap}>{['Bank transfer','Agent deposit','Pay at counter'].map(x=><V41Chip key={x} label={x} active={method===x} onPress={()=>setMethod(x)}/>)}</View><RoundedCard style={styles.bankCard}><Text style={styles.heroEyebrow}>PAYMENT INSTRUCTIONS</Text><Text style={styles.storeName}>Kareebu settlement account</Text><Text style={styles.bodyCopy}>Use your order ID as the payment narration. Verification happens before fulfilment begins.</Text></RoundedCard><TextInput value={reference} onChangeText={setReference} placeholder="Payment reference / transaction ID" placeholderTextColor={COLORS.muted} style={styles.input}/><PrimaryButton disabled={!reference.trim()} label="Submit payment proof" onPress={()=>actions.go('orderDetails')}/></ScrollView></ScreenShell>;
}

export function PaymentProcessingScreen({ actions }: { data: V41FrontendData; actions: V41FrontendActions }) {
  const [processing,setProcessing]=useState(false);
  return <ScreenShell><Header title="Secure payment" onBack={()=>actions.go('paymentMethods')}/><ScrollView style={styles.flex} contentContainerStyle={styles.scroll}><View style={styles.webPayment}><View style={styles.webBar}><Ionicons name="lock-closed" size={16} color={COLORS.green}/><Text style={styles.webUrl}>secure.kareebu.pay</Text></View><View style={styles.webBody}><Ionicons name="card-outline" size={52}/><Text style={styles.heroTitle}>Complete your payment</Text><Text style={[styles.heroBody,{textAlign:'center'}]}>This represents the secure payment-webview surface used by the donor app for external gateways.</Text></View></View><PrimaryButton label={processing?'Processing…':'Authorise payment'} disabled={processing} onPress={()=>{setProcessing(true);setTimeout(()=>actions.go('commerceOrderSuccess'),650)}}/><Pressable onPress={()=>actions.go('paymentFailed')}><Text style={styles.centerAction}>Preview failed payment state</Text></Pressable></ScrollView></ScreenShell>;
}

export function RidePaymentScreen({ data, actions }: { data: V41FrontendData; actions: V41FrontendActions }) {
  const [method,setMethod]=useState('MTN Mobile Money'); const methods=['MTN Mobile Money','Airtel Money','Visa •••• 4242','Cash'];
  return <ScreenShell><Header title="Ride payment" onBack={()=>actions.go('confirmBooking')}/><ScrollView style={styles.flex} contentContainerStyle={styles.scroll}><RoundedCard style={styles.rideFareCard}><Text style={styles.heroEyebrow}>TRIP FARE</Text><Text style={styles.rideFareAmount}>{formatMoney(data.country,8500)}</Text><Text style={styles.storeMeta}>Final fare may change if the trip route or waiting time changes.</Text></RoundedCard><SectionTitle title="Choose payment method"/><RoundedCard>{methods.map(x=><Pressable key={x} onPress={()=>setMethod(x)} style={styles.paymentRow}><View style={styles.paymentIcon}><Ionicons name={x==='Cash'?'cash-outline':x.startsWith('Visa')?'card-outline':'phone-portrait-outline'} size={23}/></View><Text style={styles.paymentName}>{x}</Text><View style={[styles.radio,method===x&&styles.radioActive]}>{method===x?<View style={styles.radioDot}/>:null}</View></Pressable>)}</RoundedCard><PrimaryButton label="Confirm & request driver" onPress={()=>actions.go('driver')}/></ScrollView></ScreenShell>;
}

function SummaryRow({label,value,strong}:{label:string;value:string;strong?:boolean}){return <View style={styles.summaryRow}><Text style={[styles.summaryLabel,strong&&styles.summaryStrong]}>{label}</Text><Text style={[styles.summaryValue,strong&&styles.summaryStrong]}>{value}</Text></View>}
function Benefit({text}:{text:string}){return <View style={styles.benefit}><View style={styles.benefitCheck}><Feather name="check" size={13} color={COLORS.black}/></View><Text style={styles.benefitText}>{text}</Text></View>}
function Stat({value,label}:{value:string;label:string}){return <View style={styles.stat}><Text style={styles.statValue}>{value}</Text><Text style={styles.statLabel}>{label}</Text></View>}
function ServiceLine({title,price}:{title:string;price:string}){return <View style={styles.serviceLine}><Text style={styles.serviceTitle}>{title}</Text><Text style={styles.servicePrice}>{price}</Text></View>}

const styles=StyleSheet.create({
  flex:{flex:1},scroll:{paddingHorizontal:14,paddingTop:12,paddingBottom:38,gap:12},fullCenter:{flexGrow:1,justifyContent:'center',paddingHorizontal:18},rowBetween:{flexDirection:'row',alignItems:'center',justifyContent:'space-between',gap:12},
  search:{height:52,borderRadius:17,backgroundColor:'#F5F5F5',borderWidth:1,borderColor:COLORS.line,flexDirection:'row',alignItems:'center',gap:10,paddingHorizontal:14},searchText:{flex:1,...TYPE.body,color:COLORS.muted},
  chipRow:{gap:8,paddingRight:12},chipWrap:{flexDirection:'row',flexWrap:'wrap',gap:8},chip:{minHeight:38,borderRadius:20,borderWidth:1,borderColor:COLORS.line,paddingHorizontal:13,alignItems:'center',justifyContent:'center',backgroundColor:COLORS.white},chipActive:{backgroundColor:COLORS.black,borderColor:COLORS.black},chipText:{...TYPE.small,fontWeight:'800',color:COLORS.black},chipTextActive:{color:COLORS.white},
  categoryGrid:{flexDirection:'row',flexWrap:'wrap',gap:12},categoryCard:{width:'47.8%',minHeight:142,borderWidth:1,borderColor:COLORS.line,borderRadius:21,padding:14,justifyContent:'space-between',backgroundColor:COLORS.white,...SHADOW},categoryIcon:{width:58,height:58,borderRadius:18,alignItems:'center',justifyContent:'center'},categoryName:{...TYPE.cardTitle,fontFamily:FONT.bold,fontWeight:'900'},categoryHero:{minHeight:132,borderRadius:23,backgroundColor:'#FFF6D8',padding:18,flexDirection:'row',alignItems:'center',gap:12},heroEyebrow:{...TYPE.caption,fontFamily:FONT.bold,fontWeight:'900',letterSpacing:1.3,color:COLORS.red},heroTitle:{fontFamily:FONT.bold,fontSize:22,lineHeight:27,fontWeight:'900',color:COLORS.black},heroBody:{...TYPE.body,color:COLORS.muted,lineHeight:21,marginTop:4},bigTitle:{fontFamily:FONT.bold,fontSize:29,lineHeight:34,fontWeight:'900',color:COLORS.black},
  storeList:{gap:10},storeCard:{minHeight:84,borderRadius:18,borderWidth:1,borderColor:COLORS.line,backgroundColor:COLORS.white,padding:12,flexDirection:'row',alignItems:'center',gap:12,...SHADOW},storeLogo:{width:54,height:54,borderRadius:16,backgroundColor:'#F6F6F6',alignItems:'center',justifyContent:'center'},storeName:{...TYPE.cardTitle,fontFamily:FONT.bold,fontWeight:'900'},storeMeta:{...TYPE.small,color:COLORS.muted,marginTop:2},
  productGrid:{flexDirection:'row',flexWrap:'wrap',gap:11},productCard:{width:'48.2%',minHeight:226,borderWidth:1,borderColor:COLORS.line,borderRadius:19,backgroundColor:COLORS.white,padding:10,...SHADOW},productVisual:{height:96,borderRadius:15,backgroundColor:'#F6F6F6',alignItems:'center',justifyContent:'center',position:'relative'},badge:{position:'absolute',top:7,left:7,backgroundColor:COLORS.red,borderRadius:7,paddingHorizontal:7,paddingVertical:4},badgeText:{fontFamily:FONT.bold,fontSize:9,fontWeight:'900',color:COLORS.white},productName:{...TYPE.bodyStrong,fontFamily:FONT.bold,fontWeight:'900',marginTop:9},productMeta:{...TYPE.caption,color:COLORS.muted,marginTop:3},productBottom:{marginTop:'auto',paddingTop:8,flexDirection:'row',alignItems:'center',justifyContent:'space-between'},productPrice:{fontFamily:FONT.bold,fontSize:13,fontWeight:'900'},addButton:{width:31,height:31,borderRadius:10,backgroundColor:COLORS.red,alignItems:'center',justifyContent:'center'},
  brandGrid:{flexDirection:'row',flexWrap:'wrap',gap:12},brandCard:{width:'31%',minHeight:115,borderRadius:18,borderWidth:1,borderColor:COLORS.line,alignItems:'center',justifyContent:'center',gap:8,backgroundColor:COLORS.white},brandLogo:{width:58,height:58,borderRadius:29,backgroundColor:'#F7F7F7',alignItems:'center',justifyContent:'center'},brandName:{...TYPE.small,fontFamily:FONT.bold,fontWeight:'800',textAlign:'center'},brandHero:{minHeight:88,borderRadius:20,borderWidth:1,borderColor:COLORS.line,padding:14,flexDirection:'row',alignItems:'center',gap:12},brandHeroIcon:{width:58,height:58,borderRadius:17,backgroundColor:'#E6F7ED',alignItems:'center',justifyContent:'center'},
  campaignCard:{minHeight:145,borderRadius:23,padding:18,flexDirection:'row',gap:15,alignItems:'center'},campaignIcon:{width:62,height:62,borderRadius:18,backgroundColor:'rgba(255,255,255,.55)',alignItems:'center',justifyContent:'center'},campaignTitle:{fontFamily:FONT.bold,fontSize:21,fontWeight:'900'},campaignBody:{...TYPE.body,marginTop:5,lineHeight:20},campaignLink:{...TYPE.small,fontFamily:FONT.bold,fontWeight:'900',marginTop:9},bigCampaign:{minHeight:215,borderRadius:25,padding:21,justifyContent:'center',gap:8},bigCampaignTitle:{fontFamily:FONT.bold,fontSize:34,lineHeight:38,fontWeight:'900'},
  flashHero:{minHeight:112,borderRadius:22,backgroundColor:'#FFF1ED',padding:14,flexDirection:'row',alignItems:'center',gap:14},flashImage:{width:84,height:84},flashTitle:{fontFamily:FONT.bold,fontSize:26,fontWeight:'900',color:COLORS.red},flashBody:{...TYPE.small,color:COLORS.muted,marginTop:4},segment:{flexDirection:'row',backgroundColor:'#F2F2F2',borderRadius:14,padding:4},segmentButton:{flex:1,minHeight:42,borderRadius:11,alignItems:'center',justifyContent:'center'},segmentActive:{backgroundColor:COLORS.white,...SHADOW},segmentText:{...TYPE.small,fontWeight:'800',color:COLORS.muted},segmentTextActive:{color:COLORS.black},
  offerHero:{minHeight:145,borderRadius:23,backgroundColor:COLORS.black,padding:19,justifyContent:'center'},couponCard:{minHeight:92,padding:13,flexDirection:'row',alignItems:'center',gap:12,shadowOpacity:0},couponIcon:{width:52,height:52,borderRadius:15,backgroundColor:'#FFF3F0',alignItems:'center',justifyContent:'center'},smallAsset:{width:34,height:34},couponTitle:{...TYPE.cardTitle,fontFamily:FONT.bold,fontWeight:'900'},couponMeta:{...TYPE.small,color:COLORS.muted,marginTop:2},couponCode:{fontFamily:FONT.bold,fontSize:12,fontWeight:'900',color:COLORS.red,marginTop:5,letterSpacing:1},actionText:{...TYPE.action,color:COLORS.red,fontFamily:FONT.bold,fontWeight:'900'},resultCount:{...TYPE.bodyStrong},sortButton:{minHeight:38,borderWidth:1,borderColor:COLORS.line,borderRadius:19,paddingHorizontal:12,flexDirection:'row',alignItems:'center',gap:6},sortText:{...TYPE.small,fontWeight:'800'},
  filterCard:{shadowOpacity:0},filterRow:{minHeight:58,flexDirection:'row',alignItems:'center',gap:12,paddingHorizontal:14,borderBottomWidth:1,borderBottomColor:COLORS.line},filterText:{...TYPE.bodyStrong},radio:{width:22,height:22,borderRadius:11,borderWidth:2,borderColor:COLORS.lineDark,alignItems:'center',justifyContent:'center'},radioActive:{borderColor:COLORS.red},radioDot:{width:10,height:10,borderRadius:5,backgroundColor:COLORS.red},
  addressCard:{minHeight:78,padding:13,flexDirection:'row',alignItems:'center',gap:12,shadowOpacity:0},addressIcon:{width:46,height:46,borderRadius:14,backgroundColor:'#F5F5F5',alignItems:'center',justifyContent:'center'},addressTitle:{...TYPE.cardTitle,fontWeight:'900'},addressBody:{...TYPE.small,color:COLORS.muted,marginTop:3},addAddress:{minHeight:55,borderWidth:1,borderColor:COLORS.red,borderStyle:'dashed',borderRadius:17,flexDirection:'row',alignItems:'center',justifyContent:'center',gap:8},addAddressText:{...TYPE.bodyStrong,color:COLORS.red},mapMock:{height:190,borderRadius:23,backgroundColor:'#EEF2F5',alignItems:'center',justifyContent:'center',position:'relative'},mapPin:{position:'absolute',width:44,height:44,borderRadius:22,backgroundColor:COLORS.white,alignItems:'center',justifyContent:'center',...SHADOW},mapText:{position:'absolute',bottom:14,...TYPE.small,fontWeight:'800'},input:{minHeight:54,borderWidth:1,borderColor:COLORS.line,borderRadius:16,paddingHorizontal:14,fontFamily:FONT.regular,fontSize:15,color:COLORS.black},multiline:{minHeight:105,paddingTop:14,textAlignVertical:'top'},
  languageHero:{alignItems:'center',gap:6,paddingVertical:12},languageImage:{width:110,height:88},languageRow:{minHeight:62,flexDirection:'row',alignItems:'center',justifyContent:'space-between',paddingHorizontal:15,borderBottomWidth:1,borderBottomColor:COLORS.line},languageName:{...TYPE.bodyStrong},interestGrid:{flexDirection:'row',flexWrap:'wrap',gap:10},interestCard:{width:'48.3%',minHeight:74,borderWidth:1,borderColor:COLORS.line,borderRadius:18,padding:12,flexDirection:'row',alignItems:'center',gap:9},interestActive:{backgroundColor:COLORS.black,borderColor:COLORS.black},interestText:{...TYPE.small,fontWeight:'900',flex:1},interestTextActive:{color:COLORS.white},
  centerHero:{alignItems:'center',gap:8,paddingVertical:10},heroAsset:{width:150,height:125},orderStatusCard:{padding:16,shadowOpacity:0},orderStatusTop:{flexDirection:'row',alignItems:'center',justifyContent:'space-between'},orderEta:{fontFamily:FONT.bold,fontSize:24,fontWeight:'900',marginTop:3},orderAsset:{width:84,height:70},orderStatus:{...TYPE.cardTitle,fontFamily:FONT.bold,fontWeight:'900',marginTop:10},timeline:{gap:0},timelineRow:{minHeight:69,flexDirection:'row',gap:12},timelineRail:{alignItems:'center',width:24},timelineDot:{width:24,height:24,borderRadius:12,borderWidth:2,borderColor:COLORS.lineDark,alignItems:'center',justifyContent:'center'},timelineDone:{backgroundColor:COLORS.green,borderColor:COLORS.green},timelineLine:{width:2,flex:1,backgroundColor:COLORS.line},timelineLineDone:{backgroundColor:COLORS.green},timelineCopy:{paddingBottom:13},timelineTitle:{...TYPE.bodyStrong,fontWeight:'900'},timelineMeta:{...TYPE.small,color:COLORS.muted,marginTop:2},summaryCard:{padding:15,gap:10,shadowOpacity:0},summaryRow:{flexDirection:'row',alignItems:'center',justifyContent:'space-between',gap:12},summaryLabel:{...TYPE.body,color:COLORS.muted},summaryValue:{...TYPE.bodyStrong},summaryStrong:{fontFamily:FONT.bold,fontWeight:'900',color:COLORS.black},divider:{height:1,backgroundColor:COLORS.line},centerAction:{...TYPE.action,color:COLORS.red,textAlign:'center',paddingVertical:8},
  monthlyHero:{minHeight:112,borderRadius:22,backgroundColor:'#FFF6D8',padding:16,flexDirection:'row',alignItems:'center',gap:14},monthlyCard:{padding:15,gap:12,shadowOpacity:0},toggle:{width:48,height:27,borderRadius:14,backgroundColor:'#D7D7D7',padding:3},toggleOn:{backgroundColor:COLORS.green},toggleDot:{width:21,height:21,borderRadius:11,backgroundColor:COLORS.white},toggleDotOn:{marginLeft:21},monthlyNote:{...TYPE.small,color:COLORS.muted},
  paymentRow:{minHeight:72,flexDirection:'row',alignItems:'center',gap:12,paddingHorizontal:14,borderBottomWidth:1,borderBottomColor:COLORS.line},paymentIcon:{width:46,height:46,borderRadius:14,backgroundColor:'#F5F5F5',alignItems:'center',justifyContent:'center'},paymentName:{flex:1,...TYPE.bodyStrong,fontWeight:'900'},failedIcon:{width:82,height:82,borderRadius:41,backgroundColor:COLORS.red,alignItems:'center',justifyContent:'center'},successCircle:{width:82,height:82,borderRadius:41,backgroundColor:COLORS.yellow,alignItems:'center',justifyContent:'center'},
  proHero:{minHeight:220,borderRadius:25,backgroundColor:COLORS.black,padding:20,alignItems:'center',justifyContent:'center'},proCrown:{width:72,height:72},proBrand:{fontFamily:FONT.bold,fontSize:29,fontWeight:'900',color:COLORS.yellow,marginTop:8},proHeadline:{...TYPE.body,color:COLORS.white,textAlign:'center',marginTop:6},planCard:{padding:18,gap:5,shadowOpacity:0},planTitle:{...TYPE.cardTitle,fontWeight:'900'},planPrice:{fontFamily:FONT.bold,fontSize:30,fontWeight:'900',marginTop:5},planMeta:{...TYPE.small,color:COLORS.muted},benefits:{gap:10,marginTop:14},benefit:{flexDirection:'row',alignItems:'center',gap:9},benefitCheck:{width:24,height:24,borderRadius:12,backgroundColor:COLORS.yellow,alignItems:'center',justifyContent:'center'},benefitText:{...TYPE.body,flex:1},termsText:{...TYPE.caption,color:COLORS.muted,textAlign:'center',lineHeight:17},
  listHero:{minHeight:120,borderRadius:22,backgroundColor:'#F6F6F6',padding:14,flexDirection:'row',alignItems:'center',gap:14},listImage:{width:86,height:86},inlineInput:{height:55,borderWidth:1,borderColor:COLORS.line,borderRadius:16,paddingLeft:14,flexDirection:'row',alignItems:'center'},inlineTextInput:{flex:1,fontFamily:FONT.regular,fontSize:15},addButtonLarge:{width:43,height:43,borderRadius:13,backgroundColor:COLORS.red,alignItems:'center',justifyContent:'center',marginRight:5},listRow:{minHeight:58,flexDirection:'row',alignItems:'center',gap:11,paddingHorizontal:14,borderBottomWidth:1,borderBottomColor:COLORS.line},checkCircle:{width:21,height:21,borderRadius:11,borderWidth:2,borderColor:COLORS.lineDark},listText:{flex:1,...TYPE.bodyStrong},uploadBox:{minHeight:155,borderRadius:20,borderWidth:1.5,borderStyle:'dashed',borderColor:COLORS.lineDark,alignItems:'center',justifyContent:'center',gap:5},uploadDone:{borderColor:COLORS.green,backgroundColor:'#F3FBF6'},uploadTitle:{...TYPE.cardTitle,fontWeight:'900'},
  vehicleCard:{minHeight:110,borderWidth:1,borderColor:COLORS.line,borderRadius:19,padding:12,flexDirection:'row',alignItems:'center',gap:12},vehicleVisual:{width:76,height:76,borderRadius:18,backgroundColor:'#F4F4F4',alignItems:'center',justifyContent:'center'},vehiclePrice:{fontFamily:FONT.bold,fontSize:13,fontWeight:'900',marginTop:6},providerHero:{alignItems:'center',gap:6},providerAvatar:{width:88,height:88,borderRadius:44,backgroundColor:COLORS.black,alignItems:'center',justifyContent:'center'},providerInitial:{fontFamily:FONT.bold,fontSize:34,fontWeight:'900',color:COLORS.yellow},providerStats:{flexDirection:'row',gap:8,marginTop:12},stat:{minWidth:92,borderRadius:15,backgroundColor:'#F5F5F5',padding:10,alignItems:'center'},statValue:{fontFamily:FONT.bold,fontSize:17,fontWeight:'900'},statLabel:{...TYPE.caption,color:COLORS.muted,marginTop:2},bodyCopy:{...TYPE.body,color:COLORS.muted,lineHeight:22},serviceLine:{minHeight:58,paddingHorizontal:14,flexDirection:'row',alignItems:'center',justifyContent:'space-between',borderBottomWidth:1,borderBottomColor:COLORS.line},serviceTitle:{...TYPE.bodyStrong},servicePrice:{...TYPE.small,fontFamily:FONT.bold,fontWeight:'900',color:COLORS.red},reviewCard:{padding:15,gap:7,shadowOpacity:0},
  rideOfferHero:{minHeight:155,borderRadius:23,backgroundColor:'#FFF6D8',alignItems:'center',justifyContent:'center',gap:5},legalTitle:{fontFamily:FONT.bold,fontSize:26,fontWeight:'900'},legalText:{...TYPE.body,color:'#4D4D4D',lineHeight:24},systemAsset:{width:190,height:150},qrHero:{alignItems:'center',gap:7},qrBox:{width:220,height:220,borderRadius:28,borderWidth:1,borderColor:COLORS.line,backgroundColor:COLORS.white,alignItems:'center',justifyContent:'center',marginVertical:8},qrImage:{width:160,height:160},qrActions:{padding:12,flexDirection:'row',gap:10,shadowOpacity:0},quickAction:{flex:1,minHeight:72,borderRadius:16,backgroundColor:'#F5F5F5',alignItems:'center',justifyContent:'center',gap:5},quickActionText:{...TYPE.small,fontWeight:'900'},roleGrid:{flexDirection:'row',gap:9},roleCard:{flex:1,minHeight:92,borderWidth:1,borderColor:COLORS.line,borderRadius:18,alignItems:'center',justifyContent:'center',gap:6},roleActive:{backgroundColor:COLORS.black,borderColor:COLORS.black},roleText:{...TYPE.small,fontWeight:'900'},roleTextActive:{color:COLORS.white},
  authHero:{alignItems:'center',gap:6,paddingVertical:8},authMark:{width:74,height:74,borderRadius:22,backgroundColor:COLORS.black,alignItems:'center',justifyContent:'center'},authMarkText:{fontFamily:FONT.bold,fontSize:27,fontWeight:'900',color:COLORS.yellow},passwordWrap:{minHeight:54,borderWidth:1,borderColor:COLORS.line,borderRadius:16,paddingHorizontal:14,flexDirection:'row',alignItems:'center'},passwordInput:{flex:1,fontFamily:FONT.regular,fontSize:15,color:COLORS.black},rightAction:{...TYPE.action,color:COLORS.red,textAlign:'right'},orRow:{flexDirection:'row',alignItems:'center',gap:12},orLine:{height:1,flex:1,backgroundColor:COLORS.line},orText:{...TYPE.small,color:COLORS.muted},secondaryButton:{minHeight:54,borderWidth:1,borderColor:COLORS.line,borderRadius:17,flexDirection:'row',alignItems:'center',justifyContent:'center',gap:9},secondaryButtonText:{...TYPE.bodyStrong},termsRow:{flexDirection:'row',alignItems:'flex-start',gap:10},checkBox:{width:22,height:22,borderRadius:6,borderWidth:1.5,borderColor:COLORS.lineDark,alignItems:'center',justifyContent:'center',marginTop:1},checkBoxOn:{backgroundColor:COLORS.red,borderColor:COLORS.red},termsCopy:{...TYPE.small,color:COLORS.muted,flex:1,lineHeight:19},authIcon:{width:74,height:74,borderRadius:37,backgroundColor:COLORS.yellow,alignItems:'center',justifyContent:'center'},codeInput:{height:66,borderWidth:1,borderColor:COLORS.line,borderRadius:18,textAlign:'center',fontFamily:FONT.bold,fontSize:28,fontWeight:'900',letterSpacing:10},
  globalCartGroup:{padding:12,gap:10,shadowOpacity:0},cartLine:{minHeight:82,flexDirection:'row',alignItems:'center',gap:10},cartLineIcon:{width:48,height:48,borderRadius:14,backgroundColor:'#F5F5F5',alignItems:'center',justifyContent:'center'},qtyControl:{height:36,borderWidth:1,borderColor:COLORS.line,borderRadius:12,flexDirection:'row',alignItems:'center',gap:10,paddingHorizontal:8},qtyText:{fontFamily:FONT.bold,fontSize:13,fontWeight:'900'},cartCheckout:{height:46,borderRadius:14,backgroundColor:COLORS.black,flexDirection:'row',alignItems:'center',justifyContent:'center',gap:8},cartCheckoutText:{...TYPE.small,fontFamily:FONT.bold,fontWeight:'900',color:COLORS.white},offlineHero:{minHeight:122,borderRadius:22,backgroundColor:'#FFF6D8',padding:16,flexDirection:'row',alignItems:'center',gap:14},bankCard:{padding:16,gap:7,shadowOpacity:0},webPayment:{minHeight:330,borderWidth:1,borderColor:COLORS.line,borderRadius:22,overflow:'hidden',backgroundColor:COLORS.white},webBar:{height:48,backgroundColor:'#F5F5F5',flexDirection:'row',alignItems:'center',justifyContent:'center',gap:6},webUrl:{...TYPE.caption,color:COLORS.muted},webBody:{flex:1,alignItems:'center',justifyContent:'center',gap:9,padding:24},rideFareCard:{padding:18,gap:5,shadowOpacity:0},rideFareAmount:{fontFamily:FONT.bold,fontSize:34,fontWeight:'900'},
});
