export const assets = {
  mark: require('../assets/kareebu-plus/kareebu-plus-mark.png'),
  wordmark: require('../assets/kareebu-plus/kareebu-plus-wordmark.png'),
  promoVisual: require('../assets/kareebu-plus/kareebu-black-visual.png'),
  homeOffers: {
    glovo: require('../assets/kareebu-plus/home-offers/glovo.png'),
    carrefour: require('../assets/kareebu-plus/home-offers/carrefour.png'),
    goodlife: require('../assets/kareebu-plus/home-offers/goodlife.png'),
    jumia: require('../assets/kareebu-plus/home-offers/jumia.png'),
  },
  homeBrands: {
    carrefour: require('../assets/kareebu-plus/home-brands/carrefour.png'),
    jumia: require('../assets/kareebu-plus/home-brands/jumia.png'),
    glovo: require('../assets/kareebu-plus/home-brands/glovo.png'),
    goodlife: require('../assets/kareebu-plus/home-brands/goodlife.png'),
    pizzahut: require('../assets/kareebu-plus/home-brands/pizzahut.png'),
  },
  countries: {
    uganda: require('../assets/kareebu-plus/countries/uganda.png'),
    kenya: require('../assets/kareebu-plus/countries/kenya.png'),
    tanzania: require('../assets/kareebu-plus/countries/tanzania.png'),
  },
  countrySelection: {
    map: require('../assets/kareebu-plus/country-landmarks/map.jpg'),
    uganda: require('../assets/kareebu-plus/country-landmarks/uganda.jpg'),
    kenya: require('../assets/kareebu-plus/country-landmarks/kenya.jpg'),
    tanzania: require('../assets/kareebu-plus/country-landmarks/tanzania.jpg'),
  },
  ribbons: require('../assets/karibu/splash-ribbons.png'),
  flag: require('../assets/karibu/uganda-flag.png'),
  welcomeHero: require('../assets/karibu/premium/welcome-hero-premium.png'),
  // Global semantic 3D atlas. High-frequency product/category/action tiles
  // should resolve through this object instead of inventing a new icon style.
  service: {
    rides: require('../assets/kareebu-plus/services-3d/rides.png'),
    boda: require('../assets/kareebu-plus/services-3d/boda.png'),
    food: require('../assets/kareebu-plus/services-3d/food.png'),
    shops: require('../assets/kareebu-plus/services-3d/shops.png'),
    send: require('../assets/kareebu-plus/services-3d/send.png'),
    groceries: require('../assets/kareebu-plus/services-3d/groceries.png'),
    pay: require('../assets/kareebu-plus/services-3d/pay.png'),
    pharmacies: require('../assets/kareebu-plus/services-3d/pharmacies.png'),
    pharmacy: require('../assets/kareebu-plus/services-3d/pharmacy.png'),
    electronics: require('../assets/kareebu-plus/services-3d/electronics.png'),
    dineout: require('../assets/kareebu-plus/services-3d/dineout.png'),
    fix: require('../assets/kareebu-plus/services-3d/fix.png'),
    forGood: require('../assets/kareebu-plus/services-3d/for-good.png'),
    goOut: require('../assets/kareebu-plus/services-3d/go-out.png'),
    healthcare: require('../assets/kareebu-plus/services-3d/healthcare.png'),
    homeCare: require('../assets/kareebu-plus/services-3d/home-care.png'),
    homeServices: require('../assets/kareebu-plus/services-3d/home-services.png'),
    all: require('../assets/kareebu-plus/services-3d/more.png'),
  },
  maps: {
    where: require('../assets/karibu/premium/where-map-premium.png'),
    driver: require('../assets/karibu/maps/driver.png'),
    onTrip: require('../assets/karibu/maps/on-trip.png'),
  },
  food: {
    promo: require('../assets/karibu/food/promo.png'),
    cafeJavas: require('../assets/karibu/food/cafe-javas.png'),
    chickenTonight: require('../assets/karibu/food/chicken-tonight.png'),
    tamaraThai: require('../assets/karibu/food/tamara-thai.png'),
  },
  shops: {
    promo: require('../assets/karibu/shops/promo.png'),
    jumia: require('../assets/karibu/shops/jumia.png'),
    carrefour: require('../assets/karibu/shops/carrefour.png'),
    game: require('../assets/karibu/shops/game.png'),
    pharmacy: require('../assets/karibu/shops/pharmacy.png'),
  },
  payment: {
    mtn: require('../assets/karibu/payment/mtn.png'),
    airtel: require('../assets/karibu/payment/airtel.png'),
    visa: require('../assets/karibu/payment/visa.png'),
  },
  avatars: {
    driver: require('../assets/karibu/avatars/driver.png'),
    account: require('../assets/karibu/premium/account-avatar-premium.png'),
  },
  cities: {
    kampala: require('../assets/kareebu-plus/cities/kampala.png'),
    entebbe: require('../assets/kareebu-plus/cities/entebbe.png'),
    jinja: require('../assets/kareebu-plus/cities/jinja.png'),
    wakiso: require('../assets/kareebu-plus/cities/wakiso.png'),
    mbarara: require('../assets/kareebu-plus/cities/mbarara.png'),
    gulu: require('../assets/kareebu-plus/cities/gulu.png'),
  },
};
