export const assets = {
  mark: require('../assets/kareebu-plus/kareebu-plus-mark.png'),
  wordmark: require('../assets/kareebu-plus/kareebu-plus-wordmark.png'),
  promoVisual: require('../assets/kareebu-plus/kareebu-black-visual.png'),
  homeOffers: {
    glovo: require('../assets/kareebu-plus/home-offers/glovo.png'),
    carrefour: require('../assets/kareebu-plus/home-offers/carrefour.png'),
    goodlife: require('../assets/kareebu-plus/home-offers/goodlife.png'),
    jumia: require('../assets/kareebu-plus/home-offers/jumia.png'),
  },
  homeBrands: {
    carrefour: require('../assets/kareebu-plus/home-brands/carrefour.png'),
    jumia: require('../assets/kareebu-plus/home-brands/jumia.png'),
    glovo: require('../assets/kareebu-plus/home-brands/glovo.png'),
    goodlife: require('../assets/kareebu-plus/home-brands/goodlife.png'),
    pizzahut: require('../assets/kareebu-plus/home-brands/pizzahut.png'),
  },
  countries: {
    uganda: require('../assets/kareebu-plus/countries/uganda.png'),
    kenya: require('../assets/kareebu-plus/countries/kenya.png'),
    tanzania: require('../assets/kareebu-plus/countries/tanzania.png'),
  },
  countrySelection: {
    map: require('../assets/kareebu-plus/country-landmarks/map.jpg'),
    uganda: require('../assets/kareebu-plus/country-landmarks/uganda.jpg'),
    kenya: require('../assets/kareebu-plus/country-landmarks/kenya.jpg'),
    tanzania: require('../assets/kareebu-plus/country-landmarks/tanzania.jpg'),
  },
  ribbons: require('../assets/karibu/splash-ribbons.png'),
  flag: require('../assets/karibu/uganda-flag.png'),
  welcomeHero: require('../assets/karibu/premium/welcome-hero-premium.png'),
  // Semantic service atlas. Major service tiles use transparent commercial
  // photography; interface controls continue to use the vector icon system.
  service: {
    rides: require('../assets/kareebu-plus/lifestyle-cutouts/service-rides.png'),
    boda: require('../assets/kareebu-plus/lifestyle-cutouts/service-boda.png'),
    food: require('../assets/kareebu-plus/lifestyle-cutouts/service-food.png'),
    shops: require('../assets/kareebu-plus/lifestyle-cutouts/service-shops.png'),
    send: require('../assets/kareebu-plus/lifestyle-cutouts/service-send.png'),
    groceries: require('../assets/kareebu-plus/lifestyle-cutouts/service-groceries.png'),
    pay: require('../assets/kareebu-plus/realistic-v9/pay.png'),
    pharmacies: require('../assets/kareebu-plus/realistic-v9/pharmacy.jpg'),
    pharmacy: require('../assets/kareebu-plus/lifestyle-cutouts/service-pharmacy.png'),
    electronics: require('../assets/kareebu-plus/lifestyle-cutouts/service-electronics.png'),
    dineout: require('../assets/kareebu-plus/lifestyle-cutouts/service-dineout.png'),
    fix: require('../assets/kareebu-plus/lifestyle-cutouts/service-fix.png'),
    forGood: require('../assets/kareebu-plus/realistic-v9/flowers.jpg'),
    goOut: require('../assets/kareebu-plus/lifestyle-cutouts/service-go-out.png'),
    healthcare: require('../assets/kareebu-plus/realistic-v9/healthcare.jpg'),
    homeCare: require('../assets/kareebu-plus/lifestyle-cutouts/service-home-care.png'),
    homeServices: require('../assets/kareebu-plus/lifestyle-cutouts/service-home-care.png'),
    all: require('../assets/kareebu-plus/lifestyle-cutouts/service-shops.png'),
  },
  maps: {
    where: require('../assets/karibu/premium/where-map-premium.png'),
    driver: require('../assets/karibu/maps/driver.png'),
    onTrip: require('../assets/karibu/maps/on-trip.png'),
  },
  food: {
    promo: require('../assets/karibu/food/promo.png'),
    cafeJavas: require('../assets/karibu/food/cafe-javas.png'),
    chickenTonight: require('../assets/karibu/food/chicken-tonight.png'),
    tamaraThai: require('../assets/karibu/food/tamara-thai.png'),
    cafeJavasLoadedChapati: require('../assets/kareebu-plus/food/restaurants/menu/cafe_javas_loaded_chapati_combo.jpg'),
    chickenTonight12PcCombo: require('../assets/kareebu-plus/food/restaurants/menu/chicken_tonight_12pc_combo.jpg'),
    javaHouseChickenMushroomCurry: require('../assets/kareebu-plus/food/restaurants/menu/java_house_chicken_mushroom_medley_curry.png'),
  },
  restaurants: {
    cafeJavas: {
      logo: require('../assets/kareebu-plus/food/restaurants/logos/cafe_javas_logo_white.png'),
      logoBackgroundColor: '#123D35',
    },
    chickenTonight: {
      logo: require('../assets/kareebu-plus/food/restaurants/logos/chicken_tonight_uganda_logo.png'),
      logoBackgroundColor: '#FFFFFF',
    },
    javaHouse: {
      logo: require('../assets/kareebu-plus/food/restaurants/logos/java_house_uganda_logo.png'),
      logoBackgroundColor: '#FFFFFF',
    },
    pizzaInn: {
      logo: require('../assets/kareebu-plus/food/restaurants/logos/pizza_inn_africa_logo.png'),
      logoBackgroundColor: '#FFFFFF',
    },
  },
  shops: {
    promo: require('../assets/karibu/shops/promo.png'),
    jumia: require('../assets/karibu/shops/jumia.png'),
    carrefour: require('../assets/karibu/shops/carrefour.png'),
    game: require('../assets/karibu/shops/game.png'),
    pharmacy: require('../assets/karibu/shops/pharmacy.png'),
  },
  payment: {
    mtn: require('../assets/karibu/payment/mtn.png'),
    airtel: require('../assets/karibu/payment/airtel.png'),
    visa: require('../assets/karibu/payment/visa.png'),
  },
  avatars: {
    driver: require('../assets/karibu/avatars/driver.png'),
    account: require('../assets/karibu/premium/account-avatar-premium.png'),
  },
  cities: {
    kampala: require('../assets/kareebu-plus/cities/kampala.png'),
    entebbe: require('../assets/kareebu-plus/cities/entebbe.png'),
    jinja: require('../assets/kareebu-plus/cities/jinja.png'),
    wakiso: require('../assets/kareebu-plus/cities/wakiso.png'),
    mbarara: require('../assets/kareebu-plus/cities/mbarara.png'),
    gulu: require('../assets/kareebu-plus/cities/gulu.png'),
  },
};
