export type Screen =
  | 'splash'
  | 'welcome'
  | 'country'
  | 'city'
  | 'location'
  | 'locationPicker'
  | 'phone'
  | 'otp'
  | 'profile'
  | 'permissions'
  | 'home'
  | 'search'
  | 'assistant'
  | 'services'
  | 'place'
  | 'whereTo'
  | 'chooseRide'
  | 'confirmBooking'
  | 'driver'
  | 'onTrip'
  | 'tripComplete'
  | 'rateTrip'
  | 'food'
  | 'restaurant'
  | 'foodItem'
  | 'cart'
  | 'foodCheckout'
  | 'foodOrderSuccess'
  | 'orderTracking'
  | 'shops'
  | 'shop'
  | 'parcel'
  | 'wallet'
  | 'account'
  | 'activity'
  | 'orders';

export type BottomTab = 'home' | 'activity' | 'orders' | 'wallet' | 'account';
export type RideId = 'boda' | 'economy' | 'comfort' | 'xl' | 'delivery';
